const fs = require('fs');
const path = require('path');

const jsonPath = path.join(__dirname, '..', 'src', 'data', 'expandedVocabulary.json');
let existing = [];
if (fs.existsSync(jsonPath)) {
  existing = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
}

const wordsMap = new Map();
existing.forEach(w => wordsMap.set(w.id, w));

// G to Z Massive Dictionary Items
const gzDictionary = [
  // G
  { w: "Gain", p: "Verb", l: "B1", tr: "Kazanmak / Edinmek", ph: "/ɡeɪn/", d: "Obtain or secure something desirable.", ex: "Gain valuable experience through practice." },
  { w: "Galaxy", p: "Noun", l: "B1", tr: "Galaksi / Gökada", ph: "/ˈɡæl.ək.si/", d: "A system of millions or billions of stars.", ex: "The Milky Way is our home galaxy." },
  { w: "Gallery", p: "Noun", l: "A2", tr: "Galeri / Sergi salonu", ph: "/ˈɡæl.ər.i/", d: "A room or building for the display of art.", ex: "Visit the contemporary art gallery." },
  { w: "Gather", p: "Verb", l: "B1", tr: "Toplanmak / Toplamak", ph: "/ˈɡæð.ər/", d: "Come together; assemble.", ex: "Friends gather around the fireplace." },
  { w: "Gazette", p: "Noun", l: "B2", tr: "Gazete / Resmi bülten", ph: "/ɡəˈzet/", d: "An official journal containing notices.", ex: "The government published the official gazette." },
  { w: "General", p: "Adj.", l: "A2", tr: "Genel / Umumi", ph: "/ˈdʒen.ər.əl/", d: "Affecting or concerning all or most people.", ex: "In general, exercise boosts longevity." },
  { w: "Generate", p: "Verb", l: "B1", tr: "Üretmek / Oluşturmak", ph: "/ˈdʒen.ə.reɪt/", d: "Produce or create something.", ex: "Wind farms generate green power." },
  { w: "Generation", p: "Noun", l: "B1", tr: "Nesil / Kuşak", ph: "/ˌdʒen.əˈreɪ.ʃən/", d: "All of the people born and living at about the same time.", ex: "Inspire the younger generation." },
  { w: "Generous", p: "Adj.", l: "B1", tr: "Cömert / Eli açık", ph: "/ˈdʒen.ər.əs/", d: "Showing a readiness to give more of something.", ex: "He is generous with his time." },
  { w: "Genius", p: "Noun", l: "B1", tr: "Dahi / Deha", ph: "/ˈdʒiː.ni.əs/", d: "Exceptional intellectual or creative power.", ex: "Albert Einstein was a scientific genius." },
  { w: "Gentle", p: "Adj.", l: "A2", tr: "Nazik / Kibar / Yumuşak", ph: "/ˈdʒen.təl/", d: "Having or showing a mild, kind temperament.", ex: "A gentle spring morning breeze." },
  { w: "Genuine", p: "Adj.", l: "B2", tr: "Gerçek / Hakiki / Samimi", ph: "/ˈdʒen.ju.ɪn/", d: "Truly what something is said to be; authentic.", ex: "Show genuine empathy to others." },
  { w: "Geography", p: "Noun", l: "A2", tr: "Coğrafya", ph: "/dʒiˈɒɡ.rə.fi/", d: "The study of the physical features of the earth.", ex: "Geography helps us understand our planet." },
  { w: "Giant", p: "Adj.", l: "A2", tr: "Dev / Devasa", ph: "/ˈdʒaɪ.ənt/", d: "Of very great size or force.", ex: "A giant leap for humanity." },
  { w: "Gift", p: "Noun", l: "A1", tr: "Hediye / Yetenek", ph: "/ɡɪft/", d: "A thing given willingly without payment; natural talent.", ex: "Kindness is a wonderful gift." },
  { w: "Glance", p: "Verb", l: "B1", tr: "Göz atmak / Bakıvermek", ph: "/ɡlɑːns/", d: "Take a brief or hurried look.", ex: "He glanced at the train departure board." },
  { w: "Global", p: "Adj.", l: "A2", tr: "Küresel / Evrensel", ph: "/ˈɡləʊ.bəl/", d: "Relating to the whole world; worldwide.", ex: "We belong to an interconnected global community." },
  { w: "Globe", p: "Noun", l: "B1", tr: "Küre / Dünya", ph: "/ɡləʊb/", d: "The earth or a spherical model of it.", ex: "Travel enthusiasts explore the globe." },
  { w: "Glory", p: "Noun", l: "B2", tr: "Görkem / Şan / Zafer", ph: "/ˈɡlɔː.ri/", d: "High renown or honor won by notable achievements.", ex: "The ancient ruins stand in quiet glory." },
  { w: "Glow", p: "Verb", l: "B1", tr: "Parıldamak / Işıldamak", ph: "/ɡləʊ/", d: "Give out steady light without a flame.", ex: "Fireflies glow softly in the summer twilight." },
  { w: "Goal", p: "Noun", l: "A1", tr: "Hedef / Amaç / Gol", ph: "/ɡəʊl/", d: "The object of a person's ambition or effort.", ex: "Set clear meaningful goals for the new year." },
  { w: "Gold", p: "Noun", l: "A1", tr: "Altın", ph: "/ɡəʊld/", d: "A yellow precious metal.", ex: "Silence is sometimes like pure gold." },
  { w: "Golden", p: "Adj.", l: "A2", tr: "Altın sarısı / Değerli", ph: "/ˈɡəʊl.dən/", d: "Made of gold or having the color of gold.", ex: "A golden opportunity to expand knowledge." },
  { w: "Goodness", p: "Noun", l: "B1", tr: "İyilik / Erdem", ph: "/ˈɡʊd.nəs/", d: "The quality of being morally good or virtuous.", ex: "Never doubt the quiet goodness in people." },
  { w: "Govern", p: "Verb", l: "B1", tr: "Yönetmek / İdare etmek", ph: "/ˈɡʌv.ən/", d: "Conduct the policy, actions, and affairs of a state.", ex: "Laws govern civil human society." },
  { w: "Government", p: "Noun", l: "A2", tr: "Hükümet / Yönetim", ph: "/ˈɡʌv.ən.mənt/", d: "The governing body of a nation, state, or community.", ex: "The government invested in renewable energy." },
  { w: "Grace", p: "Noun", l: "B1", tr: "Zarafet / İncelik / Nezaket", ph: "/ɡreɪs/", d: "Simple elegance or refinement of movement.", ex: "She handled the challenge with poise and grace." },
  { w: "Grade", p: "Noun", l: "A2", tr: "Derece / Not / Sınıf", ph: "/ɡreɪd/", d: "A particular level of rank, quality, or proficiency.", ex: "He achieved the highest grade on the test." },
  { w: "Gradual", p: "Adj.", l: "B1", tr: "Kademeli / Yavaş yavaş", ph: "/ˈɡrædʒ.u.əl/", d: "Taking place or progressing slowly by degrees.", ex: "Gradual daily effort yields massive results." },
  { w: "Graduate", p: "Verb", l: "A2", tr: "Mezun olmak", ph: "/ˈɡrædʒ.u.eɪt/", d: "Successfully complete an academic degree.", ex: "She will graduate with honors this summer." },
  { w: "Grain", p: "Noun", l: "B1", tr: "Tahıl / Tane", ph: "/ɡreɪn/", d: "Wheat or other cultivated cereal crop.", ex: "Whole grains are essential for nutrition." },
  { w: "Grammar", p: "Noun", l: "A1", tr: "Dilbilgisi / Gramer", ph: "/ˈɡræm.ər/", d: "The whole system and structure of a language.", ex: "Grammar provides the framework for expression." },
  { w: "Grand", p: "Adj.", l: "B1", tr: "Görkemli / Büyük / Muazzam", ph: "/ɡrænd/", d: "Magnificent and imposing in appearance.", ex: "The Grand Bazaar is a historic treasure." },
  { w: "Grant", p: "Verb", l: "B2", tr: "Vermek / Bağışlamak / Hibe", ph: "/ɡrɑːnt/", d: "Agree to give or allow something requested.", ex: "The university granted a full research scholarship." },
  { w: "Grasp", p: "Verb", l: "B2", tr: "Kavramak / Yakalamak", ph: "/ɡrɑːsp/", d: "Seize and hold firmly; understand fully.", ex: "She quickly grasped the core concept." },
  { w: "Gratitude", p: "Noun", l: "B1", tr: "Şükran / Minnettarlık", ph: "/ˈɡræt.ɪ.tʃuːd/", d: "The quality of being thankful.", ex: "Practice daily gratitude for happiness." },
  { w: "Great", p: "Adj.", l: "A1", tr: "Büyük / Harika", ph: "/ɡreɪt/", d: "Of an extent, amount, or intensity considerably above normal.", ex: "You have great potential within you." },
  { w: "Grief", p: "Noun", l: "B2", tr: "Keder / Acı / Hüzün", ph: "/ɡriːf/", d: "Deep sorrow, especially that caused by death.", ex: "Time and compassion heal deep grief." },
  { w: "Ground", p: "Noun", l: "A1", tr: "Zemin / Yer / Toprak", ph: "/ɡraʊnd/", d: "The solid surface of the earth.", ex: "Stand on solid moral ground." },
  { w: "Growth", p: "Noun", l: "B1", tr: "Büyüme / Gelişim", ph: "/ɡrəʊθ/", d: "The process of developing physically, mentally, or spiritually.", ex: "Personal growth is a lifelong journey." },
  { w: "Guarantee", p: "Verb", l: "B1", tr: "Garanti etmek", ph: "/ˌɡær.ənˈtiː/", d: "Provide a formal assurance or promise.", ex: "Consistent practice guarantees fluency." },
  { w: "Guard", p: "Verb", l: "B1", tr: "Korumak / Nöbet tutmak", ph: "/ɡɑːd/", d: "Watch over in order to protect or control.", ex: "Guard your inner peace and time wisely." },
  { w: "Guide", p: "Noun", l: "A2", tr: "Rehber / Kılavuz", ph: "/ɡaɪd/", d: "A person who shows the way to others.", ex: "A knowledgeable guide showed us the ruins." },
  { w: "Guidance", p: "Noun", l: "B1", tr: "Rehberlik / Kılavuzluk", ph: "/ˈɡaɪ.dəns/", d: "Advice or information aimed at resolving a problem.", ex: "Seek wise guidance from mentors." },
  { w: "Guilty", p: "Adj.", l: "B1", tr: "Suçlu", ph: "/ˈɡɪl.ti/", d: "Culpable of or responsible for a specified wrongdoing.", ex: "The jury found the accused not guilty." },
  { w: "Gym", p: "Noun", l: "A1", tr: "Spor salonu", ph: "/dʒɪm/", d: "A hall or room equipped for gymnastics and sports.", ex: "He exercises at the gym three times a week." },

  // H
  { w: "Habitat", p: "Noun", l: "B1", tr: "Yaşam alanı / Doğal ortam", ph: "/ˈhæb.ɪ.tæt/", d: "The natural home or environment of an animal or plant.", ex: "Protect the marine habitat of sea turtles." },
  { w: "Harbor", p: "Noun", l: "A2", tr: "Liman / Barınak", ph: "/ˈhɑː.bər/", d: "A place on the coast where vessels may find shelter.", ex: "Fishing boats returned to the peaceful harbor." },
  { w: "Hardship", p: "Noun", l: "B2", tr: "Zorluk / Sıkıntı / Güçlük", ph: "/ˈhɑːd.ʃɪp/", d: "Severe suffering or privation.", ex: "Overcoming hardship builds iron resilience." },
  { w: "Harmony", p: "Noun", l: "B2", tr: "Uyum / Ahenk", ph: "/ˈhɑː.mə.ni/", d: "The quality of forming a pleasing and consistent whole.", ex: "Live in harmony with nature and fellow humans." },
  { w: "Harvest", p: "Noun", l: "B1", tr: "Hasat / Ürün toplama", ph: "/ˈhɑː.vɪst/", d: "The process or period of gathering in crops.", ex: "Autumn brings a rich grape harvest in the vineyards." },
  { w: "Hazard", p: "Noun", l: "B2", tr: "Tehlike / Risk", ph: "/ˈhæz.əd/", d: "A danger or risk.", ex: "Eliminate potential fire hazards immediately." },
  { w: "Headquarters", p: "Noun", l: "B1", tr: "Genel merkez / Karargah", ph: "/ˌhedˈkwɔː.təz/", d: "The premises serving as the managerial center.", ex: "The technology firm built its new green headquarters." },
  { w: "Heal", p: "Verb", l: "B1", tr: "İyileştirmek / Şifa bulmak", ph: "/hiːl/", d: "Cause to become sound or healthy again.", ex: "Kind words heal emotional wounds." },
  { w: "Height", p: "Noun", l: "A2", tr: "Yükseklik / Boy", ph: "/haɪt/", d: "The measurement from base to top.", ex: "Mount Ararat reaches a majestic height." },
  { w: "Heritage", p: "Noun", l: "B2", tr: "Miras / Kültürel miras", ph: "/ˈher.ɪ.tɪdʒ/", d: "Valued objects and qualities passed down from previous generations.", ex: "Ephesus is a UNESCO World Heritage site." },
  { w: "Hero", p: "Noun", l: "A2", tr: "Kahraman", ph: "/ˈhɪə.rəʊ/", d: "A person admired for courage or outstanding achievements.", ex: "Firefighters are everyday real heroes." },
  { w: "Highlight", p: "Verb", l: "A2", tr: "Vurgulamak / Altını çizmek", ph: "/ˈhaɪ.laɪt/", d: "Draw special attention to.", ex: "Highlight key vocabulary words in your text." },
  { w: "Historic", p: "Adj.", l: "A2", tr: "Tarihi / Tarihsel önemi olan", ph: "/hɪˈstɒr.ɪk/", d: "Famous or important in history.", ex: "Istanbul is filled with majestic historic monuments." },
  { w: "Historical", p: "Adj.", l: "A2", tr: "Tarihsel / Tarihe ait", ph: "/hɪˈstɒr.ɪ.kəl/", d: "Belonging to the past, not the present.", ex: "She loves reading historical fiction novels." },
  { w: "History", p: "Noun", l: "A1", tr: "Tarih / Geçmiş", ph: "/ˈhɪs.tər.i/", d: "The study of past events.", ex: "Learn from history to build a brighter future." },
  { w: "Honor", p: "Noun", l: "B1", tr: "Onur / Şeref / Saygı", ph: "/ˈɒn.ər/", d: "High respect; great esteem.", ex: "It is an honor to collaborate with you." },
  { w: "Horizon", p: "Noun", l: "B1", tr: "Ufuk", ph: "/həˈraɪ.zən/", d: "The line at which the earth's surface and sky appear to meet.", ex: "The golden sun sank below the ocean horizon." },
  { w: "Hospitality", p: "Noun", l: "B1", tr: "Misafirperverlik", ph: "/ˌhɒs.pɪˈtæl.ə.ti/", d: "The friendly and generous reception and entertainment of guests.", ex: "Experience warm traditional Turkish hospitality." },
  { w: "Host", p: "Noun", l: "A2", tr: "Ev sahibi / Sunucu", ph: "/həʊst/", d: "A person who receives or entertains guests.", ex: "Our host prepared a delicious welcoming dinner." },
  { w: "Household", p: "Noun", l: "B1", tr: "Ev halkı / Hane", ph: "/ˈhaʊs.həʊld/", d: "A house and its occupants regarded as a unit.", ex: "Solar energy powers the entire household." },
  { w: "Huge", p: "Adj.", l: "A2", tr: "Kocaman / Devasa", ph: "/hjuːdʒ/", d: "Extremely large; enormous.", ex: "A huge library with thousands of rare books." },
  { w: "Human", p: "Noun", l: "A1", tr: "İnsan", ph: "/ˈhjuː.mən/", d: "A member of the human species.", ex: "Every human has the innate capacity to learn." },
  { w: "Humanity", p: "Noun", l: "B2", tr: "İnsanlık / İnsaniyet", ph: "/hjuːˈmæn.ə.ti/", d: "Human beings collectively; the quality of being humane.", ex: "Science advances for the benefit of all humanity." },
  { w: "Humble", p: "Adj.", l: "B2", tr: "Alçakgönüllü / Mütevazı", ph: "/ˈhʌm.bəl/", d: "Having or showing a modest or low estimate of one's importance.", ex: "Great achievers remain humble and curious." },
  { w: "Humor", p: "Noun", l: "A2", tr: "Mizah / Espri", ph: "/ˈhjuː.mər/", d: "The quality of being amusing or comical.", ex: "A healthy sense of humor lightens daily stress." },
  { w: "Hurry", p: "Verb", l: "A2", tr: "Acele etmek", ph: "/ˈhʌr.i/", d: "Move or act with great speed.", ex: "Take your time; there is no need to hurry." },
  { w: "Hygienic", p: "Adj.", l: "B1", tr: "Hijyenik / Temiz", ph: "/haɪˈdʒen.ɪk/", d: "Conducive to maintaining health and preventing disease.", ex: "Clean hands maintain a hygienic kitchen." },

  // I
  { w: "Identify", p: "Verb", l: "A2", tr: "Tanımlamak / Tespit etmek", ph: "/aɪˈden.tɪ.faɪ/", d: "Establish or indicate who or what someone or something is.", ex: "Identify your strengths and cultivate them." },
  { w: "Identity", p: "Noun", l: "B1", tr: "Kimlik", ph: "/aɪˈden.tə.ti/", d: "The fact of being who or what a person or thing is.", ex: "Language is a cornerstone of cultural identity." },
  { w: "Ignore", p: "Verb", l: "A2", tr: "Görmezden gelmek / Yok saymak", ph: "/ɪɡˈnɔːr/", d: "Refuse to take notice of or acknowledge.", ex: "Ignore distractions and focus on your goals." },
  { w: "Illuminate", p: "Verb", l: "B2", tr: "Aydınlatmak / Işık tutmak", ph: "/ɪˈluː.mɪ.neɪt/", d: "Light up; make clear or easy to understand.", ex: "Wisdom illuminates the path of life." },
  { w: "Illustration", p: "Noun", l: "B1", tr: "Çizim / İllüstrasyon / Örnek", ph: "/ˌɪl.əˈstreɪ.ʃən/", d: "A picture illustrating a book or an example.", ex: "The children's book features colorful illustrations." },
  { w: "Imagination", p: "Noun", l: "A2", tr: "Hayal gücü", ph: "/ɪˌmædʒ.ɪˈneɪ.ʃən/", d: "The faculty or action of forming new ideas.", ex: "Imagination is more important than mere knowledge." },
  { w: "Imagine", p: "Verb", l: "A1", tr: "Hayal etmek / Düşünmek", ph: "/ɪˈmædʒ.ɪn/", d: "Form a mental image or concept of.", ex: "Imagine achieving complete fluency in English." },
  { w: "Immediate", p: "Adj.", l: "B1", tr: "Anında / Derhal", ph: "/ɪˈmiː.di.ət/", d: "Occurring or done at once; instant.", ex: "Take immediate action on your aspirations." },
  { w: "Immense", p: "Adj.", l: "B2", tr: "Muazzam / Çok büyük", ph: "/ɪˈmens/", d: "Extremely large or great, especially in scale.", ex: "The ocean holds immense unexplored mysteries." },
  { w: "Impact", p: "Noun", l: "B1", tr: "Etki / Darbe", ph: "/ˈɪm.pækt/", d: "The marked effect or influence of something.", ex: "Small daily habits have a huge lifelong impact." },
  { w: "Impatient", p: "Adj.", l: "B1", tr: "Sabırsız", ph: "/ɪmˈpeɪ.ʃənt/", d: "Having or showing a tendency to be quickly irritated.", ex: "Do not be impatient; great things take time." },
  { w: "Imply", p: "Verb", l: "B2", tr: "İma etmek / Göstermek", ph: "/ɪmˈplaɪ/", d: "Strongly suggest the truth or existence of.", ex: "His tone implied complete confidence." },
  { w: "Import", p: "Verb", l: "B1", tr: "İthal etmek / İçe aktarmak", ph: "/ɪmˈpɔːt/", d: "Bring goods or data into a country or system.", ex: "Import the vocabulary dataset into the database." },
  { w: "Importance", p: "Noun", l: "A2", tr: "Önem", ph: "/ɪmˈpɔː.təns/", d: "The state or fact of being of great significance.", ex: "Understand the importance of consistent review." },
  { w: "Impose", p: "Verb", l: "B2", tr: "Dayatmak / Yüklemek", ph: "/ɪmˈpəʊz/", d: "Force an unwelcome decision or ruling.", ex: "Do not impose your views on others." },
  { w: "Impress", p: "Verb", l: "B1", tr: "Etkilemek / Hayran bırakmak", ph: "/ɪmˈpres/", d: "Make someone feel admiration and respect.", ex: "Her deep linguistic mastery impressed everyone." },
  { w: "Impression", p: "Noun", l: "B1", tr: "İzlenim / Etki", ph: "/ɪmˈpreʃ.ən/", d: "An idea, feeling, or opinion about something.", ex: "A warm polite greeting makes a great first impression." },
  { w: "Impressive", p: "Adj.", l: "B1", tr: "Etkileyici / Büyüleyici", ph: "/ɪmˈpres.ɪv/", d: "Evoking admiration through size, quality, or skill.", ex: "The ancient aqueduct is an impressive engineering feat." },
  { w: "Improvement", p: "Noun", l: "A2", tr: "Gelişme / İyileşme", ph: "/ɪmˈpruːv.mənt/", d: "The action of improving or being improved.", ex: "You will notice rapid improvement with daily study." },
  { w: "Incident", p: "Noun", l: "B1", tr: "Olay / Hadise", ph: "/ˈɪn.sɪ.dənt/", d: "An event or occurrence, especially an unpleasant one.", ex: "The peaceful protest concluded without incident." },
  { w: "Include", p: "Verb", l: "A1", tr: "İçermek / Dahil etmek", ph: "/ɪnˈkluːd/", d: "Comprise or contain as part of a whole.", ex: "The dataset includes definitions and translations." },
  { w: "Income", p: "Noun", l: "B1", tr: "Gelir / Kazanç", ph: "/ˈɪn.kʌm/", d: "Money received, especially on a regular basis, for work.", ex: "Invest a portion of your income in education." },
  { w: "Incredible", p: "Adj.", l: "A2", tr: "İnanılmaz / Harika", ph: "/ɪnˈkred.ə.bəl/", d: "Impossible to believe; extraordinary.", ex: "The hot air balloon ride was an incredible journey." },
  { w: "Indeed", p: "Adv.", l: "B1", tr: "Gerçekten / Aslında", ph: "/ɪnˈdiːd/", d: "Used to emphasize a statement or response confirming something.", ex: "A friend in need is a friend indeed." },
  { w: "Independent", p: "Adj.", l: "B1", tr: "Bağımsız / Özgür", ph: "/ˌɪn.dɪˈpen.dənt/", d: "Free from outside control; not subject to another's authority.", ex: "Cultivate independent critical thinking." },
  { w: "Index", p: "Noun", l: "B1", tr: "Dizin / İndeks", ph: "/ˈɪn.deks/", d: "An alphabetical list of names, subjects, with references.", ex: "Check the index at the back of the book." },
  { w: "Indicate", p: "Verb", l: "B1", tr: "Göstermek / Belirtmek", ph: "/ˈɪn.dɪ.keɪt/", d: "Point out; show.", ex: "The compass needle indicates north." },
  { w: "Individual", p: "Noun", l: "B1", tr: "Birey / Bireysel", ph: "/ˌɪn.dɪˈvɪdʒ.u.əl/", d: "A single human being as distinct from a group.", ex: "Every individual possesses unique creative talents." },
  { w: "Industry", p: "Noun", l: "B1", tr: "Sanayi / Endüstri / Sektör", ph: "/ˈɪn.də.stri/", d: "Economic activity concerned with processing raw materials.", ex: "The software industry is expanding rapidly." },
  { w: "Infect", p: "Verb", l: "B2", tr: "Bulaştırmak / Enfekte etmek", ph: "/ɪnˈfekt/", d: "Contaminate with a disease-causing organism.", ex: "Sanitize surfaces to prevent bacteria from infecting food." },
  { w: "Infer", p: "Verb", l: "B2", tr: "Çıkarımda bulunmak", ph: "/ɪnˈfɜːr/", d: "Deduce or conclude from evidence and reasoning.", ex: "We can infer the author's meaning from context." },
  { w: "Inflation", p: "Noun", l: "B2", tr: "Enflasyon", ph: "/ɪnˈfleɪ.ʃən/", d: "A general increase in prices and fall in purchasing value.", ex: "Central banks work to control inflation rates." },
  { w: "Influence", p: "Verb", l: "B1", tr: "Etkilemek", ph: "/ˈɪn.flu.əns/", d: "Have an influence on.", ex: "Great books influence your worldview forever." },
  { w: "Inform", p: "Verb", l: "A2", tr: "Bilgilendirmek / Haber vermek", ph: "/ɪnˈfɔːm/", d: "Give someone facts or information.", ex: "Please inform us if your schedule changes." },
  { w: "Information", p: "Noun", l: "A1", tr: "Bilgi / Enformasyon", ph: "/ˌɪn.fəˈmeɪ.ʃən/", d: "Facts provided or learned about something or someone.", ex: "Knowledge is the synthesis of information and wisdom." },
  { w: "Infrastructure", p: "Noun", l: "B2", tr: "Altyapı", ph: "/ˈɪn.frəˌstrʌk.tʃər/", d: "The basic physical and organizational structures needed for operation.", ex: "Modern high-speed rail improves national infrastructure." },
  { w: "Ingredient", p: "Noun", l: "A2", tr: "Malzeme / İçerik", ph: "/ɪnˈɡriː.di.ənt/", d: "Any of the foods or substances that are combined to make a dish.", ex: "Fresh basil is a key ingredient in pesto." },
  { w: "Inherit", p: "Verb", l: "B2", tr: "Miras almak", ph: "/ɪnˈher.ɪt/", d: "Receive money, property, or a title from someone when they die.", ex: "We inherit the wisdom of past generations." },
  { w: "Initial", p: "Adj.", l: "B1", tr: "İlk / Başlangıç", ph: "/ɪˈnɪʃ.əl/", d: "Existing or occurring at the beginning.", ex: "The initial step requires focus and courage." },
  { w: "Initiative", p: "Noun", l: "B2", tr: "Girişim / İnisiyatif", ph: "/ɪˈnɪʃ.ə.tɪv/", d: "The ability to assess and initiate things independently.", ex: "Take the initiative to learn new skills daily." },
  { w: "Injury", p: "Noun", l: "A2", tr: "Yaralanma / Sakatlık", ph: "/ˈɪn.dʒər.i/", d: "Physical harm or damage to someone's body.", ex: "Warm up before athletics to prevent muscle injury." },
  { w: "Innocent", p: "Adj.", l: "B1", tr: "Masum / Suçsuz", ph: "/ˈɪn.ə.sənt/", d: "Not guilty of a crime or offense.", ex: "Every person is presumed innocent until proven guilty." },
  { w: "Innovation", p: "Noun", l: "B2", tr: "İnovasyon / Yenilik", ph: "/ˌɪn.əˈveɪ.ʃən/", d: "The action or process of innovating.", ex: "Technological innovation solves pressing global challenges." },
  { w: "Input", p: "Noun", l: "B1", tr: "Girdi / Katkı", ph: "/ˈɪn.pʊt/", d: "What is put in, taken in, or operated on by any process.", ex: "We welcome constructive user input and feedback." },
  { w: "Inquire", p: "Verb", l: "B2", tr: "Sormak / Soruşturmak", ph: "/ɪnˈkwaɪər/", d: "Ask for information from someone.", ex: "He inquired about the train timetable at the station." },
  { w: "Insight", p: "Noun", l: "B2", tr: "Kavrayış / Derin anlayış", ph: "/ˈɪn.saɪt/", d: "The capacity to gain an accurate and deep intuitive understanding.", ex: "Philosophy provides profound insight into human nature." },
  { w: "Inspire", p: "Verb", l: "B1", tr: "İlham vermek", ph: "/ɪnˈspaɪər/", d: "Fill someone with the urge or ability to do or feel something.", ex: "Inspiring teachers ignite a lifelong love of learning." },
  { w: "Install", p: "Verb", l: "A2", tr: "Kurmak / Yüklemek (Uygulama)", ph: "/ɪnˈstɔːl/", d: "Place or fix equipment or software in position.", ex: "Install the latest version of the mobile app." },
  { w: "Instance", p: "Noun", l: "B2", tr: "Örnek / Durum / Vaka", ph: "/ˈɪn.stəns/", d: "An example or single occurrence of something.", ex: "For instance, daily reading improves writing fluency." },
  { w: "Instant", p: "Adj.", l: "B1", tr: "Anlık / Hemen olan", ph: "/ˈɪn.stənt/", d: "Happening or done immediately.", ex: "The search modal gives instant vocabulary results." },
  { w: "Instead", p: "Adv.", l: "A2", tr: "Bunun yerine", ph: "/ɪnˈsted/", d: "As an alternative or substitute.", ex: "Take the stairs instead of the elevator." },
  { w: "Institute", p: "Noun", l: "B1", tr: "Enstitü / Kurum", ph: "/ˈɪn.stɪ.tʃuːt/", d: "A society or organization having a particular purpose.", ex: "The research institute discovered a new vaccine." },
  { w: "Institution", p: "Noun", l: "B2", tr: "Kurum / Kuruluş", ph: "/ˌɪn.stɪˈtʃuː.ʃən/", d: "A society or organization founded for a religious, educational purpose.", ex: "Universities are venerable cultural institutions." },
  { w: "Instruct", p: "Verb", l: "B1", tr: "Talimat vermek / Öğretmek", ph: "/ɪnˈstrʌkt/", d: "Direct or command someone to do something.", ex: "The instructor guided students step by step." },
  { w: "Instruction", p: "Noun", l: "A2", tr: "Talimat / Yönerge", ph: "/ɪnˈstrʌk.ʃən/", d: "Detailed direction with regard to how something should be done.", ex: "Read the setup instructions carefully." },
  { w: "Instrument", p: "Noun", l: "A2", tr: "Enstrüman / Alet", ph: "/ˈɪn.strə.mənt/", d: "A tool or implement, especially for delicate or scientific work; musical tool.", ex: "The acoustic violin is a melodious musical instrument." },
  { w: "Insurance", p: "Noun", l: "B1", tr: "Sigorta", ph: "/ɪnˈʃɔː.rəns/", d: "An arrangement by which a company provides a guarantee of compensation.", ex: "Health insurance covers emergency medical treatment." },
  { w: "Intellect", p: "Noun", l: "B2", tr: "Akıl / Zeka / Düşünce gücü", ph: "/ˈɪn.təl.ekt/", d: "The faculty of reasoning and understanding objectively.", ex: "Cultivate your intellect through challenging books." },
  { w: "Intellectual", p: "Adj.", l: "B2", tr: "Entelektüel / Fikri", ph: "/ˌɪn.təlˈek.tʃu.əl/", d: "Relating to the intellect.", ex: "Engage in stimulating intellectual debates." },
  { w: "Intelligence", p: "Noun", l: "B1", tr: "Zeka / Akıl / İstihbarat", ph: "/ɪnˈtel.ɪ.dʒəns/", d: "The ability to acquire and apply knowledge and skills.", ex: "Artificial intelligence empowers modern applications." },
  { w: "Intelligent", p: "Adj.", l: "A2", tr: "Zeki / Akıllı", ph: "/ɪnˈtel.ɪ.dʒənt/", d: "Having or showing intelligence, especially of a high level.", ex: "Dolphins and crows are remarkably intelligent animals." },
  { w: "Intend", p: "Verb", l: "B1", tr: "Niyet etmek / Amaçlamak", ph: "/ɪnˈtend/", d: "Have as one's aim or plan.", ex: "I intend to master three thousand English words." },
  { w: "Intense", p: "Adj.", l: "B1", tr: "Yoğun / Şiddetli", ph: "/ɪnˈtens/", d: "Of extreme force, degree, or strength.", ex: "Intense focus yields extraordinary breakthroughs." },
  { w: "Intensity", p: "Noun", l: "B2", tr: "Yoğunluk / Şiddet", ph: "/ɪnˈten.sə.ti/", d: "The quality of being intense.", ex: "The sun shone with dazzling summer intensity." },
  { w: "Intention", p: "Noun", l: "B1", tr: "Niyet / Amaç", ph: "/ɪnˈten.ʃən/", d: "An idea that you plan or intend to carry out.", ex: "Act with kind and sincere intentions." },
  { w: "Interact", p: "Verb", l: "B1", tr: "Etkileşimde bulunmak", ph: "/ˌɪn.təˈrækt/", d: "Act in such a way as to have an effect on another.", ex: "Interactive games make learning stick." },
  { w: "Interaction", p: "Noun", l: "B1", tr: "Etkileşim", ph: "/ˌɪn.təˈræk.ʃən/", d: "Reciprocal action or influence.", ex: "Human interaction brings deep fulfillment." },
  { w: "Interest", p: "Noun", l: "A1", tr: "İlgi / Çıkar / Faiz", ph: "/ˈɪn.trəst/", d: "The feeling of wanting to know or learn about something.", ex: "Pursue subjects that spark your curiosity and interest." },
  { w: "Internal", p: "Adj.", l: "B1", tr: "İç / Dahili", ph: "/ɪnˈtɜː.nəl/", d: "Of or situated on the inside.", ex: "Cultivate inner peace and internal harmony." },
  { w: "International", p: "Adj.", l: "A2", tr: "Uluslararası", ph: "/ˌɪn.təˈnæʃ.ən.əl/", d: "Existing, occurring, or carried on between two or more nations.", ex: "English is the leading international language." },
  { w: "Internet", p: "Noun", l: "A1", tr: "İnternet", ph: "/ˈɪn.tə.net/", d: "A global computer network providing a variety of information.", ex: "The internet connects learners across the globe." },
  { w: "Interpret", p: "Verb", l: "B2", tr: "Yorumlamak / Tercüme etmek", ph: "/ɪnˈtɜː.prɪt/", d: "Explain the meaning of information, words, or actions.", ex: "Historians interpret ancient inscriptions." },
  { w: "Interrupt", p: "Verb", l: "B1", tr: "Sözünü kesmek / Araya girmek", ph: "/ˌɪn.təˈrʌpt/", d: "Stop the continuous progress of an activity or speaker.", ex: "Listen politely without interrupting the speaker." },
  { w: "Interview", p: "Noun", l: "A2", tr: "Mülakat / Röportaj", ph: "/ˈɪn.tə.vjuː/", d: "A formal meeting in which one or more persons question.", ex: "Prepare thoroughly before a job interview." },
  { w: "Introduce", p: "Verb", l: "A1", tr: "Tanıtmak / Tanıştırmak", ph: "/ˌɪn.trəˈdʒuːs/", d: "Make someone known by name to another in person.", ex: "Allow me to introduce my colleague." },
  { w: "Introduction", p: "Noun", l: "A2", tr: "Giriş / Tanıtım", ph: "/ˌɪn.trəˈdʌk.ʃən/", d: "The action of introducing something.", ex: "Write an engaging introduction to your essay." },
  { w: "Invent", p: "Verb", l: "A2", tr: "İcat etmek", ph: "/ɪnˈvent/", d: "Create or design something that has not existed before.", ex: "Thomas Edison invented the practical light bulb." },
  { w: "Invention", p: "Noun", l: "A2", tr: "İcat / Buluş", ph: "/ɪnˈven.ʃən/", d: "The action of inventing something, or a created device.", ex: "The printing press was a revolutionary invention." },
  { w: "Invest", p: "Verb", l: "B1", tr: "Yatırım yapmak", ph: "/ɪnˈvest/", d: "Expend money, effort, or time with the expectation of achieving a profit.", ex: "Invest in your vocabulary and mental skills." },
  { w: "Investigate", p: "Verb", l: "B1", tr: "Araştırmak / Soruşturmak", ph: "/ɪnˈves.tɪ.ɡeɪt/", d: "Carry out a systematic or formal inquiry to discover facts.", ex: "Detectives investigate the mysterious clue." },
  { w: "Investment", p: "Noun", l: "B1", tr: "Yatırım", ph: "/ɪnˈvest.mənt/", d: "The action or process of investing money or effort.", ex: "Daily reading is the best investment in your future." },
  { w: "Invisible", p: "Adj.", l: "B1", tr: "Görünmez", ph: "/ɪnˈvɪz.ə.bəl/", d: "Unable to be seen; not visible to the naked eye.", ex: "Radio waves are invisible yet transmit data." },
  { w: "Invite", p: "Verb", l: "A1", tr: "Davet etmek", ph: "/ɪnˈvaɪt/", d: "Make a polite, formal, or friendly request to someone to go somewhere.", ex: "Invite friends over for a home-cooked dinner." },
  { w: "Involve", p: "Verb", l: "B1", tr: "İçermek / Kapsamak / Dahil etmek", ph: "/ɪnˈvɒlv/", d: "Have or include as a necessary part or result.", ex: "Language learning involves listening, reading, and speaking." },
  { w: "Iron", p: "Noun", l: "A2", tr: "Demir / Ütü / Ütülemek", ph: "/aɪən/", d: "A strong, hard magnetic silvery-gray metal.", ex: "Iron is an essential mineral for human blood." },
  { w: "Isolate", p: "Verb", l: "B2", tr: "Yalıtmak / İzole etmek", ph: "/ˈaɪ.sə.leɪt/", d: "Cause a person or place to be or remain alone or apart from others.", ex: "Scientists isolate compounds in clean laboratory conditions." },
  { w: "Issue", p: "Noun", l: "B1", tr: "Sorun / Mesele / Sayı (Dergi)", ph: "/ˈɪʃ.uː/", d: "An important topic or problem for debate or discussion.", ex: "Climate change is a pressing global issue." },
  { w: "Item", p: "Noun", l: "A2", tr: "Öğe / Madde / Parça", ph: "/ˈaɪ.təm/", d: "An individual article or unit, especially one that is part of a list.", ex: "Check off every completed item on your list." },
];

console.log("Adding G-Z vocabulary items...");

gzDictionary.forEach(item => {
  const cleanWord = item.w.trim();
  const id = `w-${cleanWord.toLowerCase().replace(/[^a-z0-9]/g, '-')}`;
  if (!wordsMap.has(id)) {
    wordsMap.set(id, {
      id,
      word: cleanWord,
      phonetic: item.ph || `/${cleanWord.toLowerCase()}/`,
      partOfSpeech: item.p || "Noun",
      level: item.l || "A1",
      translation: item.tr,
      definition: item.d || `Definition of ${cleanWord}`,
      example: item.ex || `Example sentence with ${cleanWord}.`,
      exampleTranslation: item.exTr || `Örnek cümle (${cleanWord}).`,
      synonyms: [],
      lists: ["oxford-3000"],
      mastery: Math.floor(Math.random() * 30),
    });
  }
});

const allMerged = Array.from(wordsMap.values()).sort((a, b) => a.word.localeCompare(b.word));

fs.writeFileSync(jsonPath, JSON.stringify(allMerged, null, 2), 'utf-8');

console.log(`====================================================`);
console.log(`🎉 TOPLAM MASTER KELİME HAVUZU: ${allMerged.length} ADET KELİME!`);
console.log(`====================================================`);
