/**
 * Oxford 3000 & CEFR A1-C2 Kapsamlı Kelime Üreteci
 * Bu betik, 1.000+ adet temel ve ileri düzey İngilizce kelimeyi
 * Türkçe karşılıkları, seviyeleri, fonetik okunuşları ve tanımlarıyla derler.
 */

const fs = require('fs');
const path = require('path');

// Temel Kelime Havuzu (Seviye ve Türlerine Göre Kategorize Edilmiş 1.000+ Kelime)
const wordPool = [
  // --- A1 Seviyesi (250+ Kelime) ---
  { w: "About", p: "Adv.", l: "A1", tr: "Hakkında / Yaklaşık", ph: "/əˈbaʊt/", d: "On the subject of; concerning.", ex: "Tell me about your family.", exTr: "Bana ailenden bahset." },
  { w: "Above", p: "Adv.", l: "A1", tr: "Yukarıda / Üzerinde", ph: "/əˈbʌv/", d: "At a higher level or position.", ex: "The plane flew above the clouds.", exTr: "Uçak bulutların üzerinde uçtu." },
  { w: "Across", p: "Adv.", l: "A1", tr: "Karşısında / Karşıdan karşıya", ph: "/əˈkrɒs/", d: "From one side to the other side.", ex: "He walked across the street.", exTr: "Caddenin karşısına yürüdü." },
  { w: "Action", p: "Noun", l: "A1", tr: "Eylem / Hareket", ph: "/ˈæk.ʃən/", d: "The process of doing something.", ex: "We need urgent action now.", exTr: "Şimdi acil eyleme ihtiyacımız var." },
  { w: "Activity", p: "Noun", l: "A1", tr: "Etkinlik / Faaliyet", ph: "/ækˈtɪv.ə.ti/", d: "A thing that a person or group does.", ex: "Outdoor activity is healthy.", exTr: "Açık hava etkinliği sağlıklıdır." },
  { w: "Actor", p: "Noun", l: "A1", tr: "Aktör / Erkek Oyuncu", ph: "/ˈæk.tər/", d: "A person who acts in a play or film.", ex: "He is a famous theater actor.", exTr: "O ünlü bir tiyatro oyuncusudur." },
  { w: "Actress", p: "Noun", l: "A1", tr: "Aktris / Kadın Oyuncu", ph: "/ˈæk.trəs/", d: "A woman who acts in a play or film.", ex: "The actress won a prestigious award.", exTr: "Aktris prestijli bir ödül kazandı." },
  { w: "Address", p: "Noun", l: "A1", tr: "Adres", ph: "/əˈdres/", d: "The details of where someone lives.", ex: "Write down your postal address.", exTr: "Posta adresinizi yazın." },
  { w: "Adult", p: "Noun", l: "A1", tr: "Yetişkin", ph: "/ˈæd.ʌlt/", d: "A fully grown human being.", ex: "Tickets for adults cost ten dollars.", exTr: "Yetişkinler için biletler on dolar." },
  { w: "Advice", p: "Noun", l: "A1", tr: "Tavsiye / Öğüt", ph: "/ədˈvaɪs/", d: "Guidance or recommendations.", ex: "She gave me valuable career advice.", exTr: "Bana değerli bir kariyer tavsiyesi verdi." },
  { w: "Afraid", p: "Adj.", l: "A1", tr: "Korkmuş", ph: "/əˈfreɪd/", d: "Feeling fear or apprehension.", ex: "Do not be afraid of change.", exTr: "Değişimden korkmayın." },
  { w: "Afternoon", p: "Noun", l: "A1", tr: "Öğleden sonra", ph: "/ˌɑːf.təˈnuːn/", d: "The time from noon to evening.", ex: "Let's meet tomorrow afternoon.", exTr: "Yarın öğleden sonra buluşalım." },
  { w: "Again", p: "Adv.", l: "A1", tr: "Tekrar / Yeniden", ph: "/əˈɡen/", d: "Another time; once more.", ex: "Could you please say that again?", exTr: "Onu tekrar söyleyebilir misiniz lütfen?" },
  { w: "Airport", p: "Noun", l: "A1", tr: "Havalimanı", ph: "/ˈeə.pɔːt/", d: "A place where planes land and depart.", ex: "We arrived at the airport on time.", exTr: "Havalimanına zamanında vardık." },
  { w: "Almost", p: "Adv.", l: "A1", tr: "Neredeyse / Hemen hemen", ph: "/ˈɔːl.məʊst/", d: "Not quite; very nearly.", ex: "Dinner is almost ready to serve.", exTr: "Akşam yemeği servise neredeyse hazır." },
  { w: "Alone", p: "Adj.", l: "A1", tr: "Yalnız / Tek başına", ph: "/əˈləʊn/", d: "Having no one else present.", ex: "She enjoys hiking alone in nature.", exTr: "Doğada yalnız yürüyüş yapmaktan hoşlanır." },
  { w: "Already", p: "Adv.", l: "A1", tr: "Zaten / Çoktan", ph: "/ɔːlˈred.i/", d: "Before the present time.", ex: "I have already booked the flight.", exTr: "Uçuşu çoktan rezerve ettim." },
  { w: "Always", p: "Adv.", l: "A1", tr: "Her zaman / Daima", ph: "/ˈɔːl.weɪz/", d: "At all times; constantly.", ex: "He always arrives five minutes early.", exTr: "Her zaman beş dakika erken gelir." },
  { w: "Amazing", p: "Adj.", l: "A1", tr: "İnanılmaz / Harika", ph: "/əˈmeɪ.zɪŋ/", d: "Causing great surprise or wonder.", ex: "The mountain view was amazing.", exTr: "Dağ manzarası harikaydı." },
  { w: "Angry", p: "Adj.", l: "A1", tr: "Kızgın / Öfkeli", ph: "/ˈæŋ.ɡri/", d: "Feeling or showing strong displeasure.", ex: "There is no reason to be angry.", exTr: "Kızgın olmak için bir neden yok." },
  { w: "Animal", p: "Noun", l: "A1", tr: "Hayvan", ph: "/ˈæn.ɪ.məl/", d: "A living organism that feeds on matter.", ex: "Dolphins are very intelligent animals.", exTr: "Yunuslar çok zeki hayvanlardır." },
  { w: "Answer", p: "Noun", l: "A1", tr: "Cevap / Yanıt", ph: "/ˈɑːn.sər/", d: "A response to a question.", ex: "Give a direct and honest answer.", exTr: "Doğrudan ve dürüst bir cevap verin." },
  { w: "Apartment", p: "Noun", l: "A1", tr: "Daire / Apartman dairesi", ph: "/əˈpɑːt.mənt/", d: "A set of rooms for living in.", ex: "They live in a cozy new apartment.", exTr: "Şirin yeni bir dairede yaşıyorlar." },
  { w: "Apple", p: "Noun", l: "A1", tr: "Elma", ph: "/ˈæp.əl/", d: "A crisp red or green fruit.", ex: "Eat a fresh apple every morning.", exTr: "Her sabah taze bir elma yiyin." },
  { w: "April", p: "Noun", l: "A1", tr: "Nisan", ph: "/ˈeɪ.prəl/", d: "The fourth month of the year.", ex: "Spring blossoms bloom in April.", exTr: "Bahar çiçekleri Nisan'da açar." },
  { w: "Area", p: "Noun", l: "A1", tr: "Alan / Bölge", ph: "/ˈeə.ri.ə/", d: "A region or part of a town.", ex: "This is a quiet residential area.", exTr: "Burası sessiz bir yerleşim alanıdır." },
  { w: "Arm", p: "Noun", l: "A1", tr: "Kol", ph: "/ɑːm/", d: "Each of the two upper limbs of human body.", ex: "He raised his right arm to wave.", exTr: "El sallamak için sağ kolunu kaldırdı." },
  { w: "Around", p: "Adv.", l: "A1", tr: "Etrafında / Çevresinde", ph: "/əˈraʊnd/", d: "Located on every side of.", ex: "They sat around the warm bonfire.", exTr: "Sıcak kamp ateşinin etrafında oturdular." },
  { w: "Arrive", p: "Verb", l: "A1", tr: "Varmak / Ulaşmak", ph: "/əˈraɪv/", d: "Reach a destination.", ex: "We will arrive in Istanbul at dusk.", exTr: "Alacakaranlıkta İstanbul'a varacağız." },
  { w: "Artist", p: "Noun", l: "A1", tr: "Sanatçı / Ressam", ph: "/ˈɑː.tɪst/", d: "A creator of visual art.", ex: "The artist painted an oil canvas.", exTr: "Sanatçı bir yağlı boya tuvali yaptı." },
  { w: "August", p: "Noun", l: "A1", tr: "Ağustos", ph: "/ɔːˈɡʌst/", d: "The eighth month of the year.", ex: "August is the hottest summer month.", exTr: "Ağustos en sıcak yaz ayıdır." },
  { w: "Autumn", p: "Noun", l: "A1", tr: "Sonbahar", ph: "/ˈɔː.təm/", d: "The season between summer and winter.", ex: "Golden leaves fall in autumn.", exTr: "Altın yapraklar sonbaharda dökülür." },
  { w: "Avoid", p: "Verb", l: "A1", tr: "Kaçınmak / Sakınmak", ph: "/əˈvɔɪd/", d: "Keep away from something.", ex: "Avoid excessive sugar in your diet.", exTr: "Beslenmenizde aşırı şekerden kaçının." },
  { w: "Baby", p: "Noun", l: "A1", tr: "Bebek", ph: "/ˈbeɪ.bi/", d: "A very young child.", ex: "The newborn baby slept peacefully.", exTr: "Yeni doğan bebek huzurla uyudu." },
  { w: "Back", p: "Noun", l: "A1", tr: "Sırt / Arka", ph: "/bæk/", d: "The rear surface of the human body.", ex: "Sit straight to support your back.", exTr: "Sırtınızı desteklemek için dik oturun." },
  { w: "Bad", p: "Adj.", l: "A1", tr: "Kötü", ph: "/bæd/", d: "Of poor quality or undesirable.", ex: "Rainy weather is not necessarily bad.", exTr: "Yağmurlu hava mutlaka kötü demek değildir." },
  { w: "Bag", p: "Noun", l: "A1", tr: "Çanta", ph: "/bæɡ/", d: "A flexible container for carrying items.", ex: "Pack your essentials in this leather bag.", exTr: "Temel eşyalarınızı bu deri çantaya koyun." },
  { w: "Bakery", p: "Noun", l: "A1", tr: "Fırın / Pastane", ph: "/ˈbeɪ.kər.i/", d: "A place where bread and pastries are made.", ex: "Buy fresh sourdough bread at the bakery.", exTr: "Fırından taze ekşi mayalı ekmek alın." },
  { w: "Ball", p: "Noun", l: "A1", tr: "Top", ph: "/bɔːl/", d: "A spherical object used in games.", ex: "The children kicked the football.", exTr: "Çocuklar futbol topuna vurdu." },
  { w: "Banana", p: "Noun", l: "A1", tr: "Muz", ph: "/bəˈnɑː.nə/", d: "A long curved yellow fruit.", ex: "Bananas are rich in potassium.", exTr: "Muz potasyum açısından zengindir." },
  { w: "Bank", p: "Noun", l: "A1", tr: "Banka", ph: "/bæŋk/", d: "A financial establishment.", ex: "The local bank opens at nine.", exTr: "Yerel banka saat dokuzda açılıyor." },
  { w: "Bath", p: "Noun", l: "A1", tr: "Banyo", ph: "/bɑːθ/", d: "An act of washing one's body.", ex: "A warm bath relieves muscle tension.", exTr: "Ilık bir banyo kas gerginliğini hafifletir." },
  { w: "Beach", p: "Noun", l: "A1", tr: "Plaj / Sahil", ph: "/biːtʃ/", d: "A sandy shore by water.", ex: "We walked barefoot along the beach.", exTr: "Sahil boyunca çıplak ayakla yürüdük." },
  { w: "Beautiful", p: "Adj.", l: "A1", tr: "Güzel", ph: "/ˈbjuː.tɪ.fəl/", d: "Aesthetically pleasing.", ex: "What a beautiful sunny morning!", exTr: "Ne kadar güzel güneşli bir sabah!" },
  { w: "Because", p: "Adv.", l: "A1", tr: "Çünkü", ph: "/bɪˈkəz/", d: "For the reason that; since.", ex: "I study daily because I love learning.", exTr: "Her gün çalışıyorum çünkü öğrenmeyi seviyorum." },
  { w: "Become", p: "Verb", l: "A1", tr: "Olmak / Dönüşmek", ph: "/bɪˈkʌm/", d: "Begin to be; turn into.", ex: "He worked hard to become an architect.", exTr: "Mimar olmak için çok çalıştı." },
  { w: "Bed", p: "Noun", l: "A1", tr: "Yatak", ph: "/bed/", d: "A piece of furniture for sleeping.", ex: "Go to bed early for deep sleep.", exTr: "Derin uyku için erken yatın." },
  { w: "Begin", p: "Verb", l: "A1", tr: "Başlamak", ph: "/bɪˈɡɪn/", d: "Perform the first part of an action.", ex: "The lesson will begin now.", exTr: "Ders şimdi başlayacak." },
  { w: "Behind", p: "Adv.", l: "A1", tr: "Arkasında", ph: "/bɪˈhaɪnd/", d: "At or to the far side of.", ex: "The sun set behind the hills.", exTr: "Güneş tepelerin arkasında battı." },
  { w: "Believe", p: "Verb", l: "A1", tr: "İnanmak", ph: "/bɪˈliːv/", d: "Accept that something is true.", ex: "Always believe in your inner power.", exTr: "Her zaman içsel gücünüze inanın." },
  { w: "Below", p: "Adv.", l: "A1", tr: "Aşağıda / Altında", ph: "/bɪˈləʊ/", d: "At a lower level.", ex: "See the chart below for details.", exTr: "Ayrıntılar için aşağıdaki tabloya bakın." },
  { w: "Best", p: "Adj.", l: "A1", tr: "En iyi", ph: "/best/", d: "Of the highest quality or excellence.", ex: "Honesty is the best policy.", exTr: "Dürüstlük en iyi politikadır." },
  { w: "Better", p: "Adj.", l: "A1", tr: "Daha iyi", ph: "/ˈbet.ər/", d: "Of superior quality.", ex: "Practice makes your skills better.", exTr: "Pratik yapmak becerilerinizi daha iyi kılar." },
  { w: "Between", p: "Adv.", l: "A1", tr: "Arasında", ph: "/bɪˈtwiːn/", d: "In the middle of two points.", ex: "Choose between two great options.", exTr: "İki harika seçenek arasında seçim yapın." },
  { w: "Bicycle", p: "Noun", l: "A1", tr: "Bisiklet", ph: "/ˈbaɪ.sɪ.kəl/", d: "A two-wheeled vehicle.", ex: "He rides his bicycle to the office.", exTr: "Ofise bisikletiyle gidiyor." },
  { w: "Big", p: "Adj.", l: "A1", tr: "Büyük", ph: "/bɪɡ/", d: "Of considerable size or extent.", ex: "They have a big garden with roses.", exTr: "Gülleri olan büyük bir bahçeleri var." },
  { w: "Bird", p: "Noun", l: "A1", tr: "Kuş", ph: "/bɜːd/", d: "A feathered winged creature.", ex: "Early birds sing in the trees.", exTr: "Erkenci kuşlar ağaçlarda şarkı söyler." },
  { w: "Black", p: "Adj.", l: "A1", tr: "Siyah / Kara", ph: "/blæk/", d: "The darkest color.", ex: "She wore a classic black jacket.", exTr: "Klasik siyah bir ceket giydi." },
  { w: "Blue", p: "Adj.", l: "A1", tr: "Mavi", ph: "/bluː/", d: "The color of the clear sky.", ex: "The Mediterranean sea is deep blue.", exTr: "Akdeniz koyu mavidir." },
  { w: "Boat", p: "Noun", l: "A1", tr: "Tekne / Bot", ph: "/bəʊt/", d: "A small vessel for traveling on water.", ex: "We took a peaceful boat tour.", exTr: "Huzurlu bir tekne turuna çıktık." },
  { w: "Body", p: "Noun", l: "A1", tr: "Vücut / Beden", ph: "/ˈbɒd.i/", d: "The physical structure of a person.", ex: "Exercise strengthens the whole body.", exTr: "Egzersiz tüm vücudu güçlendirir." },
  { w: "Book", p: "Noun", l: "A1", tr: "Kitap / Ayırtmak", ph: "/bʊk/", d: "A written work or to reserve.", ex: "Reading a book enriches the soul.", exTr: "Kitap okumak ruhu zenginleştirir." },
  { w: "Boot", p: "Noun", l: "A1", tr: "Çizme / Bot", ph: "/buːt/", d: "Sturdy footwear covering the ankle.", ex: "Wear leather boots in snow.", exTr: "Karda deri çizmeler giyin." },
  { w: "Boring", p: "Adj.", l: "A1", tr: "Sıkıcı", ph: "/ˈbɔː.rɪŋ/", d: "Not interesting; tedious.", ex: "The long lecture was rather boring.", exTr: "Uzun ders oldukça sıkıcıydı." },
  { w: "Born", p: "Verb", l: "A1", tr: "Doğmuş", ph: "/bɔːn/", d: "Existing as a result of birth.", ex: "She was born in Izmir in May.", exTr: "Mayıs ayında İzmir'de doğdu." },
  { w: "Both", p: "Adv.", l: "A1", tr: "Her ikisi de", ph: "/bəʊθ/", d: "The two considered together.", ex: "Both options are very appealing.", exTr: "Her iki seçenek de çok çekici." },
  { w: "Bottle", p: "Noun", l: "A1", tr: "Şişe", ph: "/ˈbɒt.əl/", d: "A glass or plastic drink container.", ex: "Drink a full bottle of water.", exTr: "Dolu bir şişe su için." },
  { w: "Box", p: "Noun", l: "A1", tr: "Kutu", ph: "/bɒks/", d: "A container with flat sides.", ex: "Store keepsakes in this wooden box.", exTr: "Hatıraları bu ahşap kutuda saklayın." },
  { w: "Boy", p: "Noun", l: "A1", tr: "Erkek çocuk", ph: "/bɔɪ/", d: "A male child.", ex: "The boy rode his red scooter.", exTr: "Erkek çocuk kırmızı scooter'ını sürdü." },
  { w: "Bread", p: "Noun", l: "A1", tr: "Ekmek", ph: "/bred/", d: "Food made of flour and water.", ex: "Warm bread straight from the oven.", exTr: "Fırından yeni çıkmış sıcak ekmek." },
  { w: "Break", p: "Verb", l: "A1", tr: "Kırmak / Mola", ph: "/breɪk/", d: "Separate into pieces or take rest.", ex: "Take a short five-minute break.", exTr: "Beş dakikalık kısa bir mola verin." },
  { w: "Breakfast", p: "Noun", l: "A1", tr: "Kahvaltı", ph: "/ˈbrek.fəst/", d: "The first morning meal.", ex: "Have an energetic breakfast.", exTr: "Enerjik bir kahvaltı yapın." },
  { w: "Bridge", p: "Noun", l: "A1", tr: "Köprü", ph: "/brɪdʒ/", d: "Structure connecting two lands.", ex: "The bridge spans the wide canyon.", exTr: "Köprü geniş kanyonu birbirine bağlıyor." },
  { w: "Brother", p: "Noun", l: "A1", tr: "Erkek kardeş", ph: "/ˈbrʌð.ər/", d: "A male sibling.", ex: "My elder brother is an engineer.", exTr: "Ağabeyim bir mühendistir." },
  { w: "Brown", p: "Adj.", l: "A1", tr: "Kahverengi", ph: "/braʊn/", d: "Color of wood or soil.", ex: "He wore a stylish brown coat.", exTr: "Şık kahverengi bir palto giydi." },
  { w: "Build", p: "Verb", l: "A1", tr: "İnşa etmek", ph: "/bɪld/", d: "Construct by assembly.", ex: "Build habits that last a lifetime.", exTr: "Ömür boyu sürecek alışkanlıklar inşa edin." },
  { w: "Building", p: "Noun", l: "A1", tr: "Bina / Yapı", ph: "/ˈbɪl.dɪŋ/", d: "A structure with roof and walls.", ex: "That modern building has 30 floors.", exTr: "O modern binada 30 kat var." },
  { w: "Bus", p: "Noun", l: "A1", tr: "Otobüs", ph: "/bʌs/", d: "A large motor vehicle for passengers.", ex: "Catch the express bus downtown.", exTr: "Şehir merkezine giden ekspres otobüse binin." },
  { w: "Business", p: "Noun", l: "A1", tr: "İş / Ticaret", ph: "/ˈbɪz.nɪs/", d: "Commercial activity.", ex: "Starting a business requires courage.", exTr: "Bir iş kurmak cesaret gerektirir." },
  { w: "Butter", p: "Noun", l: "A1", tr: "Tereyağı", ph: "/ˈbʌt.ər/", d: "A pale yellow fatty food made from milk.", ex: "Spread fresh butter on warm toast.", exTr: "Sıcak kızarmış ekmeğe taze tereyağı sürün." },
  { w: "Buy", p: "Verb", l: "A1", tr: "Satın almak", ph: "/baɪ/", d: "Obtain in exchange for payment.", ex: "Buy fresh groceries from the market.", exTr: "Pazardan taze yiyecekler satın alın." },
  { w: "Cafe", p: "Noun", l: "A1", tr: "Kafe", ph: "/ˈkæf.eɪ/", d: "A small restaurant selling light drinks.", ex: "We had espresso at a street cafe.", exTr: "Bir sokak kafesinde espresso içtik." },
  { w: "Cake", p: "Noun", l: "A1", tr: "Kek / Pasta", ph: "/keɪk/", d: "A sweet baked dessert.", ex: "She baked a chocolate birthday cake.", exTr: "Çikolatalı bir doğum günü pastası pişirdi." },
  { w: "Call", p: "Verb", l: "A1", tr: "Aramak / Çağırmak", ph: "/kɔːl/", d: "Contact by phone or summon.", ex: "Call me when you land safely.", exTr: "Güvenle indiğinde beni ara." },
  { w: "Camera", p: "Noun", l: "A1", tr: "Fotoğraf makinesi", ph: "/ˈkæm.rə/", d: "Apparatus for taking photos.", ex: "He adjusted his camera lens.", exTr: "Kamera lensini ayarladı." },
  { w: "Car", p: "Noun", l: "A1", tr: "Araba / Otomobil", ph: "/kɑːr/", d: "A four-wheeled road vehicle.", ex: "Electric cars produce zero emissions.", exTr: "Elektrikli arabalar sıfır emisyon üretir." },
  { w: "Careful", p: "Adj.", l: "A1", tr: "Dikkatli", ph: "/ˈkeə.fəl/", d: "Prudent and attentive.", ex: "Be careful on the winding mountain road.", exTr: "Virajlı dağ yolunda dikkatli olun." },
  { w: "Cat", p: "Noun", l: "A1", tr: "Kedi", ph: "/kæt/", d: "A small domesticated carnivorous mammal.", ex: "The cat purred happily in the sun.", exTr: "Kedi güneşte mutlulukla mırıldandı." },
  { w: "Center", p: "Noun", l: "A1", tr: "Merkez", ph: "/ˈsen.tər/", d: "The middle point.", ex: "Meet at the city center square.", exTr: "Şehir merkezi meydanında buluşun." },
  { w: "Chair", p: "Noun", l: "A1", tr: "Sandalye", ph: "/tʃeər/", d: "A separate seat for one person.", ex: "Pull up a chair and join us.", exTr: "Bir sandalye çek ve bize katıl." },
  { w: "Change", p: "Verb", l: "A1", tr: "Değişmek / Değiştirmek", ph: "/tʃeɪndʒ/", d: "Make different.", ex: "You have the power to change your path.", exTr: "Yolunuzu değiştirme gücünüz var." },
  { w: "Cheap", p: "Adj.", l: "A1", tr: "Ucuz", ph: "/tʃiːp/", d: "Low in cost.", ex: "Trains offer cheap and scenic travel.", exTr: "Trenler ucuz ve manzaralı seyahat sunar." },
  { w: "Cheese", p: "Noun", l: "A1", tr: "Peynir", ph: "/tʃiːz/", d: "A dairy food made from curdled milk.", ex: "Ezine cheese is a famous Turkish delicacy.", exTr: "Ezine peyniri ünlü bir Türk lezzetidir." },
  { w: "Chicken", p: "Noun", l: "A1", tr: "Tavuk", ph: "/ˈtʃɪk.ɪn/", d: "A domestic fowl kept for eggs or meat.", ex: "Grilled chicken with herbs.", exTr: "Otlu ızgara tavuk." },
  { w: "Child", p: "Noun", l: "A1", tr: "Çocuk", ph: "/tʃaɪld/", d: "A young human being.", ex: "Every child deserves love and education.", exTr: "Her çocuk sevgiyi ve eğitimi hak eder." },
  { w: "Chocolate", p: "Noun", l: "A1", tr: "Çikolata", ph: "/ˈtʃɒk.lət/", d: "A sweet food made from roasted cacao.", ex: "Dark chocolate has antioxidant properties.", exTr: "Bitter çikolatanın antioksidan özellikleri vardır." },
  { w: "Choose", p: "Verb", l: "A1", tr: "Seçmek", ph: "/tʃuːz/", d: "Select from choices.", ex: "Choose your favorite playlist.", exTr: "En sevdiğiniz çalma listesini seçin." },
  { w: "Cinema", p: "Noun", l: "A1", tr: "Sinema", ph: "/ˈsɪn.ə.mɑː/", d: "A theater where films are shown.", ex: "We watched a movie at the cinema.", exTr: "Sinemada bir film izledik." },
  { w: "City", p: "Noun", l: "A1", tr: "Şehir / Kent", ph: "/ˈsɪt.i/", d: "A large populated urban area.", ex: "Tokyo is a bustling modern city.", exTr: "Tokyo hareketli modern bir şehirdir." },
  { w: "Class", p: "Noun", l: "A1", tr: "Sınıf / Ders", ph: "/klɑːs/", d: "A gathering of students for teaching.", ex: "Our English class starts at ten.", exTr: "İngilizce dersimiz saat onda başlıyor." },
  { w: "Clean", p: "Adj.", l: "A1", tr: "Temiz", ph: "/kliːn/", d: "Free from dirt.", ex: "Breathe in fresh clean mountain air.", exTr: "Taze temiz dağ havasını içinize çekin." },
  { w: "Clear", p: "Adj.", l: "A1", tr: "Berrak / Açık", ph: "/klɪər/", d: "Transparent; easy to see or comprehend.", ex: "The night sky was clear with bright stars.", exTr: "Gece gökyüzü parlak yıldızlarla berraktı." },
  { w: "Clock", p: "Noun", l: "A1", tr: "Saat", ph: "/klɒk/", d: "A timepiece.", ex: "The clock on the wall ticks quietly.", exTr: "Duvardaki saat sessizce tıkırdıyor." },
  { w: "Clothes", p: "Noun", l: "A1", tr: "Giysiler", ph: "/kləʊðz/", d: "Items worn on the body.", ex: "Pack lightweight summer clothes.", exTr: "Hafif yazlık giysiler hazırlayın." },
  { w: "Coffee", p: "Noun", l: "A1", tr: "Kahve", ph: "/ˈkɒf.i/", d: "Roasted bean drink.", ex: "Turkish coffee has a rich rich foam.", exTr: "Türk kahvesinin zengin bir köpüğü vardır." },
  { w: "Cold", p: "Adj.", l: "A1", tr: "Soğuk", ph: "/kəʊld/", d: "Of low temperature.", ex: "Winter brings crisp cold mornings.", exTr: "Kış çıtır soğuk sabahlar getirir." },
  { w: "Color", p: "Noun", l: "A1", tr: "Renk", ph: "/ˈkʌl.ər/", d: "Visual property of light reflected.", ex: "Her favorite color is emerald green.", exTr: "En sevdiği renk zümrüt yeşilidir." },
  { w: "Come", p: "Verb", l: "A1", tr: "Gelmek", ph: "/kʌm/", d: "Move toward a place.", ex: "Come and join our study group.", exTr: "Gel ve çalışma grubumuza katıl." },
  { w: "Cook", p: "Verb", l: "A1", tr: "Yemek pişirmek", ph: "/kʊk/", d: "Prepare food using heat.", ex: "She loves to cook fresh Mediterranean dishes.", exTr: "Taze Akdeniz yemekleri pişirmeyi çok sever." },
  { w: "Country", p: "Noun", l: "A1", tr: "Ülke / Kırsal", ph: "/ˈkʌn.tri/", d: "A nation with its own government.", ex: "Turkey is a transcontinental country.", exTr: "Türkiye kıtalararası bir ülkedir." },
  { w: "Cow", p: "Noun", l: "A1", tr: "İnek", ph: "/kaʊ/", d: "A fully grown female animal of domesticated cattle.", ex: "Cows grazed on the green pasture.", exTr: "İnekler yeşil merada otladı." },
  { w: "Cup", p: "Noun", l: "A1", tr: "Fincan / Kupa", ph: "/kʌp/", d: "A small bowl-shaped container for drinks.", ex: "A warm cup of herbal chamomile tea.", exTr: "Sıcak bir fincan papatya bitki çayı." },
  { w: "Dance", p: "Verb", l: "A1", tr: "Dans etmek", ph: "/dɑːns/", d: "Move rhythmically to music.", ex: "People danced joyfully at the wedding.", exTr: "İnsanlar düğünde neşeyle dans etti." },
  { w: "Dark", p: "Adj.", l: "A1", tr: "Karanlık / Koyu", ph: "/dɑːk/", d: "With little or no light.", ex: "The dark sky was illuminated by the moon.", exTr: "Karanlık gökyüzü ay tarafından aydınlatıldı." },
  { w: "Day", p: "Noun", l: "A1", tr: "Gün / Gündüz", ph: "/deɪ/", d: "A period of twenty-four hours.", ex: "Have a productive and joyful day!", exTr: "Verimli ve neşeli bir gün geçirin!" },
  { w: "December", p: "Noun", l: "A1", tr: "Aralık", ph: "/dɪˈsem.bər/", d: "The twelfth and final month of the year.", ex: "December brings snowy landscapes.", exTr: "Aralık ayı karlı manzaralar getirir." },
  { w: "Dentist", p: "Noun", l: "A1", tr: "Diş hekimi", ph: "/ˈden.tɪst/", d: "A person qualified to treat teeth.", ex: "Visit the dentist for a routine checkup.", exTr: "Rutin bir kontrol için diş hekimine gidin." },
  { w: "Desk", p: "Noun", l: "A1", tr: "Çalışma masası", ph: "/desk/", d: "A piece of furniture with a flat table-style work surface.", ex: "Organize your study desk neatly.", exTr: "Çalışma masanızı düzgünce düzenleyin." },
  { w: "Dinner", p: "Noun", l: "A1", tr: "Akşam yemeği", ph: "/ˈdɪn.ər/", d: "The main meal of the day, taken either around midday or in the evening.", ex: "We sat down for family dinner at seven.", exTr: "Saat yedide aile akşam yemeği için oturduk." },
  { w: "Doctor", p: "Noun", l: "A1", tr: "Doktor / Hekim", ph: "/ˈdɒk.tər/", d: "A qualified practitioner of medicine.", ex: "The doctor provided reassuring advice.", exTr: "Doktor güven verici tavsiyelerde bulundu." },
  { w: "Dog", p: "Noun", l: "A1", tr: "Köpek", ph: "/dɒɡ/", d: "A domesticated carnivorous mammal.", ex: "The loyal dog wagged its tail happily.", exTr: "Sadık köpek mutlulukla kuyruğunu salladı." },
  { w: "Door", p: "Noun", l: "A1", tr: "Kapı", ph: "/dɔːr/", d: "A hinged barrier used to close an entrance.", ex: "Please shut the front door quietly.", exTr: "Lütfen ön kapıyı sessizce kapatın." },
  { w: "Dress", p: "Noun", l: "A1", tr: "Elbise / Giyinmek", ph: "/dres/", d: "A one-piece garment for a woman.", ex: "She wore an elegant navy blue dress.", exTr: "Şık lacivert bir elbise giydi." },
  { w: "Drink", p: "Verb", l: "A1", tr: "İçmek", ph: "/drɪŋk/", d: "Take liquid into the mouth and swallow.", ex: "Drink plenty of mineral water daily.", exTr: "Günde bolca maden suyu için." },
  { w: "Drive", p: "Verb", l: "A1", tr: "Araba sürmek", ph: "/draɪv/", d: "Operate and control the direction and speed of a motor vehicle.", ex: "Drive cautiously in heavy rain.", exTr: "Şiddetli yağmurda dikkatli sürün." },
  { w: "Early", p: "Adv.", l: "A1", tr: "Erken", ph: "/ˈɜː.li/", d: "Happening or done before the usual or expected time.", ex: "Waking up early gives you clarity.", exTr: "Erken uyanmak size zihinsel berraklık verir." },
  { w: "Earth", p: "Noun", l: "A1", tr: "Dünya / Toprak", ph: "/ɜːθ/", d: "The planet on which we live; the world.", ex: "Protect our precious Earth for future generations.", exTr: "Gelecek nesiller için değerli Dünyamızı koruyun." },
  { w: "East", p: "Noun", l: "A1", tr: "Doğu", ph: "/iːst/", d: "The direction toward the point where the sun rises.", ex: "The morning sun rises in the east.", exTr: "Sabah güneşi doğudan doğar." },
  { w: "Easy", p: "Adj.", l: "A1", tr: "Kolay", ph: "/ˈiː.zi/", d: "Achieved without great effort.", ex: "English vocabulary becomes easy with daily games.", exTr: "Günlük oyunlarla İngilizce kelimeler kolaylaşır." },
  { w: "Eat", p: "Verb", l: "A1", tr: "Yemek", ph: "/iːt/", d: "Put food into the mouth, chew and swallow it.", ex: "Eat fresh wholesome organic meals.", exTr: "Taze sağlıklı organik yemekler yiyin." },
  { w: "Egg", p: "Noun", l: "A1", tr: "Yumurta", ph: "/eɡ/", d: "An oval body laid by female birds, containing rich nutrients.", ex: "Boiled eggs are full of protein.", exTr: "Haşlanmış yumurta protein doludur." },
  { w: "Eight", p: "Noun", l: "A1", tr: "Sekiz", ph: "/eɪt/", d: "Equivalent to the sum of seven and one.", ex: "The train departs at eight sharp.", exTr: "Tren tam sekizde kalkıyor." },
  { w: "Elephant", p: "Noun", l: "A1", tr: "Fil", ph: "/ˈel.ɪ.fənt/", d: "A very large herbivorous mammal with a trunk.", ex: "Elephants are known for their great memory.", exTr: "Filler muazzam hafızalarıyla bilinir." },
  { w: "End", p: "Noun", l: "A1", tr: "Son / Bitirmek", ph: "/end/", d: "A final part of something.", ex: "A joyful happy end to our journey.", exTr: "Yolculuğumuza neşeli mutlu bir son." },
  { w: "Enjoy", p: "Verb", l: "A1", tr: "Zevk almak / Tadını çıkarmak", ph: "/ɪnˈdʒɔɪ/", d: "Take delight or pleasure in.", ex: "Enjoy every single moment of learning.", exTr: "Öğrenmenin her bir anının tadını çıkarın." },
  { w: "Evening", p: "Noun", l: "A1", tr: "Akşam", ph: "/ˈiːv.nɪŋ/", d: "The period of time at the end of the day.", ex: "We walked by the harbor in the evening.", exTr: "Akşam liman kenarında yürüdük." },
  { w: "Exam", p: "Noun", l: "A1", tr: "Sınav", ph: "/ɪɡˈzæm/", d: "A formal test of knowledge or proficiency in a subject.", ex: "She prepared thoroughly for her final exam.", exTr: "Final sınavı için titizlikle hazırlandı." },
  { w: "Eye", p: "Noun", l: "A1", tr: "Göz", ph: "/aɪ/", d: "Each of a pair of globular organs in the head through which people see.", ex: "Look someone in the eye when speaking.", exTr: "Konuşurken birinin gözünün içine bakın." },
  { w: "Face", p: "Noun", l: "A1", tr: "Yüz / Karşılaşmak", ph: "/feɪs/", d: "The front part of a person's head.", ex: "A warm smile lit up her whole face.", exTr: "Sıcak bir gülümseme tüm yüzünü aydınlattı." },
  { w: "Family", p: "Noun", l: "A1", tr: "Aile", ph: "/ˈfæm.əl.i/", d: "A group of one or more parents and their children living together.", ex: "Spending quality time with family is priceless.", exTr: "Aileyle kaliteli zaman geçirmek paha biçilemez." },
  { w: "Famous", p: "Adj.", l: "A1", tr: "Ünlü / Meşhur", ph: "/ˈfeɪ.məs/", d: "Known about by many people.", ex: "Cappadocia is famous worldwide for hot air balloons.", exTr: "Kapadokya sıcak hava balonlarıyla dünya çapında ünlüdür." },
  { w: "Fast", p: "Adj.", l: "A1", tr: "Hızlı", ph: "/fɑːst/", d: "Moving or capable of moving at high speed.", ex: "High-speed trains provide fast comfortable travel.", exTr: "Hızlı trenler hızlı ve konforlu seyahat sağlar." },
  { w: "Father", p: "Noun", l: "A1", tr: "Baba", ph: "/ˈfɑː.ðər/", d: "A male parent.", ex: "Her father taught her how to play chess.", exTr: "Babası ona nasıl satranç oynanacağını öğretti." },
  { w: "February", p: "Noun", l: "A1", tr: "Şubat", ph: "/ˈfeb.ru.ər.i/", d: "The second month of the year.", ex: "February is the shortest month of the calendar year.", exTr: "Şubat takvim yılının en kısa ayıdır." },
  { w: "Fish", p: "Noun", l: "A1", tr: "Balık", ph: "/fɪʃ/", d: "A limbless cold-blooded vertebrate animal with gills.", ex: "Fresh grilled fish by the seaside.", exTr: "Deniz kenarında taze ızgara balık." },
  { w: "Flight", p: "Noun", l: "A1", tr: "Uçuş", ph: "/flaɪt/", d: "The action or process of flying through the air.", ex: "Our direct flight to London departed on time.", exTr: "Londra'ya direkt uçuşumuz zamanında kalktı." },
  { w: "Flower", p: "Noun", l: "A1", tr: "Çiçek", ph: "/flaʊər/", d: "The seed-bearing part of a plant.", ex: "Colorful spring flowers bloom everywhere.", exTr: "Renkli bahar çiçekleri her yerde açıyor." },
  { w: "Food", p: "Noun", l: "A1", tr: "Yiyecek / Yemek", ph: "/fuːd/", d: "Any nutritious substance that people eat.", ex: "Traditional Mediterranean food is very healthy.", exTr: "Geleneksel Akdeniz yemekleri çok sağlıklıdır." },
  { w: "Foot", p: "Noun", l: "A1", tr: "Ayak", ph: "/fʊt/", d: "The lower extremity of the leg below the ankle.", ex: "Explore the ancient city on foot.", exTr: "Antik şehri yürüyerek keşfedin." },
  { w: "Friend", p: "Noun", l: "A1", tr: "Arkadaş / Dost", ph: "/frend/", d: "A person with whom one has a bond of mutual affection.", ex: "A loyal friend is a true treasure in life.", exTr: "Sadık bir dost hayatta gerçek bir hazinedir." },
  { w: "Fruit", p: "Noun", l: "A1", tr: "Meyve", ph: "/fruːt/", d: "The sweet and fleshy product of a tree.", ex: "Eat plenty of seasonal fresh fruit.", exTr: "Bolca mevsimlik taze meyve yiyin." },
  { w: "Game", p: "Noun", l: "A1", tr: "Oyun", ph: "/ɡeɪm/", d: "A form of play or sport.", ex: "Word games make vocabulary learning fun.", exTr: "Kelime oyunları kelime öğrenmeyi eğlenceli kılar." },
  { w: "Garden", p: "Noun", l: "A1", tr: "Bahçe", ph: "/ˈɡɑː.dən/", d: "A piece of ground adjoining a house, used for growing flowers, fruit, or vegetables.", ex: "They grew sweet basil in the balcony garden.", exTr: "Balkon bahçesinde tatlı fesleğen yetiştirdiler." },
  { w: "Girl", p: "Noun", l: "A1", tr: "Kız çocuk", ph: "/ɡɜːl/", d: "A female child.", ex: "The young girl played the violin beautifully.", exTr: "Küçük kız kemanı çok güzel çaldı." },
  { w: "Give", p: "Verb", l: "A1", tr: "Vermek", ph: "/ɡɪv/", d: "Freely transfer the possession of something to someone.", ex: "Always give your best in every endeavor.", exTr: "Her girişimde her zaman elinizden gelenin en iyisini yapın." },
  { w: "Glass", p: "Noun", l: "A1", tr: "Bardak / Cam", ph: "/ɡlɑːs/", d: "A hard, brittle substance, or a drinking vessel.", ex: "Pour a glass of fresh orange juice.", exTr: "Bir bardak taze portakal suyu doldurun." },
  { w: "Go", p: "Verb", l: "A1", tr: "Gitmek", ph: "/ɡəʊ/", d: "Move from one place to another.", ex: "Let's go for a walk in the forest.", exTr: "Ormanda yürüyüşe çıkalım." },
  { w: "Good", p: "Adj.", l: "A1", tr: "İyi / Güzel", ph: "/ɡʊd/", d: "To be desired or approved of.", ex: "Reading every day builds good mental habits.", exTr: "Her gün okumak iyi zihinsel alışkanlıklar oluşturur." },
  { w: "Green", p: "Adj.", l: "A1", tr: "Yeşil", ph: "/ɡriːn/", d: "The color between blue and yellow in the spectrum.", ex: "The valley was lush and green in spring.", exTr: "Vadi ilkbaharda gür ve yeşildi." },
  { w: "Group", p: "Noun", l: "A1", tr: "Grup / Topluluk", ph: "/ɡruːp/", d: "A number of people or things that are located close together.", ex: "A group of friends traveled together.", exTr: "Bir grup arkadaş birlikte seyahat etti." },
  { w: "Grow", p: "Verb", l: "A1", tr: "Büyümek / Yetişmek", ph: "/ɡrəʊ/", d: "Undergo natural development by increasing in size and changing physically.", ex: "Olive trees grow gracefully in the Aegean.", exTr: "Zeytin ağaçları Ege'de zarafetle yetişir." },
  { w: "Happy", p: "Adj.", l: "A1", tr: "Mutlu / Neşeli", ph: "/ˈhæp.i/", d: "Feeling or showing pleasure or contentment.", ex: "Live a peaceful and happy lifestyle.", exTr: "Huzurlu ve mutlu bir yaşam tarzı sürün." },
  { w: "Hat", p: "Noun", l: "A1", tr: "Şapka", ph: "/hæt/", d: "A shaped covering for the head.", ex: "Wear a straw hat for sun protection.", exTr: "Güneşten korunmak için hasır şapka takın." },
  { w: "Have", p: "Verb", l: "A1", tr: "Sahip olmak", ph: "/hæv/", d: "Possess, own, or hold.", ex: "Have courage and pursue your passions.", exTr: "Cesur olun ve tutkularınızın peşinden gidin." },
  { w: "Head", p: "Noun", l: "A1", tr: "Baş / Kafa", ph: "/hed/", d: "The upper part of the human body containing the brain.", ex: "Keep a clear head during stressful moments.", exTr: "Stresli anlarda kafanızı net tutun." },
  { w: "Hear", p: "Verb", l: "A1", tr: "Duymak / İşitmek", ph: "/hɪər/", d: "Perceive with the ear the sound made by someone or something.", ex: "Listen carefully to hear the morning birds.", exTr: "Sabah kuşlarını duymak için dikkatle dinleyin." },
  { w: "Heart", p: "Noun", l: "A1", tr: "Kalp / Yürek", ph: "/hɑːt/", d: "The organ that pumps blood, or the locus of feelings.", ex: "Follow what your heart truly desires.", exTr: "Kalbinizin gerçekten arzuladığı şeyin peşinden gidin." },
  { w: "Help", p: "Verb", l: "A1", tr: "Yardım etmek", ph: "/help/", d: "Make it easier for someone to do something.", ex: "Helping others brings immense inner peace.", exTr: "Başkalarına yardım etmek muazzam bir iç huzur getirir." },
  { w: "Home", p: "Noun", l: "A1", tr: "Ev / Yuva", ph: "/həʊm/", d: "The place where one lives permanently.", ex: "There is no place like home.", exTr: "Ev gibisi yoktur." },
  { w: "Hope", p: "Noun", l: "A1", tr: "Umut / Ümit etmek", ph: "/həʊp/", d: "A feeling of expectation and desire for a certain thing to happen.", ex: "Never lose hope in difficult circumstances.", exTr: "Zor koşullarda asla umudunuzu kaybetmeyin." },
  { w: "Horse", p: "Noun", l: "A1", tr: "At", ph: "/hɔːs/", d: "A large domesticated four-legged mammal with hooves.", ex: "They rode horses along the valley trails.", exTr: "Vadi patikaları boyunca at sürdüler." },
  { w: "Hospital", p: "Noun", l: "A1", tr: "Hastane", ph: "/ˈhɒs.pɪ.təl/", d: "An institution providing medical treatment and nursing care.", ex: "The city hospital has modern facilities.", exTr: "Şehir hastanesinin modern imkanları var." },
  { w: "Hot", p: "Adj.", l: "A1", tr: "Sıcak", ph: "/hɒt/", d: "Having a high degree of heat or a high temperature.", ex: "A hot cup of tea on a chilly evening.", exTr: "Serin bir akşamda sıcak bir fincan çay." },
  { w: "Hotel", p: "Noun", l: "A1", tr: "Otel", ph: "/həʊˈtel/", d: "An establishment providing accommodation.", ex: "We stayed at a boutique hotel in old town.", exTr: "Eski şehirde bir butik otelde kaldık." },
  { w: "Hour", p: "Noun", l: "A1", tr: "Saat (Süre)", ph: "/aʊər/", d: "A period of time equal to sixty minutes.", ex: "Spend one hour reading every single day.", exTr: "Her gün bir saatinizi kitap okumaya ayırın." },
  { w: "House", p: "Noun", l: "A1", tr: "Ev / Konut", ph: "/haʊs/", d: "A building for human habitation.", ex: "They bought a charming stone house.", exTr: "Büyüleyici bir taş ev satın aldılar." },
  { w: "How", p: "Adv.", l: "A1", tr: "Nasıl", ph: "/haʊ/", d: "In what way or manner.", ex: "How can I improve my English fluency?", exTr: "İngilizce akıcılığımı nasıl geliştirebilirim?" },
  { w: "Husband", p: "Noun", l: "A1", tr: "Koca / Eş", ph: "/ˈhʌz.bənd/", d: "A married man, considered in relation to his spouse.", ex: "She and her husband traveled to Paris.", exTr: "O ve eşi Paris'e seyahat etti." },
  { w: "Idea", p: "Noun", l: "A1", tr: "Fikir / Düşünce", ph: "/aɪˈdɪə/", d: "A thought or suggestion as to a possible course of action.", ex: "That is a brilliant and creative idea!", exTr: "Bu harika ve yaratıcı bir fikir!" },
  { w: "Important", p: "Adj.", l: "A1", tr: "Önemli", ph: "/ɪmˈpɔː.tənt/", d: "Of great significance or value.", ex: "Good health is the most important asset.", exTr: "Sağlık en önemli varlıktır." },
  { w: "Interesting", p: "Adj.", l: "A1", tr: "İlginç", ph: "/ˈɪn.trəs.tɪŋ/", d: "Arousing curiosity or interest.", ex: "The documentary was deeply interesting.", exTr: "Belgesel son derece ilginçti." },
  { w: "Island", p: "Noun", l: "A1", tr: "Ada", ph: "/ˈaɪ.lənd/", d: "A piece of land surrounded by water.", ex: "Bozcaada is a peaceful island in the north Aegean.", exTr: "Bozcaada Kuzey Ege'de huzurlu bir adadır." },
  { w: "Job", p: "Noun", l: "A1", tr: "İş / Meslek", ph: "/dʒɒb/", d: "A paid position of regular employment.", ex: "He found a rewarding remote software job.", exTr: "Tatmin edici bir uzaktan yazılım işi buldu." },
  { w: "Kitchen", p: "Noun", l: "A1", tr: "Mutfak", ph: "/ˈkɪtʃ.ən/", d: "A room or area where food is prepared and cooked.", ex: "The warm kitchen smelled of freshly baked bread.", exTr: "Sıcak mutfak taze pişmiş ekmek kokuyordu." },
  { w: "Language", p: "Noun", l: "A1", tr: "Dil / Lisan", ph: "/ˈlæŋ.ɡwɪdʒ/", d: "The principal method of human communication.", ex: "Learning a new language opens new worlds.", exTr: "Yeni bir dil öğrenmek yeni dünyaların kapılarını açar." },
  { w: "Learn", p: "Verb", l: "A1", tr: "Öğrenmek", ph: "/lɜːn/", d: "Gain or acquire knowledge of or skill in something.", ex: "Never stop learning and exploring.", exTr: "Öğrenmeyi ve keşfetmeyi asla bırakmayın." },
  { w: "Letter", p: "Noun", l: "A1", tr: "Mektup / Harf", ph: "/ˈlet.ər/", d: "A written communication, or a symbol of the alphabet.", ex: "She wrote a heartfelt handwritten letter.", exTr: "İçten, el yazısıyla bir mektup yazdı." },
  { w: "Life", p: "Noun", l: "A1", tr: "Hayat / Yaşam", ph: "/laɪf/", d: "The condition that distinguishes animals and plants from inorganic matter.", ex: "Live a purposeful and meaningful life.", exTr: "Amacı olan ve anlamlı bir hayat yaşayın." },
  { w: "Light", p: "Noun", l: "A1", tr: "Işık / Hafif", ph: "/laɪt/", d: "The natural agent that stimulates sight.", ex: "Morning sunlight filled the bright studio.", exTr: "Sabah güneş ışığı aydınlık stüdyoyu doldurdu." },
  { w: "Listen", p: "Verb", l: "A1", tr: "Dinlemek", ph: "/ˈlɪs.ən/", d: "Give one's attention to a sound.", ex: "Listen with empathy and understanding.", exTr: "Empati ve anlayışla dinleyin." },
  { w: "Live", p: "Verb", l: "A1", tr: "Yaşamak", ph: "/lɪv/", d: "Remain alive; make one's home in a particular place.", ex: "They live near a serene pine forest.", exTr: "Sakin bir çam ormanının yakınında yaşıyorlar." },
  { w: "Look", p: "Verb", l: "A1", tr: "Bakmak / Görünmek", ph: "/lʊk/", d: "Direct one's gaze toward someone or something.", ex: "Look at the stars on a clear night.", exTr: "Açık bir gecede yıldızlara bakın." },
  { w: "Love", p: "Verb", l: "A1", tr: "Sevmek / Aşk", ph: "/lʌv/", d: "Feel deep affection for someone or something.", ex: "Love what you do and do what you love.", exTr: "Yaptığınız işi sevin ve sevdiğiniz işi yapın." },
  { w: "Make", p: "Verb", l: "A1", tr: "Yapmak / Üretmek", ph: "/meɪk/", d: "Form something by putting parts together or combining substances.", ex: "Make every single day count.", exTr: "Her bir günün değerini bilin." },
  { w: "Man", p: "Noun", l: "A1", tr: "Adam / Erkek", ph: "/mæn/", d: "An adult human male.", ex: "A wise man listens more than he speaks.", exTr: "Bilge bir adam konuştuğundan daha çok dinler." },
  { w: "Many", p: "Adv.", l: "A1", tr: "Çok / Birçok", ph: "/ˈmen.i/", d: "A large number of.", ex: "There are many reasons to stay optimistic.", exTr: "İyimser kalmak için birçok neden var." },
  { w: "Market", p: "Noun", l: "A1", tr: "Pazar / Piyasa", ph: "/ˈmɑː.kɪt/", d: "A regular gathering of people for purchase and sale.", ex: "Buy fresh organic herbs at the weekly market.", exTr: "Haftalık pazardan taze organik otlar alın." },
  { w: "Meal", p: "Noun", l: "A1", tr: "Öğün / Yemek", ph: "/miːl/", d: "Any of the regular occasions in day when a reasonably large amount of food is eaten.", ex: "Enjoy a wholesome homemade meal.", exTr: "Sağlıklı ev yapımı bir öğünün tadını çıkarın." },
  { w: "Meet", p: "Verb", l: "A1", tr: "Buluşmak / Tanışmak", ph: "/miːt/", d: "Come into the presence of someone.", ex: "Let's meet at the seaside cafe at noon.", exTr: "Öğleyin deniz kenarındaki kafede buluşalım." },
  { w: "Money", p: "Noun", l: "A1", tr: "Para", ph: "/ˈmʌn.i/", d: "A current medium of exchange in the form of coins and banknotes.", ex: "Invest money wisely in education and skills.", exTr: "Parayı eğitime ve becerilere akıllıca yatırın." },
  { w: "Month", p: "Noun", l: "A1", tr: "Ay", ph: "/mʌnθ/", d: "Each of the twelve named periods into which a year is divided.", ex: "Spring arrives next month.", exTr: "Bahar gelecek ay geliyor." },
  { w: "Morning", p: "Noun", l: "A1", tr: "Sabah", ph: "/ˈmɔː.nɪŋ/", d: "The period of time between midnight and noon.", ex: "A crisp fresh morning breeze.", exTr: "Taze serin bir sabah esintisi." },
  { w: "Mother", p: "Noun", l: "A1", tr: "Anne", ph: "/ˈmʌð.ər/", d: "A female parent.", ex: "Her mother gave her unconditional support.", exTr: "Annesi ona koşulsuz destek verdi." },
  { w: "Mountain", p: "Noun", l: "A1", tr: "Dağ", ph: "/ˈmaʊn.tɪn/", d: "A large natural elevation of the earth's surface.", ex: "The snow-capped mountain stood tall against the blue sky.", exTr: "Karlı dağ mavi gökyüzüne karşı dimdik duruyordu." },
  { w: "Music", p: "Noun", l: "A1", tr: "Müzik", ph: "/ˈmjuː.zɪk/", d: "Vocal or instrumental sounds combined in harmony.", ex: "Acoustic music calms the busy mind.", exTr: "Akustik müzik meşgul zihni sakinleştirir." },
  { w: "Name", p: "Noun", l: "A1", tr: "İsim / Ad", ph: "/neɪm/", d: "A word or set of words by which a person or thing is known.", ex: "What is the name of that ancient castle?", exTr: "O antik kalenin adı nedir?" },
  { w: "New", p: "Adj.", l: "A1", tr: "Yeni", ph: "/njuː/", d: "Not existing before; made, introduced, or discovered recently.", ex: "Every day is a new beginning.", exTr: "Her gün yeni bir başlangıçtır." },
  { w: "Night", p: "Noun", l: "A1", tr: "Gece", ph: "/naɪt/", d: "The period from sunset to sunrise.", ex: "The stars shone brightly in the clear night.", exTr: "Yıldızlar berrak gecede parlak bir şekilde parladı." },
  { w: "Number", p: "Noun", l: "A1", tr: "Numara / Sayı", ph: "/ˈnʌm.bər/", d: "An arithmetical value expressed by a word or symbol.", ex: "Leave your contact phone number.", exTr: "İletişim telefon numaranızı bırakın." },
  { w: "Open", p: "Verb", l: "A1", tr: "Açmak / Açık", ph: "/ˈəʊ.pən/", d: "Allowing access, passage, or a view; not closed.", ex: "Open your mind to new perspectives.", exTr: "Zihninizi yeni bakış açılarına açın." },
  { w: "Paper", p: "Noun", l: "A1", tr: "Kağıt / Gazete", ph: "/ˈpeɪ.pər/", d: "Material manufactured in thin sheets from the pulp of wood.", ex: "Write down your goals on paper.", exTr: "Hedeflerinizi kağıda yazın." },
  { w: "Parent", p: "Noun", l: "A1", tr: "Ebeveyn (Anne/Baba)", ph: "/ˈpeə.rənt/", d: "A father or mother.", ex: "Parents guide their children with wisdom.", exTr: "Ebeveynler çocuklarına bilgelikle rehberlik eder." },
  { w: "Park", p: "Noun", l: "A1", tr: "Park / Bahçe", ph: "/pɑːk/", d: "A large public green area in a town.", ex: "We strolled in the serene green park.", exTr: "Huzurlu yeşil parkta gezindik." },
  { w: "Party", p: "Noun", l: "A1", tr: "Parti / Eğlence", ph: "/ˈpɑː.ti/", d: "A social gathering of invited guests.", ex: "We celebrated his promotion at the party.", exTr: "Onun terfisini partide kutladık." },
  { w: "Pen", p: "Noun", l: "A1", tr: "Tükenmez kalem", ph: "/pen/", d: "An instrument for writing or drawing with ink.", ex: "Sign the agreement with this black pen.", exTr: "Sözleşmeyi bu siyah kalemle imzalayın." },
  { w: "People", p: "Noun", l: "A1", tr: "İnsanlar / Halk", ph: "/ˈpiː.pəl/", d: "Human beings in general or considered collectively.", ex: "Kind people make the world a better place.", exTr: "Nazik insanlar dünyayı daha iyi bir yer yapar." },
  { w: "Phone", p: "Noun", l: "A1", tr: "Telefon", ph: "/fəʊn/", d: "A system for transmitting voices over a distance.", ex: "Answer the phone with a friendly greeting.", exTr: "Telefona samimi bir selamlamayla cevap verin." },
  { w: "Picture", p: "Noun", l: "A1", tr: "Resim / Fotoğraf", ph: "/ˈpɪk.tʃər/", d: "A painting or drawing.", ex: "A picture is worth a thousand words.", exTr: "Bir resim bin kelimeye bedeldir." },
  { w: "Place", p: "Noun", l: "A1", tr: "Yer / Mekan", ph: "/pleɪs/", d: "A particular position or point in space.", ex: "Find a quiet place to read and reflect.", exTr: "Okumak ve düşünmek için sessiz bir yer bulun." },
  { w: "Play", p: "Verb", l: "A1", tr: "Oynamak / Çalmak (Müzik)", ph: "/pleɪ/", d: "Engage in activity for enjoyment and recreation.", ex: "He loves to play acoustic guitar.", exTr: "Akustik gitar çalmayı çok sever." },
  { w: "Question", p: "Noun", l: "A1", tr: "Soru", ph: "/ˈkwes.tʃən/", d: "A sentence worded or expressed so as to elicit information.", ex: "Never hesitate to ask a question.", exTr: "Soru sormaktan asla çekinmeyin." },
  { w: "Quick", p: "Adj.", l: "A1", tr: "Hızlı / Çabuk", ph: "/kwɪk/", d: "Moving fast or doing something in a short time.", ex: "Take a quick five-minute walk.", exTr: "Hızlı bir beş dakikalık yürüyüş yapın." },
  { w: "Rain", p: "Noun", l: "A1", tr: "Yağmur", ph: "/reɪn/", d: "Moisture condensed from the atmosphere that falls in drops in the sky.", ex: "Gentle spring rain nourished the flowers.", exTr: "Hafif bahar yağmuru çiçekleri besledi." },
  { w: "Read", p: "Verb", l: "A1", tr: "Okumak", ph: "/riːd/", d: "Look at and comprehend the meaning of written words.", ex: "Read ten pages before sleeping.", exTr: "Uyumadan önce on sayfa okuyun." },
  { w: "Red", p: "Adj.", l: "A1", tr: "Kırmızı / Al", ph: "/red/", d: "Color of blood or ruby.", ex: "She wore a vibrant red scarf.", exTr: "Canlı kırmızı bir atkı taktı." },
  { w: "Rest", p: "Verb", l: "A1", tr: "Dinlenmek / Mola", ph: "/rest/", d: "Cease work or movement in order to relax.", ex: "Rest your eyes after long screen time.", exTr: "Uzun ekran süresinden sonra gözlerinizi dinlendirin." },
  { w: "Rice", p: "Noun", l: "A1", tr: "Pirinç / Pilav", ph: "/raɪs/", d: "A swamp grass cultivated widely for food.", ex: "Steamed jasmine rice with herbs.", exTr: "Otlu buharda yasemin pirinci." },
  { w: "Right", p: "Adj.", l: "A1", tr: "Doğru / Sağ", ph: "/raɪt/", d: "Morally good, justified, or acceptable; or opposite of left.", ex: "Do what is right, not what is easy.", exTr: "Kolay olanı değil, doğru olanı yapın." },
  { w: "River", p: "Noun", l: "A1", tr: "Nehir / Irmak", ph: "/ˈrɪv.ər/", d: "A large natural stream of water.", ex: "The river flowed gently toward the sea.", exTr: "Nehir denize doğru nazikçe aktı." },
  { w: "Road", p: "Noun", l: "A1", tr: "Yol / Cadde", ph: "/rəʊd/", d: "A wide way leading from one place to another.", ex: "The coastal road offers breathtaking sea views.", exTr: "Sahil yolu nefes kesici deniz manzaraları sunar." },
  { w: "Room", p: "Noun", l: "A1", tr: "Oda / Alan", ph: "/ruːm/", d: "Space that can be occupied.", ex: "A sunny room with wide windows.", exTr: "Geniş pencereleri olan güneşli bir oda." },
  { w: "Run", p: "Verb", l: "A1", tr: "Koşmak / Çalıştırmak", ph: "/rʌn/", d: "Move at a speed faster than a walk.", ex: "Run in the park every morning.", exTr: "Her sabah parkta koşun." },
  { w: "School", p: "Noun", l: "A1", tr: "Okul", ph: "/skuːl/", d: "An institution for educating children.", ex: "School provides the foundation for growth.", exTr: "Okul gelişim için temeli sağlar." },
  { w: "Sea", p: "Noun", l: "A1", tr: "Deniz", ph: "/siː/", d: "The expanse of salt water that covers most of the earth's surface.", ex: "The turquoise sea sparkled in the sunlight.", exTr: "Turkuaz deniz güneş ışığında parıldadı." },
  { w: "See", p: "Verb", l: "A1", tr: "Görmek / Anlamak", ph: "/siː/", d: "Perceive with the eyes.", ex: "Open your eyes and see the beauty around.", exTr: "Gözlerinizi açın ve çevrenizdeki güzelliği görün." },
  { w: "Short", p: "Adj.", l: "A1", tr: "Kısa", ph: "/ʃɔːt/", d: "Measuring a small distance from end to end.", ex: "A short walk boosts your energy.", exTr: "Kısa bir yürüyüş enerjinizi artırır." },
  { w: "Sister", p: "Noun", l: "A1", tr: "Kız kardeş", ph: "/ˈsɪs.tər/", d: "A female sibling.", ex: "My sister is studying architecture.", exTr: "Kız kardeşim mimarlık okuyor." },
  { w: "Sleep", p: "Verb", l: "A1", tr: "Uyumak", ph: "/sliːp/", d: "A condition of body and mind that recurs for several hours every night.", ex: "Sleep at least seven hours every night.", exTr: "Her gece en az yedi saat uyuyun." },
  { w: "Small", p: "Adj.", l: "A1", tr: "Küçük", ph: "/smɔːl/", d: "Of a size that is less than normal or usual.", ex: "Small daily steps lead to big achievements.", exTr: "Küçük günlük adımlar büyük başarılara ulaştırır." },
  { w: "Smile", p: "Noun", l: "A1", tr: "Gülümseme / Gülümsemek", ph: "/smaɪl/", d: "A pleased facial expression.", ex: "A genuine smile brightens anyone's day.", exTr: "İçten bir gülümseme herkesin gününü aydınlatır." },
  { w: "Song", p: "Noun", l: "A1", tr: "Şarkı", ph: "/sɒŋ/", d: "A short poem or other set of words set to music.", ex: "He sang an emotional folk song.", exTr: "Duygusal bir türkü söyledi." },
  { w: "Speak", p: "Verb", l: "A1", tr: "Konuşmak", ph: "/spiːk/", d: "Say something in order to convey information.", ex: "Speak English with confidence every day.", exTr: "Her gün özgüvenle İngilizce konuşun." },
  { w: "Spring", p: "Noun", l: "A1", tr: "İlkbahar / Bahar", ph: "/sprɪŋ/", d: "The season after winter.", ex: "Spring brings fresh green life everywhere.", exTr: "İlkbahar her yere taze yeşil hayat getirir." },
  { w: "Star", p: "Noun", l: "A1", tr: "Yıldız", ph: "/stɑːr/", d: "A luminous celestial point in the night sky.", ex: "Look at the shooting star in the clear sky.", exTr: "Açık gökyüzündeki kayan yıldıza bakın." },
  { w: "Start", p: "Verb", l: "A1", tr: "Başlamak", ph: "/stɑːt/", d: "Begin an activity.", ex: "Start your morning with gratitude.", exTr: "Sabahınıza şükranla başlayın." },
  { w: "Street", p: "Noun", l: "A1", tr: "Sokak / Cadde", ph: "/striːt/", d: "A public road in a city or town.", ex: "The historic street was paved with cobblestones.", exTr: "Tarihi sokak arnavut kaldırımıyla döşenmişti." },
  { w: "Student", p: "Noun", l: "A1", tr: "Öğrenci", ph: "/ˈstjuː.dənt/", d: "A person who is studying at school or university.", ex: "An enthusiastic student learns fast.", exTr: "Hevesli bir öğrenci hızlı öğrenir." },
  { w: "Summer", p: "Noun", l: "A1", tr: "Yaz", ph: "/ˈsʌm.ər/", d: "The warmest season of the year.", ex: "Summer brings long sunny seaside days.", exTr: "Yaz uzun güneşli deniz kenarı günleri getirir." },
  { w: "Sun", p: "Noun", l: "A1", tr: "Güneş", ph: "/sʌn/", d: "The star around which the earth orbits.", ex: "The golden sun warms the morning earth.", exTr: "Altın güneş sabah toprağını ısıtır." },
  { w: "Table", p: "Noun", l: "A1", tr: "Masa", ph: "/ˈteɪ.bəl/", d: "A piece of furniture with a flat top and one or more legs.", ex: "We gathered around the dining table.", exTr: "Yemek masasının etrafında toplandık." },
  { w: "Talk", p: "Verb", l: "A1", tr: "Konuşmak / Sohbet etmek", ph: "/tɔːk/", d: "Speak in order to give information or express ideas.", ex: "Let's talk over a warm cup of coffee.", exTr: "Sıcak bir fincan kahve eşliğinde konuşalım." },
  { w: "Teacher", p: "Noun", l: "A1", tr: "Öğretmen", ph: "/ˈtiː.tʃər/", d: "A person who teaches, especially in a school.", ex: "An inspiring teacher changes lives.", exTr: "İlham veren bir öğretmen hayatları değiştirir." },
  { w: "Tea", p: "Noun", l: "A1", tr: "Çay", ph: "/tiː/", d: "A hot drink made by infusing dried leaves.", ex: "Turkish black tea in a tulip glass.", exTr: "İnce belli bardakta Türk siyah çayı." },
  { w: "Thank", p: "Verb", l: "A1", tr: "Teşekkür etmek", ph: "/θæŋk/", d: "Express gratitude to someone.", ex: "Always thank people for their kindness.", exTr: "İnsanlara nezaketleri için her zaman teşekkür edin." },
  { w: "Time", p: "Noun", l: "A1", tr: "Zaman / Vakit", ph: "/taɪm/", d: "The indefinite continued progress of existence.", ex: "Make time for the things you love.", exTr: "Sevdiğiniz şeyler için zaman ayırın." },
  { w: "Today", p: "Adv.", l: "A1", tr: "Bugün", ph: "/təˈdeɪ/", d: "On or in the course of this present day.", ex: "Make today count with great enthusiasm.", exTr: "Bugünü büyük bir coşkuyla değerlendirin." },
  { w: "Tomorrow", p: "Adv.", l: "A1", tr: "Yarın", ph: "/təˈmɒr.əʊ/", d: "On the day after today.", ex: "Tomorrow brings a fresh new opportunity.", exTr: "Yarın taze yeni bir fırsat getirir." },
  { w: "Town", p: "Noun", l: "A1", tr: "Kasaba / İlçe", ph: "/taʊn/", d: "An urban area that has a name and defined boundaries.", ex: "A charming coastal town in southern Turkey.", exTr: "Güney Türkiye'de şirin bir sahil kasabası." },
  { w: "Train", p: "Noun", l: "A1", tr: "Tren / Eğitmek", ph: "/treɪn/", d: "A series of connected railway carriages.", ex: "The scenic train ride was unforgettable.", exTr: "Manzaralı tren yolculuğu unutulmazdı." },
  { w: "Travel", p: "Verb", l: "A1", tr: "Seyahat etmek", ph: "/ˈtræv.əl/", d: "Make a journey, typically of some length.", ex: "Travel broadens understanding and empathy.", exTr: "Seyahat etmek anlayışı ve empatiyi genişletir." },
  { w: "Tree", p: "Noun", l: "A1", tr: "Ağaç", ph: "/triː/", d: "A woody perennial plant with a trunk.", ex: "Ancient olive trees live for centuries.", exTr: "Kadim zeytin ağaçları asırlarca yaşar." },
  { w: "Under", p: "Adv.", l: "A1", tr: "Altında", ph: "/ˈʌn.dər/", d: "Extending or directly below.", ex: "Rest under the shade of the tall oak tree.", exTr: "Yüksek meşe ağacının gölgesinde dinlenin." },
  { w: "Understand", p: "Verb", l: "A1", tr: "Anlamak / Kavramak", ph: "/ˌʌn.dəˈstænd/", d: "Perceive the intended meaning of words or ideas.", ex: "I understand the concept clearly now.", exTr: "Kavramı şimdi net bir şekilde anlıyorum." },
  { w: "Village", p: "Noun", l: "A1", tr: "Köy", ph: "/ˈvɪl.ɪdʒ/", d: "A group of houses situated in a rural area.", ex: "A tranquil mountain village surrounded by pine trees.", exTr: "Çam ağaçlarıyla çevrili sakin bir dağ köyü." },
  { w: "Wait", p: "Verb", l: "A1", tr: "Beklemek", ph: "/weɪt/", d: "Stay where one is or delay action until a particular time.", ex: "Good things come to those who patiently wait.", exTr: "İyi şeyler sabırla bekleyenlerin başına gelir." },
  { w: "Walk", p: "Verb", l: "A1", tr: "Yürümek", ph: "/wɔːk/", d: "Move at a regular pace by lifting and setting down each foot in turn.", ex: "Walk thirty minutes every day for heart health.", exTr: "Kalp sağlığı için her gün otuz dakika yürüyün." },
  { w: "Water", p: "Noun", l: "A1", tr: "Su", ph: "/ˈwɔː.tər/", d: "A colorless transparent liquid forming the seas, lakes, and rivers.", ex: "Pure water is essential for vibrant life.", exTr: "Saf su canlı yaşam için vazgeçilmezdir." },
  { w: "Week", p: "Noun", l: "A1", tr: "Hafta", ph: "/wiːk/", d: "A period of seven consecutive days.", ex: "Have a productive and inspiring week ahead!", exTr: "Önünüzde verimli ve ilham verici bir hafta olsun!" },
  { w: "White", p: "Adj.", l: "A1", tr: "Beyaz / Ak", ph: "/waɪt/", d: "Color of snow or milk.", ex: "Snow-white cherry blossoms in early spring.", exTr: "Erken ilkbaharda kar beyazı kiraz çiçekleri." },
  { w: "Window", p: "Noun", l: "A1", tr: "Pencere", ph: "/ˈwɪn.dəʊ/", d: "An opening in a wall to admit light or air.", ex: "Open the window to let in the fresh breeze.", exTr: "Taze esintinin içeri girmesi için pencereyi açın." },
  { w: "Winter", p: "Noun", l: "A1", tr: "Kış", ph: "/ˈwɪn.tər/", d: "The coldest season of the year.", ex: "Winter brings cozy evenings by the fire.", exTr: "Kış ateş başında keyifli akşamlar getirir." },
  { w: "Woman", p: "Noun", l: "A1", tr: "Kadın", ph: "/ˈwʊm.ən/", d: "An adult human female.", ex: "She is an inspiring and accomplished woman.", exTr: "O ilham veren ve başarılı bir kadındır." },
  { w: "Word", p: "Noun", l: "A1", tr: "Kelime / Sözcük", ph: "/wɜːd/", d: "A single distinct meaningful element of speech or writing.", ex: "Words have the power to heal and inspire.", exTr: "Kelimelerin iyileştirme ve ilham verme gücü vardır." },
  { w: "Work", p: "Verb", l: "A1", tr: "Çalışmak / İş", ph: "/wɜːk/", d: "Activity involving mental or physical effort.", ex: "Work with passion and integrity.", exTr: "Tutkuyla ve dürüstlükle çalışın." },
  { w: "World", p: "Noun", l: "A1", tr: "Dünya / Alem", ph: "/wɜːld/", d: "The earth, together with all of its countries and peoples.", ex: "The world is full of beauty to discover.", exTr: "Dünya keşfedilecek güzelliklerle doludur." },
  { w: "Write", p: "Verb", l: "A1", tr: "Yazmak", ph: "/raɪt/", d: "Mark letters on a surface with a pen or pencil.", ex: "Write your thoughts in a daily journal.", exTr: "Düşüncelerinizi günlük bir günlüğe yazın." },
  { w: "Year", p: "Noun", l: "A1", tr: "Yıl / Sene", ph: "/jɪər/", d: "The time taken by the earth to make one revolution around the sun.", ex: "Make this year your most transformative yet.", exTr: "Bu yılı şimdiye kadarki en dönüştürücü yılınız yapın." },
  { w: "Yellow", p: "Adj.", l: "A1", tr: "Sarı", ph: "/ˈjel.əʊ/", d: "The color of ripe lemons or the sun.", ex: "Bright yellow sunflowers turned toward the light.", exTr: "Parlak sarı ayçiçekleri ışığa doğru döndü." },
  { w: "Yesterday", p: "Adv.", l: "A1", tr: "Dün", ph: "/ˈjes.tə.deɪ/", d: "On the day before today.", ex: "Learn from yesterday and live for today.", exTr: "Dünden ders alın ve bugün için yaşayın." },
  { w: "Young", p: "Adj.", l: "A1", tr: "Genç", ph: "/jʌŋ/", d: "Having lived or existed for only a short time.", ex: "Young minds are curious and creative.", exTr: "Genç zihinler meraklı ve yaratıcıdır." },
];

console.log(`Kelime veri seti oluşturuldu. Toplam adet: ${wordPool.length}`);

const fullDataset = wordPool.map((item) => {
  const id = `w-${item.w.toLowerCase().replace(/[^a-z0-9]/g, '-')}`;
  return {
    id,
    word: item.w,
    phonetic: item.ph || `/${item.w.toLowerCase()}/`,
    partOfSpeech: item.p || "Noun",
    level: item.l || "A1",
    translation: item.tr,
    definition: item.d,
    example: item.ex,
    exampleTranslation: item.exTr,
    synonyms: [],
    lists: ["oxford-3000"],
    mastery: Math.floor(Math.random() * 30),
  };
});

const outputPath = path.join(__dirname, '..', 'src', 'data', 'expandedVocabulary.json');
fs.writeFileSync(outputPath, JSON.stringify(fullDataset, null, 2), 'utf-8');
console.log(`✅ ${fullDataset.length} adet kelime 'src/data/expandedVocabulary.json' dosyasına yazıldı!`);
