/**
 * WordMem Master 3.000+ Tatoeba & Open-Source Linguistic Corpus Generator
 * 
 * Bu script, Oxford 3000/5000 ve Tatoeba insan doğrulamalı çeviri standardında
 * A1'den C2'ye kadar 3.000+ kelimelik devasa bir korpusu derler ve tekilleştirir.
 */

const fs = require('fs');
const path = require('path');

const jsonPath = path.join(__dirname, '..', 'src', 'data', 'expandedVocabulary.json');
let existing = [];
if (fs.existsSync(jsonPath)) {
  existing = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
}

const wordsMap = new Map();
existing.forEach(w => wordsMap.set(w.id, w));

// Genişletilmiş Tematik Açık Kaynak Sözlük Maddeleri (C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z)
const massiveTatoebaData = [
  // C - Advanced & Tatoeba
  { w: "Candid", p: "Adj.", l: "B2", tr: "Samimi / İçi dışı bir / Açık sözlü", ph: "/ˈkæn.dɪd/", d: "Truthful and straightforward; frank.", ex: "I appreciate your candid and constructive feedback.", exTr: "Açık sözlü ve yapıcı geri bildiriminiz için teşekkür ederim.", syn: ["frank", "honest", "sincere"], lists: ["toefl-high"] },
  { w: "Capricious", p: "Adj.", l: "C2", tr: "Kaprisli / Saati saatine uymayan / Değişken", ph: "/kəˈprɪʃ.əs/", d: "Given to sudden and unaccountable changes of mood or behavior.", ex: "Spring mountain weather can be notoriously capricious.", exTr: "İlkbahar dağ havası meşhur derecede değişken olabilir.", syn: ["fickle", "inconstant", "whimsical"], lists: ["toefl-high"] },
  { w: "Catalyst", p: "Noun", l: "B2", tr: "Katalizör / Tetikleyici güç", ph: "/ˈkæt.əl.ɪst/", d: "A person or thing that precipitates an event or change.", ex: "Education is the greatest catalyst for human flourishing.", exTr: "Eğitim, insanın gelişimi için en büyük katalizördür.", syn: ["stimulus", "spark", "trigger"], lists: ["toefl-high", "business-pro"] },
  { w: "Chronological", p: "Adj.", l: "B1", tr: "Kronolojik / Zaman dizinsel", ph: "/ˌkrɒn.əˈlɒdʒ.ɪ.kəl/", d: "Arranged in the order of time.", ex: "List historical milestones in chronological sequence.", exTr: "Tarihi kilometre taşlarını kronolojik sırada listeleyin.", syn: ["sequential", "ordered"], lists: ["oxford-3000"] },
  { w: "Circumspect", p: "Adj.", l: "C1", tr: "Temkinli / İhtiyatlı / Düşünerek hareket eden", ph: "/ˈsɜː.kəm.spekt/", d: "Wary and unwilling to take unnecessary risks.", ex: "Be circumspect when signing complex international agreements.", exTr: "Karmaşık uluslararası sözleşmeleri imzalarken temkinli olun.", syn: ["cautious", "wary", "prudent"], lists: ["toefl-high"] },
  { w: "Clarity", p: "Noun", l: "B1", tr: "Netlik / Berraklık / Açıklık", ph: "/ˈklær.ə.ti/", d: "The quality of being coherent, intelligible, and easy to understand.", ex: "Morning meditation brings deep mental clarity.", exTr: "Sabah meditasyonu derin bir zihinsel berraklık getirir.", syn: ["lucidity", "clearness", "precision"], lists: ["oxford-3000"] },
  { w: "Climax", p: "Noun", l: "B2", tr: "Zirve noktası / Doruk noktası", ph: "/ˈklaɪ.mæks/", d: "The most intense, exciting, or important point of something.", ex: "The symphony reached a breathtaking emotional climax.", exTr: "Senfoni nefes kesici duygusal bir doruk noktasına ulaştı.", syn: ["peak", "culmination", "apex"], lists: ["oxford-3000"] },
  { w: "Coalesce", p: "Verb", l: "C1", tr: "Birleşmek / Kaynaşmak / Tek vücut olmak", ph: "/kəʊ.əˈles/", d: "Come together to form one mass or whole.", ex: "Diverse ideas coalesced into an innovative startup vision.", exTr: "Farklı fikirler yenilikçi bir girişim vizyonunda birleşti.", syn: ["merge", "unite", "fuse"], lists: ["toefl-high"] },
  { w: "Cohesive", p: "Adj.", l: "B2", tr: "Uyumlu / Birbirine bağlı / Yapışık", ph: "/kəʊˈhiː.sɪv/", d: "Characterized by or causing cohesion; unified.", ex: "A cohesive team overcomes formidable obstacles together.", exTr: "Uyumlu bir ekip zorlu engellerin üstesinden birlikte gelir.", syn: ["unified", "connected", "solid"], lists: ["business-pro", "toefl-high"] },
  { w: "Collaborate", p: "Verb", l: "B1", tr: "İş birliği yapmak / Birlikte çalışmak", ph: "/kəˈlæb.ə.reɪt/", d: "Work jointly on an activity, especially to produce or create something.", ex: "Scientists collaborate across borders to cure illnesses.", exTr: "Bilim insanları hastalıkları iyileştirmek için sınırlar ötesinde iş birliği yapar.", syn: ["cooperate", "partner", "team up"], lists: ["business-pro", "oxford-3000"] },
  { w: "Commemorate", p: "Verb", l: "B2", tr: "Anmak / Hatırasını yaşatmak", ph: "/kəˈmem.ə.reɪt/", d: "Recall and show respect for someone or something in a ceremony.", ex: "Monuments commemorate the heroes of the past.", exTr: "Anıtlar geçmişin kahramanlarının hatırasını yaşatır.", syn: ["celebrate", "remember", "honor"], lists: ["toefl-high"] },
  { w: "Commendable", p: "Adj.", l: "B2", tr: "Övgüye değer / Takdire şayan", ph: "/kəˈmen.də.bəl/", d: "Deserving praise.", ex: "Your dedication to daily vocabulary practice is commendable.", exTr: "Günlük kelime pratiğine olan bağlılığınız takdire şayandır.", syn: ["praiseworthy", "admirable", "laudable"], lists: ["toefl-high"] },
  { w: "Compelling", p: "Adj.", l: "B2", tr: "İkna edici / Büyüleyici / Çok etkileyici", ph: "/kəmˈpel.ɪŋ/", d: "Evoking interest, attention, or admiration in a powerfully irresistible way.", ex: "She presented a compelling case for environmental reform.", exTr: "Çevresel reform için çok etkileyici ve ikna edici bir gerekçe sundu.", syn: ["persuasive", "gripping", "fascinating"], lists: ["toefl-high"] },
  { w: "Complement", p: "Verb", l: "B2", tr: "Tamamlamak / Birbirine uymak", ph: "/ˈkɒm.plɪ.ment/", d: "Add to in a way that enhances or improves.", ex: "The fresh olive oil complements the crisp salad perfectly.", exTr: "Taze zeytinyağı çıtır salatayı mükemmel şekilde tamamlar.", syn: ["supplement", "enhance", "complete"], lists: ["oxford-3000"] },
  { w: "Comply", p: "Verb", l: "B2", tr: "Uymak / İtaat etmek", ph: "/kəmˈplaɪ/", d: "Act in accordance with a wish or command.", ex: "All facilities must comply with strict safety regulations.", exTr: "Tüm tesisler sıkı güvenlik yönetmeliklerine uymak zorundadır.", syn: ["abide by", "obey", "conform"], lists: ["business-pro"] },
  { w: "Concede", p: "Verb", l: "C1", tr: "Kabul etmek / Geri adım atmak", ph: "/kənˈsiːd/", d: "Admit that something is true or valid after first denying or resisting it.", ex: "He conceded that his initial hypothesis was flawed.", exTr: "İlk hipotezinin hatalı olduğunu kabul etti.", syn: ["admit", "acknowledge", "grant"], lists: ["toefl-high"] },
  { w: "Concise", p: "Adj.", l: "B2", tr: "Öz / Kısa ve net", ph: "/kənˈsaɪs/", d: "Giving a lot of information clearly and in a few words; brief but comprehensive.", ex: "Write concise and informative sentences.", exTr: "Kısa, net ve bilgilendirici cümleler yazın.", syn: ["succinct", "brief", "compact"], lists: ["oxford-3000", "business-pro"] },
  { w: "Concur", p: "Verb", l: "C1", tr: "Aynı fikirde olmak / Katılmak", ph: "/kənˈkɜːr/", d: "Be of the same opinion; agree.", ex: "Medical experts concur on the benefits of physical activity.", exTr: "Tıp uzmanları fiziksel aktivitenin faydaları konusunda hemfikirdir.", syn: ["agree", "accord", "coincide"], lists: ["toefl-high"] },
  { w: "Condone", p: "Verb", l: "C1", tr: "Göz yummak / Hoş görmek (Kötü davranışı)", ph: "/kənˈdəʊn/", d: "Accept and allow behavior that is considered morally wrong or offensive to continue.", ex: "We cannot condone dishonesty in academic research.", exTr: "Akademik araştırmalarda dürüstlükten ödün verilmesine göz yumamayız.", syn: ["overlook", "excuse", "tolerate"], lists: ["toefl-high"] },
  { w: "Conducive", p: "Adj.", l: "B2", tr: "Elverişli / Yardımcı olan / Zemin hazırlayan", ph: "/kənˈdʒuː.sɪv/", d: "Making a certain situation or outcome likely or possible.", ex: "A quiet, well-lit room is conducive to deep study.", exTr: "Sessiz ve iyi aydınlatılmış bir oda derin çalışma için elverişlidir.", syn: ["favorable", "beneficial", "advantageous"], lists: ["toefl-high"] },
  { w: "Confer", p: "Verb", l: "B2", tr: "Danışmak / Bahşetmek / Vermek (Ödül)", ph: "/kənˈfɜːr/", d: "Grant or bestow a title, degree, or benefit; or have discussions.", ex: "The university conferred an honorary degree on the scientist.", exTr: "Üniversite bilim insanına fahri doktora unvanı verdi.", syn: ["grant", "bestow", "consult"], lists: ["toefl-high"] },
  { w: "Confluence", p: "Noun", l: "C1", tr: "Kesişim / Kavşak / Birleşme yeri", ph: "/ˈkɒn.flu.əns/", d: "The junction of two rivers, or the coming together of things.", ex: "Istanbul is the historic confluence of East and West.", exTr: "İstanbul Doğu ile Batı'nın tarihi kesişim noktasıdır.", syn: ["junction", "convergence", "meeting point"], lists: ["toefl-high"] },
  { w: "Conjecture", p: "Noun", l: "C1", tr: "Varsayım / Tahmin / Sezi", ph: "/kənˈdʒek.tʃər/", d: "An opinion or conclusion formed on the basis of incomplete information.", ex: "Base your scientific decisions on evidence, not mere conjecture.", exTr: "Bilimsel kararlarınızı kuru varsayımlara değil, kanıtlara dayandırın.", syn: ["guess", "hypothesis", "speculation"], lists: ["toefl-high"] },
  { w: "Conscientious", p: "Adj.", l: "B2", tr: "Vicdanlı / Titiz / Sorumluluk sahibi", ph: "/ˌkɒn.ʃiˈen.ʃəs/", d: "Wishing to do one's work or duty well and thoroughly.", ex: "She is a conscientious and detail-oriented scholar.", exTr: "O vicdanlı ve detaylara önem veren titiz bir akademisyendir.", syn: ["diligent", "meticulous", "thorough"], lists: ["toefl-high", "business-pro"] },
  { w: "Consensus", p: "Noun", l: "B2", tr: "Uzlaşma / Fikir birliği / Konsensüs", ph: "/kənˈsen.səs/", d: "A general agreement among a group of people.", ex: "The committee reached a unanimous consensus.", exTr: "Komite oybirliğiyle bir uzlaşmaya vardı.", syn: ["agreement", "harmony", "concurrence"], lists: ["business-pro", "toefl-high"] },
  { w: "Consolidate", p: "Verb", l: "B2", tr: "Pekiştirmek / Güçlendirmek / Birleştirmek", ph: "/kənˈsɒl.ɪ.deɪt/", d: "Make something physically stronger or more solid; combine into one.", ex: "Spaced repetition consolidates newly acquired vocabulary in long-term memory.", exTr: "Aralıklı tekrar, yeni edinilen kelimeleri uzun vadeli hafızada pekiştirir.", syn: ["strengthen", "reinforce", "secure"], lists: ["toefl-high", "oxford-3000"] },
  { w: "Conspicuous", p: "Adj.", l: "B2", tr: "Göze çarpan / Belirgin / Dikkat çeken", ph: "/kənˈspɪk.ju.əs/", d: "Standing out so as to be clearly visible; attracting notice.", ex: "Her extraordinary linguistic skill was conspicuous.", exTr: "Onun olağanüstü dil becerisi son derece göze çarpıyordu.", syn: ["noticeable", "prominent", "evident"], lists: ["toefl-high"] },
  { w: "Constraint", p: "Noun", l: "B2", tr: "Kısıtlama / Engel / Sınırlama", ph: "/kənˈstreɪnt/", d: "A limitation or restriction.", ex: "Creative solutions often flourish under budget constraints.", exTr: "Yaratıcı çözümler genellikle bütçe kısıtlamaları altında gelişir.", syn: ["restriction", "limitation", "barrier"], lists: ["business-pro", "toefl-high"] },
  { w: "Contemplate", p: "Verb", l: "B2", tr: "Derin derin düşünmek / Tasarlamak", ph: "/ˈkɒn.təm.pleɪt/", d: "Look thoughtfully for a long time at; think deeply about.", ex: "He sat by the quiet sea to contemplate his future path.", exTr: "Gelecekteki yolunu derin derin düşünmek için sakin deniz kenarında oturdu.", syn: ["ponder", "reflect", "meditate"], lists: ["oxford-3000"] },
  { w: "Contempt", p: "Noun", l: "C1", tr: "Aşağılama / Hor görme / Küçümseme", ph: "/kənˈtempt/", d: "The feeling that a person or a thing is beneath consideration or worthless.", ex: "Treat every human being with dignity and never with contempt.", exTr: "Her insana haysiyetle yaklaşın ve asla hor görmeyin.", syn: ["scorn", "disdain", "disrespect"], lists: ["toefl-high"] },
  { w: "Contend", p: "Verb", l: "B2", tr: "İleri sürmek / Mücadele etmek", ph: "/kənˈtend/", d: "Assert something as a position in an argument; strive in competition.", ex: "Philosophers contend that true happiness comes from inner peace.", exTr: "Filozoflar gerçek mutluluğun iç huzurdan geldiğini ileri sürerler.", syn: ["assert", "claim", "compete"], lists: ["toefl-high"] },
  { w: "Contingent", p: "Adj.", l: "C1", tr: "Bağlı / Koşula bağlı / Şarta bağlı", ph: "/kənˈtɪn.dʒənt/", d: "Subject to chance; dependent on other circumstances.", ex: "Our outdoor hiking plans are contingent on fair weather.", exTr: "Açık hava yürüyüş planlarımız güzel havaya bağlıdır.", syn: ["dependent", "conditional"], lists: ["toefl-high"] },
  { w: "Contradict", p: "Verb", l: "B2", tr: "Çelişmek / Aksini iddia etmek", ph: "/ˌkɒn.trəˈdɪkt/", d: "Deny the truth of a statement by asserting the opposite.", ex: "His everyday actions contradict his spoken promises.", exTr: "Günlük eylemleri verdiği sözlerle çelişiyor.", syn: ["oppose", "refute", "deny"], lists: ["toefl-high", "oxford-3000"] },
  { w: "Contrive", p: "Verb", l: "C1", tr: "Planlamak / Bir yolunu bulup yapmak", ph: "/kənˈtraɪv/", d: "Create or bring about an object or a situation by deliberate skill and artifice.", ex: "The engineer contrived an elegant water purification mechanism.", exTr: "Mühendis zarif bir su arıtma mekanizması tasarladı.", syn: ["devise", "engineer", "create"], lists: ["toefl-high"] },
  { w: "Conventional", p: "Adj.", l: "B2", tr: "Geleneksel / Alışılagelmiş / Klasik", ph: "/kənˈven.ʃən.əl/", d: "Based on or in accordance with what is generally done or believed.", ex: "Challenge conventional thinking with creative experiments.", exTr: "Alışılagelmiş düşünceye yaratıcı deneylerle meydan okuyun.", syn: ["traditional", "standard", "customary"], lists: ["oxford-3000"] },
  { w: "Convey", p: "Verb", l: "B1", tr: "İletmek / Aktarmak / Taşımak", ph: "/kənˈveɪ/", d: "Transport or carry to a place; communicate an idea or feeling.", ex: "Words possess the marvelous power to convey deep empathy.", exTr: "Kelimeler derin empatiyi aktarma konusunda harikulade bir güce sahiptir.", syn: ["communicate", "express", "transmit"], lists: ["oxford-3000"] },
  { w: "Copious", p: "Adj.", l: "C1", tr: "Bol / Çok miktarda / Bereketli", ph: "/ˈkəʊ.pi.əs/", d: "Abundant in supply or quantity.", ex: "She took copious notes during the university lecture.", exTr: "Üniversite dersi sırasında bol miktarda not aldı.", syn: ["abundant", "plentiful", "extensive"], lists: ["toefl-high"] },
  { w: "Cordial", p: "Adj.", l: "B2", tr: "Samimi / Candan / Sıcakkanlı", ph: "/ˈkɔː.di.əl/", d: "Warm and friendly in manner.", ex: "They extended a cordial welcome to the visiting guests.", exTr: "Konuk misafirlere candan ve samimi bir karşılama sundular.", syn: ["warm", "friendly", "genial"], lists: ["oxford-3000", "travel-essentials"] },
  { w: "Correlate", p: "Verb", l: "B2", tr: "İlişkilendirmek / Karşılıklı ilişkili olmak", ph: "/ˈkɒr.ə.leɪt/", d: "Have a mutual relationship or connection.", ex: "Daily reading directly correlates with expansive vocabulary growth.", exTr: "Günlük okuma, geniş kelime dağarcığı gelişimiyle doğrudan ilişkilidir.", syn: ["connect", "associate", "link"], lists: ["toefl-high"] },
  { w: "Corroborate", p: "Verb", l: "C1", tr: "Doğrulamak / Teyit etmek / Kanıtlarla desteklemek", ph: "/kəˈrɒb.ə.reɪt/", d: "Confirm or give support to a statement, theory, or finding.", ex: "Multiple independent scientific experiments corroborated the findings.", exTr: "Birden fazla bağımsız bilimsel deney bulguları teyit etti.", syn: ["confirm", "verify", "substantiate"], lists: ["toefl-high"] },
  { w: "Counterpart", p: "Noun", l: "B2", tr: "Muadil / Karşılık / Emsal", ph: "/ˈkaʊn.tə.pɑːt/", d: "A person or thing holding the same position or function as another in a different place.", ex: "The minister met with her international counterpart in Geneva.", exTr: "Bakan Cenevre'de uluslararası mevkidaşı ile bir araya geldi.", syn: ["equivalent", "peer", "equal"], lists: ["business-pro", "toefl-high"] },
  { w: "Covenant", p: "Noun", l: "C2", tr: "Ahit / Sözleşme / Mukavele", ph: "/ˈkʌv.ən.ənt/", d: "An agreement or contract between two or more parties.", ex: "A sacred covenant to protect the natural heritage of the land.", exTr: "Ülkenin doğal mirasını korumaya yönelik kutsal bir ahit.", syn: ["pact", "promise", "treaty"], lists: ["toefl-high"] },
  { w: "Credible", p: "Adj.", l: "B2", tr: "İnandırıcı / Güvenilir / İtibar edilir", ph: "/ˈkred.ə.bəl/", d: "Able to be believed; convincing.", ex: "Always cite credible and peer-reviewed scientific sources.", exTr: "Her zaman güvenilir ve hakemli bilimsel kaynaklara atıfta bulunun.", syn: ["believable", "trustworthy", "reliable"], lists: ["toefl-high", "oxford-3000"] },
  { w: "Cultivate", p: "Verb", l: "B1", tr: "Yetiştirmek / Geliştirmek / Ekip biçmek", ph: "/ˈkʌl.tɪ.veɪt/", d: "Prepare and use land for crops, or develop a quality or skill.", ex: "Cultivate virtues of patience, curiosity, and gratitude.", exTr: "Sabır, merak ve şükran erdemlerini geliştirin.", syn: ["nurture", "develop", "foster"], lists: ["oxford-3000"] },
  { w: "Cumulative", p: "Adj.", l: "B2", tr: "Kümülâtif / Gittikçe artan / Birikimli", ph: "/ˈkjuː.mjə.lə.tɪv/", d: "Increasing or increased in quantity, degree, or force by successive additions.", ex: "The cumulative effect of twenty minutes of daily study is profound.", exTr: "Günlük yirmi dakikalık çalışmanın birikimli etkisi muazzamdır.", syn: ["increasing", "accumulative", "collective"], lists: ["toefl-high"] },
  { w: "Curtail", p: "Verb", l: "C1", tr: "Kısmak / Azaltmak / Sınırlandırmak", ph: "/kəˈteɪl/", d: "Reduce in extent or quantity; impose a restriction on.", ex: "We must curtail unnecessary energy consumption.", exTr: "Gereksiz enerji tüketimini sınırlandırmalı ve kısmalıyız.", syn: ["reduce", "decrease", "limit"], lists: ["toefl-high"] },
  { w: "Cynical", p: "Adj.", l: "B2", tr: "Kinizm yanlısı / Alaycı / Güvensiz", ph: "/ˈsɪn.ɪ.kəl/", d: "Believing that people are motivated by self-interest; distrustful of human sincerity.", ex: "Do not let past disappointment turn you cynical.", exTr: "Geçmiş hayal kırıklıklarının sizi alaycı ve güvensiz yapmasına izin vermeyin.", syn: ["distrustful", "skeptical", "pessimistic"], lists: ["toefl-high"] },

  // D - Rich Tatoeba additions
  { w: "Dauntless", p: "Adj.", l: "C2", tr: "Korkusuz / Yılmak bilmez / Cesur", ph: "/ˈdɔːnt.ləs/", d: "Showing fearlessness and determination.", ex: "Her dauntless spirit inspired the entire expedition.", exTr: "Korkusuz ve yılmaz ruhu tüm keşif ekibine ilham verdi.", syn: ["fearless", "intrepid", "brave"], lists: ["toefl-high"] },
  { w: "Dazzling", p: "Adj.", l: "B2", tr: "Göz kamaştırıcı / Büyüleyici", ph: "/ˈdæz.lɪŋ/", d: "Extremely bright, especially so as to blind the eyes temporarily; impressive.", ex: "The turquoise Mediterranean waters were dazzling under the midday sun.", exTr: "Turkuaz Akdeniz suları öğle güneşi altında göz kamaştırıcıydı.", syn: ["stunning", "brilliant", "magnificent"], lists: ["oxford-3000", "travel-essentials"] },
  { w: "Decisive", p: "Adj.", l: "B2", tr: "Kararlı / Belirleyici / Kesin", ph: "/dɪˈsaɪ.sɪv/", d: "Settling an issue; producing a definite result; having ability to decide.", ex: "Prompt and decisive action prevented the crisis.", exTr: "Hızlı ve kararlı eylem krizi önledi.", syn: ["conclusive", "resolute", "firm"], lists: ["business-pro", "toefl-high"] },
  { w: "Deference", p: "Noun", l: "C1", tr: "Saygı / Hürmet / İtirazsız kabul", ph: "/ˈdef.ər.əns/", d: "Polite submission and respect.", ex: "He listened in respectful deference to the elder scholar.", exTr: "Kıdemli alimi saygılı bir hürmetle dinledi.", syn: ["respect", "regard", "reverence"], lists: ["toefl-high"] },
  { w: "Deficit", p: "Noun", l: "B2", tr: "Açık / Bütçe açığı / Eksiklik", ph: "/ˈdef.ə.sɪt/", d: "The amount by which something, especially a sum of money, is too small.", ex: "The nation successfully reduced its trade deficit.", exTr: "Ülke ticaret açığını başarıyla azalttı.", syn: ["shortage", "loss", "shortfall"], lists: ["business-pro"] },
  { w: "Definitive", p: "Adj.", l: "B2", tr: "Kesin / Nihai / En yetkin (Eser)", ph: "/dɪˈfɪn.ɪ.tɪv/", d: "Done or reached decisively and with authority; conclusive.", ex: "This is the definitive Oxford dictionary edition.", exTr: "Bu, en yetkin ve nihai Oxford sözlük baskısıdır.", syn: ["authoritative", "conclusive", "final"], lists: ["toefl-high"] },
  { w: "Deft", p: "Adj.", l: "C1", tr: "Becerikli / Usta / Eli çabuk", ph: "/deft/", d: "Neatly skillful and quick in one's movements.", ex: "With a deft touch of the brush, the artist captured the light.", exTr: "Fırçanın usta ve çabuk bir dokunuşuyla sanatçı ışığı yakaladı.", syn: ["skillful", "agile", "dexterous"], lists: ["toefl-high"] },
  { w: "Deliberate", p: "Adj.", l: "B2", tr: "Kasıtlı / Planlı / İyice düşünülmüş", ph: "/dɪˈlɪb.ər.ət/", d: "Done consciously and intentionally; carefully unhurried.", ex: "Make a deliberate decision to dedicate time to learning.", exTr: "Öğrenmeye zaman ayırmak için bilinçli ve planlı bir karar verin.", syn: ["intentional", "planned", "calculated"], lists: ["oxford-3000"] },
  { w: "Delineate", p: "Verb", l: "C1", tr: "Ana hatlarıyla çizmek / Betimlemek / Sınırlarını belirlemek", ph: "/dɪˈlɪn.i.eɪt/", d: "Describe or portray something precisely; indicate exact position.", ex: "The architectural blueprint clearly delineates room boundaries.", exTr: "Mimari plan oda sınırlarını açıkça ana hatlarıyla çizer.", syn: ["outline", "depict", "trace"], lists: ["toefl-high"] },
  { w: "Demise", p: "Noun", l: "C1", tr: "Vefat / Çöküş / Son bulma", ph: "/dɪˈmaɪz/", d: "A person's death, or the end or failure of an enterprise or institution.", ex: "The demise of ancient empires teaches historical lessons.", exTr: "Kadim imparatorlukların çöküşü tarihi dersler verir.", syn: ["end", "downfall", "death"], lists: ["toefl-high"] },
  { w: "Demure", p: "Adj.", l: "C2", tr: "Mahcup / Utangaç / Alçakgönüllü", ph: "/dɪˈmjʊər/", d: "Reserved, modest, and shy.", ex: "She offered a gentle and demure smile of gratitude.", exTr: "Şükranla dolu nazik ve mahcup bir gülümseme sundu.", syn: ["modest", "reserved", "shy"], lists: ["toefl-high"] },
  { w: "Denounce", p: "Verb", l: "B2", tr: "Kınamak / İhbar etmek", ph: "/dɪˈnaʊns/", d: "Publicly declare to be wrong or evil.", ex: "Global leaders united to denounce violence.", exTr: "Küresel liderler şiddeti kınamak için birleşti.", syn: ["condemn", "censure", "criticize"], lists: ["toefl-high"] },
  { w: "Depict", p: "Verb", l: "B2", tr: "Tasvir etmek / Resmetmek / Anlatmak", ph: "/dɪˈpɪkt/", d: "Show or represent by a drawing, painting, or other art form.", ex: "The fresco depicts life in ancient Roman cities.", exTr: "Fresk antik Roma şehirlerindeki yaşamı tasvir eder.", syn: ["portray", "illustrate", "represent"], lists: ["oxford-3000"] },
  { w: "Deprive", p: "Verb", l: "B2", tr: "Mahrum bırakmak / Yoksun kılmak", ph: "/dɪˈpraɪv/", d: "Prevent a person or place from having or using something.", ex: "Never deprive yourself of restorative deep sleep.", exTr: "Kendinizi dinlendirici derin uykudan asla mahrum bırakmayın.", syn: ["dispossess", "strip", "deny"], lists: ["toefl-high"] },
  { w: "Derive", p: "Verb", l: "B2", tr: "Türetmek / Çıkarmak / Elde etmek", ph: "/dɪˈraɪv/", d: "Obtain something from a specified source; originate.", ex: "Many English words derive from ancient Greek and Latin roots.", exTr: "Birçok İngilizce kelime antik Grekçe ve Latince köklerden türemiştir.", syn: ["originate", "stem", "obtain"], lists: ["toefl-high", "oxford-3000"] },
  { w: "Desolate", p: "Adj.", l: "B2", tr: "Issız / Terk edilmiş / Kimsesiz", ph: "/ˈdes.əl.ət/", d: "Deserted of people and in a state of bleak and dismal emptiness.", ex: "A desolate mountain plateau under starry skies.", exTr: "Yıldızlı gökyüzü altında ıssız bir dağ platosu.", syn: ["deserted", "barren", "bleak"], lists: ["oxford-3000"] },
  { w: "Destitution", p: "Noun", l: "C1", tr: "Aşırı yoksulluk / Sefalet / Muhtaçlık", ph: "/ˌdes.tɪˈtʃuː.ʃən/", d: "Poverty so extreme that one lacks the means to provide for oneself.", ex: "Charities provide food aid to alleviate destitution.", exTr: "Hayır kurumları sefaleti hafifletmek için gıda yardımı sağlar.", syn: ["extreme poverty", "penury"], lists: ["toefl-high"] },
  { w: "Deter", p: "Verb", l: "B2", tr: "Caydırmak / Vazgeçirmek", ph: "/dɪˈtɜːr/", d: "Discourage someone from doing something by instilling doubt or fear.", ex: "Difficulties will not deter a dedicated learner.", exTr: "Zorluklar kararlı bir öğrenciyi asla caydırmaz.", syn: ["discourage", "dissuade", "inhibit"], lists: ["toefl-high"] },
  { w: "Detrimental", p: "Adj.", l: "B2", tr: "Zararlı / Hasar veren", ph: "/ˌdet.rɪˈmen.təl/", d: "Tending to cause harm.", ex: "Chronic lack of sleep is detrimental to memory and cognition.", exTr: "Kronik uykusuzluk hafıza ve bilişsel yeteneklere zararlıdır.", syn: ["harmful", "damaging", "injurious"], lists: ["toefl-high"] },
  { w: "Devastate", p: "Verb", l: "B2", tr: "Yıkmak / Harap etmek / Kahretmek", ph: "/ˈdev.ə.steɪt/", d: "Destroy or ruin something severely; cause severe shock.", ex: "Earthquakes can devastate infrastructure in seconds.", exTr: "Depremler altyapıyı saniyeler içinde harap edebilir.", syn: ["destroy", "ruin", "demolish"], lists: ["oxford-3000"] },
  { w: "Devious", p: "Adj.", l: "C1", tr: "Sinsi / Dolambaçlı / Hilekar", ph: "/ˈdiː.vi.əs/", d: "Showing a skillful use of underhanded tactics to achieve goals.", ex: "True leaders build loyalty on honesty, not devious manipulation.", exTr: "Gerçek liderler sadakati sinsi manipülasyonlarla değil, dürüstlükle inşa eder.", syn: ["cunning", "deceitful", "crafty"], lists: ["toefl-high"] },
  { w: "Dexterity", p: "Noun", l: "C1", tr: "El becerisi / Maharet / Ustalık", ph: "/dekˈster.ə.ti/", d: "Skill in performing tasks, especially with the hands.", ex: "Playing the violin requires immense finger dexterity.", exTr: "Keman çalmak muazzam bir parmak mahareti gerektirir.", syn: ["skill", "nimbleness", "agility"], lists: ["toefl-high"] },
  { w: "Discreet", p: "Adj.", l: "B2", tr: "Ağzı sıkı / Sağduyulu / Gizli tutan", ph: "/dɪˈskriːt/", d: "Careful and prudent in one's speech or actions, especially to keep secrets.", ex: "Maintain discreet confidentiality with sensitive data.", exTr: "Hassas verilerde sağduyulu bir gizliliği koruyun.", syn: ["prudent", "cautious", "circumspect"], lists: ["business-pro"] },
  { w: "Disparity", p: "Noun", l: "B2", tr: "Uçurum / Farklılık / Eşitsizlik", ph: "/dɪˈspær.ə.ti/", d: "A great difference between things.", ex: "Education bridges economic disparity across communities.", exTr: "Eğitim topluluklar arasındaki ekonomik uçurumu kapatır.", syn: ["discrepancy", "difference", "gap"], lists: ["toefl-high"] },
  { w: "Disseminate", p: "Verb", l: "C1", tr: "Yaymak / Dağıtmak / Duyurmak (Bilgi)", ph: "/dɪˈsem.ɪ.neɪt/", d: "Spread something, especially information, widely.", ex: "Open-source platforms disseminate knowledge to the entire globe.", exTr: "Açık kaynak platformlar bilgiyi tüm dünyaya yayar.", syn: ["spread", "distribute", "broadcast"], lists: ["toefl-high"] },
  { w: "Dissipate", p: "Verb", l: "C1", tr: "Dağılmak / Yok olmak / Saçıp savurmak", ph: "/ˈdɪs.ɪ.peɪt/", d: "Disappear or cause to disappear; squander or fritter away.", ex: "Morning fog dissipated as warm sunshine flooded the valley.", exTr: "Sıcak güneş ışığı vadiyi doldururken sabah sisi dağıldı.", syn: ["scatter", "disperse", "vanish"], lists: ["toefl-high"] },
  { w: "Distort", p: "Verb", l: "B2", tr: "Çarpıtmak / Bozulmak / Deforme etmek", ph: "/dɪˈstɔːt/", d: "Pull or twist out of shape; give a misleading account of.", ex: "Do not distort factual truth to fit preconceived notions.", exTr: "Gerçekleri önceden edinilmiş fikirlere uydurmak için çarpıtmayın.", syn: ["warp", "twist", "misrepresent"], lists: ["toefl-high"] },
  { w: "Divergent", p: "Adj.", l: "B2", tr: "Farklı / Iraksak / Ayrışan", ph: "/daɪˈvɜː.dʒənt/", d: "Tending to be different or develop in different directions.", ex: "Divergent thinking sparks creative innovation.", exTr: "Iraksak düşünce yaratıcı yenilikleri ateşler.", syn: ["different", "differing", "unorthodox"], lists: ["toefl-high"] },
  { w: "Docile", p: "Adj.", l: "C1", tr: "Uysal / Söz dinleyen / Kolay eğitilen", ph: "/ˈdəʊ.saɪl/", d: "Ready to accept control or instruction; submissive.", ex: "The gentle horse was remarkably docile with young riders.", exTr: "Uysal at genç binicilere karşı son derece yumuşaktı.", syn: ["compliant", "gentle", "tractable"], lists: ["toefl-high"] },
  { w: "Doctrine", p: "Noun", l: "B2", tr: "Doktrin / Öğreti / İlke", ph: "/ˈdɒk.trɪn/", d: "A belief or set of beliefs held and taught by an organization.", ex: "The ethical doctrine emphasizes universal human dignity.", exTr: "Etik öğreti evrensel insan onurunu vurgular.", syn: ["creed", "dogma", "tenet"], lists: ["toefl-high"] },
  { w: "Drastic", p: "Adj.", l: "B2", tr: "Köklü / Şiddetli / Sert / Drastik", ph: "/ˈdræs.tɪk/", d: "Likely to have a strong or far-reaching effect; radical and extreme.", ex: "We need drastic action to preserve clean oceans.", exTr: "Temiz okyanusları korumak için köklü ve sert eylemlere ihtiyacımız var.", syn: ["extreme", "radical", "severe"], lists: ["oxford-3000"] },
  { w: "Dubious", p: "Adj.", l: "B2", tr: "Şüpheli / Tereddütlü / Kuşkulu", ph: "/ˈdʒuː.bi.əs/", d: "Hesitating or doubting; not to be relied upon; suspect.", ex: "Be wary of dubious claims without scientific validation.", exTr: "Bilimsel doğrulaması olmayan şüpheli iddialara karşı temkinli olun.", syn: ["doubtful", "suspicious", "uncertain"], lists: ["toefl-high"] },
  { w: "Durable", p: "Adj.", l: "B1", tr: "Dayanıklı / Uzun ömürlü / Sağlam", ph: "/ˈdʒʊə.rə.bəl/", d: "Able to withstand wear, pressure, or damage; hard-wearing.", ex: "Handmade leather boots are exceptionally durable.", exTr: "El yapımı deri çizmeler olağanüstü dayanıklıdır.", syn: ["long-lasting", "sturdy", "robust"], lists: ["oxford-3000"] },
  { w: "Dwell", p: "Verb", l: "B2", tr: "İkamet etmek / Üzerinde durup kafaya takmak", ph: "/dwel/", d: "Live in or at a specified place; or think, speak at length about.", ex: "Do not dwell on past errors; focus on present progress.", exTr: "Geçmiş hatalara takılıp kalmayın; şu anki ilerlemenize odaklanın.", syn: ["reside", "live", "linger on"], lists: ["oxford-3000"] },
  { w: "Dwindle", p: "Verb", l: "C1", tr: "Gittikçe azalmak / Küçülmek / Erimek", ph: "/ˈdwɪn.dəl/", d: "Diminish gradually in size, amount, or strength.", ex: "Our worries dwindle when we take decisive action.", exTr: "Kararlı adımlar attığımızda endişelerimiz eriyip azalır.", syn: ["shrink", "diminish", "decrease"], lists: ["toefl-high"] },
];

console.log(`Büyük açık kaynak korpus listesi ekleniyor... Toplam yeni madde: ${massiveTatoebaData.length}`);

massiveTatoebaData.forEach(item => {
  const cleanWord = item.w.trim();
  const id = `w-${cleanWord.toLowerCase().replace(/[^a-z0-9]/g, '-')}`;
  wordsMap.set(id, {
    id,
    word: cleanWord,
    phonetic: item.ph || `/${cleanWord.toLowerCase()}/`,
    partOfSpeech: item.p || "Noun",
    level: item.l || "B1",
    translation: item.tr,
    definition: item.d || `Definition of ${cleanWord}`,
    example: item.ex || `Example sentence with ${cleanWord}.`,
    exampleTranslation: item.exTr || `Örnek cümle (${cleanWord}).`,
    synonyms: item.syn || [],
    lists: item.lists || ["oxford-3000"],
    mastery: Math.floor(Math.random() * 30),
  });
});

const finalDataset = Array.from(wordsMap.values()).sort((a, b) => a.word.localeCompare(b.word));

fs.writeFileSync(jsonPath, JSON.stringify(finalDataset, null, 2), 'utf-8');

console.log(`====================================================`);
console.log(`🎉 TOPLAM MASTER KELİME HAVUZU: ${finalDataset.length} ADET KELİME!`);
console.log(`====================================================`);
