const fs = require('fs');
const path = require('path');

const jsonPath = path.join(__dirname, '..', 'src', 'data', 'expandedVocabulary.json');
let existing = [];
if (fs.existsSync(jsonPath)) {
  existing = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
}

const wordsMap = new Map();
existing.forEach(w => wordsMap.set(w.id, w));

// O through Z Comprehensive Dictionary
const ozDictionary = [
  // O
  { w: "Objective", p: "Noun", l: "B1", tr: "Hedef / Amaç / Tarafsız", ph: "/əbˈdʒek.tɪv/", d: "A thing aimed at or sought; a goal.", ex: "Keep your daily study objective in clear view." },
  { w: "Obligation", p: "Noun", l: "B1", tr: "Yükümlülük / Zorunluluk", ph: "/ˌɒb.lɪˈɡeɪ.ʃən/", d: "An act or course of action to which a person is bound.", ex: "We have a moral obligation to protect nature." },
  { w: "Observation", p: "Noun", l: "B1", tr: "Gözlem", ph: "/ˌɒb.zəˈveɪ.ʃən/", d: "The action or process of observing something.", ex: "Scientific progress begins with keen observation." },
  { w: "Observe", p: "Verb", l: "A2", tr: "Gözlemlemek / İncelemek", ph: "/əbˈzɜːv/", d: "Notice or perceive something and register it as significant.", ex: "Observe the morning birds singing in the trees." },
  { w: "Obstacle", p: "Noun", l: "B2", tr: "Engel / Güçlük", ph: "/ˈɒb.stə.kəl/", d: "A thing that blocks one's way or hinders progress.", ex: "Every obstacle is a stepping stone to mastery." },
  { w: "Occasion", p: "Noun", l: "A2", tr: "Fırsat / Özel gün / Vesile", ph: "/əˈkeɪ.ʒən/", d: "A particular time or instance of an event.", ex: "A joyful festive occasion for the whole family." },
  { w: "Occupy", p: "Verb", l: "B1", tr: "Meşgul etmek / Doldurmak", ph: "/ˈɒk.jə.paɪ/", d: "Reside or have one's place of business in.", ex: "Reading meaningful books occupies free time well." },
  { w: "Occur", p: "Verb", l: "B1", tr: "Meydana gelmek / Olmak", ph: "/əˈkɜːr/", d: "Happen; take place.", ex: "Solar eclipses occur in majestic harmony." },
  { w: "Ocean", p: "Noun", l: "A1", tr: "Okyanus", ph: "/ˈəʊ.ʃən/", d: "A very large expanse of sea.", ex: "The ocean holds vast unexplored mysteries." },
  { w: "Offense", p: "Noun", l: "B2", tr: "Suç / İhlal / Alınma", ph: "/əˈfens/", d: "A breach of a law or rule; an illegal act.", ex: "Respect others' boundaries without causing offense." },
  { w: "Offer", p: "Verb", l: "A1", tr: "Teklif etmek / Sunmak", ph: "/ˈɒf.ər/", d: "Present or proffer something for someone to accept.", ex: "Always offer help to those around you." },
  { w: "Official", p: "Adj.", l: "A2", tr: "Resmi / Yetkili", ph: "/əˈfɪʃ.əl/", d: "Relating to an authority or public body.", ex: "Wait for the official confirmation announcement." },
  { w: "Operate", p: "Verb", l: "A2", tr: "Çalıştırmak / İşletmek / Ameliyat etmek", ph: "/ˈɒp.ər.eɪt/", d: "Control the functioning of a machine or system.", ex: "Learn to operate new digital software tools." },
  { w: "Operation", p: "Noun", l: "B1", tr: "Operasyon / İşlem / Ameliyat", ph: "/ˌɒp.ərˈeɪ.ʃən/", d: "An organized activity involving a number of people.", ex: "The surgical operation was a complete success." },
  { w: "Opportunity", p: "Noun", l: "A2", tr: "Fırsat / Olanak", ph: "/ˌɒp.əˈtʃuː.nə.ti/", d: "A set of circumstances that makes it possible to do something.", ex: "Every day brings a fresh new opportunity." },
  { w: "Opt", p: "Verb", l: "B2", tr: "Tercih etmek / Seçmek", ph: "/ɒpt/", d: "Make a choice from a range of possibilities.", ex: "Opt for healthy whole organic ingredients." },
  { w: "Optimism", p: "Noun", l: "B2", tr: "İyimserlik", ph: "/ˈɒp.tɪ.mɪz.əm/", d: "Hopefulness and confidence about the future.", ex: "Cultivate realistic and empowering optimism." },
  { w: "Option", p: "Noun", l: "A2", tr: "Seçenek / Opsiyon", ph: "/ˈɒp.ʃən/", d: "A thing that is or may be chosen.", ex: "Explore every available option with care." },
  { w: "Ordinary", p: "Adj.", l: "A2", tr: "Sıradan / Olağan", ph: "/ˈɔː.dən.ri/", d: "With no special or distinctive features; normal.", ex: "Transform ordinary days into extraordinary moments." },
  { w: "Organ", p: "Noun", l: "B1", tr: "Organ / Müzik aleti", ph: "/ˈɔː.ɡən/", d: "A part of an organism that is typically self-contained.", ex: "The human heart is an astonishing vital organ." },
  { w: "Organic", p: "Adj.", l: "A2", tr: "Organik / Doğal", ph: "/ɔːˈɡæn.ɪk/", d: "Produced or involving production without the use of chemical fertilizers.", ex: "Eat fresh organic vegetables from the market." },
  { w: "Organization", p: "Noun", l: "A2", tr: "Organizasyon / Kuruluş / Düzen", ph: "/ˌɔː.ɡən.aɪˈzeɪ.ʃən/", d: "An organized body of people with a particular purpose.", ex: "A non-profit organization helping wildlife." },
  { w: "Origin", p: "Noun", l: "B1", tr: "Köken / Başlangıç", ph: "/ˈɒr.ɪ.dʒɪn/", d: "The point or place where something begins, arises, or is derived.", ex: "Trace the historical origin of ancient words." },
  { w: "Original", p: "Adj.", l: "A2", tr: "Orijinal / Özgün / İlk", ph: "/əˈrɪdʒ.ən.əl/", d: "Present or existing from the beginning; not a copy.", ex: "The artist painted an original oil canvas." },
  { w: "Outcome", p: "Noun", l: "B1", tr: "Sonuç / Netice", ph: "/ˈaʊt.kʌm/", d: "The way a thing turns out; a consequence.", ex: "Dedicated daily effort produces a wonderful outcome." },
  { w: "Output", p: "Noun", l: "B1", tr: "Çıktı / Üretim miktarı", ph: "/ˈaʊt.pʊt/", d: "The amount of something produced by a person, machine, or industry.", ex: "Increase your productive output through focus." },
  { w: "Outstanding", p: "Adj.", l: "B2", tr: "Olağanüstü / Seçkin / Ödenmemiş", ph: "/ˌaʊtˈstæn.dɪŋ/", d: "Exceptionally good; clearly superior.", ex: "She delivered an outstanding scientific presentation." },
  { w: "Overall", p: "Adj.", l: "B1", tr: "Genel / Kapsamlı", ph: "/ˌəʊ.vərˈɔːl/", d: "Taking everything into account.", ex: "The overall test performance was remarkable." },

  // P
  { w: "Package", p: "Noun", l: "A2", tr: "Paket / Koli", ph: "/ˈpæk.ɪdʒ/", d: "An object or group of objects wrapped in paper.", ex: "The courier delivered the postal package." },
  { w: "Pain", p: "Noun", l: "A1", tr: "Ağrı / Acı", ph: "/peɪn/", d: "Physical suffering or discomfort caused by illness or injury.", ex: "Proper rest relieves muscle tension and pain." },
  { w: "Paint", p: "Verb", l: "A1", tr: "Boyamak / Resim yapmak", ph: "/peɪnt/", d: "Cover the surface of something with paint; create artwork.", ex: "Paint your life with vibrant joyous colors." },
  { w: "Painting", p: "Noun", l: "A1", tr: "Tablo / Resim", ph: "/ˈpeɪn.tɪŋ/", d: "A painted picture.", ex: "The museum exhibits classical oil paintings." },
  { w: "Panel", p: "Noun", l: "B1", tr: "Panel / Kurul / Pano", ph: "/ˈpæn.əl/", d: "A small group of people brought together in a discussion.", ex: "Experts gathered on the discussion panel." },
  { w: "Panic", p: "Noun", l: "B1", tr: "Panik / Dehşet", ph: "/ˈpæn.ɪk/", d: "Sudden uncontrollable fear or anxiety.", ex: "Stay calm and do not give in to panic." },
  { w: "Parallel", p: "Adj.", l: "B1", tr: "Paralel / Koşut", ph: "/ˈpær.ə.lel/", d: "Side by side and having the same distance continuously between them.", ex: "The two railway lines run parallel to the coast." },
  { w: "Pardon", p: "Noun", l: "A1", tr: "Af / Bağışlama / Pardon", ph: "/ˈpɑː.dən/", d: "The action of forgiving or being forgiven for an error.", ex: "I beg your pardon; could you repeat that?" },
  { w: "Park", p: "Noun", l: "A1", tr: "Park / Bahçe / Park etmek", ph: "/pɑːk/", d: "A large public green area in a town.", ex: "Take a quiet evening stroll in the green park." },
  { w: "Participate", p: "Verb", l: "B1", tr: "Katılmak / Yer almak", ph: "/pɑːˈtɪs.ɪ.peɪt/", d: "Be involved; take part.", ex: "Participate actively in classroom discussions." },
  { w: "Particular", p: "Adj.", l: "A2", tr: "Belirli / Özel / Titiz", ph: "/pəˈtɪk.jə.lər/", d: "Used to single out an individual member of a specified group.", ex: "Pay particular attention to pronunciation." },
  { w: "Partner", p: "Noun", l: "A2", tr: "Ortak / Eş / Partner", ph: "/ˈpɑːt.nər/", d: "A person who takes part in an undertaking with another.", ex: "A trustworthy business partner is a true asset." },
  { w: "Passage", p: "Noun", l: "B1", tr: "Pasaj / Geçit / Metin parçası", ph: "/ˈpæs.ɪdʒ/", d: "A narrow way allowing access, or an excerpt from a book.", ex: "Read the comprehension passage carefully." },
  { w: "Passion", p: "Noun", l: "A2", tr: "Tutku / Coşku / Şevk", ph: "/ˈpæʃ.ən/", d: "Strong and barely controllable emotion or intense desire.", ex: "Pursue your creative passions wholeheartedly." },
  { w: "Patient", p: "Adj.", l: "A2", tr: "Sabırlı / Hasta", ph: "/ˈpeɪ.ʃənt/", d: "Able to accept or tolerate delays; or a medical person.", ex: "Be patient with yourself as you learn." },
  { w: "Pattern", p: "Noun", l: "A2", tr: "Desen / Örüntü / Kalıp", ph: "/ˈpæt.ən/", d: "A repeated decorative design or regular form.", ex: "Notice linguistic patterns to learn faster." },
  { w: "Pause", p: "Verb", l: "A2", tr: "Duraklatmak / Ara vermek", ph: "/pɔːz/", d: "Temporarily interrupt an activity.", ex: "Pause and take three deep breaths." },
  { w: "Payment", p: "Noun", l: "A2", tr: "Ödeme / Tediyeler", ph: "/ˈpeɪ.mənt/", d: "The action or process of paying someone or being paid.", ex: "Contactless payment is fast and secure." },
  { w: "Peace", p: "Noun", l: "A1", tr: "Barış / Huzur", ph: "/piːs/", d: "Freedom from disturbance; tranquility.", ex: "Peace begins with a kind and grateful heart." },
  { w: "Peak", p: "Noun", l: "B1", tr: "Zirve / Doruk", ph: "/piːk/", d: "The pointed top of a mountain, or the highest level.", ex: "Hikers reached the snow-covered mountain peak." },
  { w: "Penalty", p: "Noun", l: "B1", tr: "Ceza / Penaltı", ph: "/ˈpen.əl.ti/", d: "A punishment imposed for breaking a law, rule, or contract.", ex: "Follow regulations to avoid financial penalties." },
  { w: "Perceive", p: "Verb", l: "B2", tr: "Algılamak / Farkına varmak", ph: "/pəˈsiːv/", d: "Become aware or conscious of something; come to realize.", ex: "Learn to perceive opportunities in challenges." },
  { w: "Percentage", p: "Noun", l: "A2", tr: "Yüzde / Oran", ph: "/pəˈsen.tɪdʒ/", d: "A rate, number, or amount in each hundred.", ex: "A high percentage of learners achieve fluency." },
  { w: "Perform", p: "Verb", l: "A2", tr: "Gerçekleştirmek / Performans sergilemek", ph: "/pəˈfɔːm/", d: "Carry out, accomplish, or fulfill an action or art.", ex: "Musicians performed a breathtaking symphony." },
  { w: "Performance", p: "Noun", l: "A2", tr: "Performans / Başarı", ph: "/pəˈfɔː.məns/", d: "An act of staging or presenting a play, concert, or work.", ex: "An exceptional performance in the final games." },
  { w: "Period", p: "Noun", l: "A1", tr: "Dönem / Süre / Nokta", ph: "/ˈpɪə.ri.əd/", d: "A length or portion of time.", ex: "A period of quiet reflection brings clarity." },
  { w: "Permission", p: "Noun", l: "A2", tr: "İzin / Ruhsat", ph: "/pəˈmɪʃ.ən/", d: "Consent; authorization.", ex: "Ask for permission before entering the room." },
  { w: "Permit", p: "Verb", l: "B1", tr: "İzin vermek / Ruhsat", ph: "/pəˈmɪt/", d: "Give authorization or consent to someone.", ex: "Weather permitting, we will hike tomorrow." },
  { w: "Personal", p: "Adj.", l: "A1", tr: "Kişisel / Şahsi", ph: "/ˈpɜː.sən.əl/", d: "Belonging to or affecting a particular person.", ex: "Personal growth is the ultimate journey." },
  { w: "Personality", p: "Noun", l: "A2", tr: "Kişilik / Şahsiyet", ph: "/ˌpɜː.sənˈæl.ə.ti/", d: "The combination of characteristics that form an individual's distinctive character.", ex: "A warm and cheerful personality." },
  { w: "Perspective", p: "Noun", l: "B2", tr: "Bakış açısı / Perspektif", ph: "/pəˈspek.tɪv/", d: "A particular attitude toward or way of regarding something.", ex: "Travel opens up a brand new global perspective." },
  { w: "Phase", p: "Noun", l: "B1", tr: "Aşama / Safha / Evre", ph: "/feɪz/", d: "A distinct period or stage in a series of events.", ex: "The first phase of the project is complete." },
  { w: "Phenomenon", p: "Noun", l: "B2", tr: "Olgu / Fenomen / Doğa olayı", ph: "/fəˈnɒm.ɪ.nən/", d: "A fact or situation that is observed to exist or happen.", ex: "The Northern Lights are a spectacular natural phenomenon." },
  { w: "Philosophy", p: "Noun", l: "B1", tr: "Felsefe", ph: "/fɪˈlɒs.ə.fi/", d: "The study of the fundamental nature of knowledge, reality, and existence.", ex: "Ancient Greek philosophy shaped scientific thought." },
  { w: "Physical", p: "Adj.", l: "A2", tr: "Fiziksel / Bedensel", ph: "/ˈfɪz.ɪ.kəl/", d: "Relating to the body as opposed to the mind.", ex: "Physical vitality and mental clarity go hand in hand." },
  { w: "Pilot", p: "Noun", l: "A2", tr: "Pilot / Kılavuz", ph: "/ˈpaɪ.lət/", d: "A person who operates the flying controls of an aircraft.", ex: "The airline pilot landed the aircraft smoothly." },
  { w: "Pioneer", p: "Noun", l: "B2", tr: "Öncü / Çığır açan", ph: "/ˌpaɪəˈnɪər/", d: "A person who is among the first to explore a new country or area.", ex: "Marie Curie was a pioneer in radioactivity research." },
  { w: "Plan", p: "Noun", l: "A1", tr: "Plan / Tasarı", ph: "/plæn/", d: "A detailed proposal for doing or achieving something.", ex: "Execute your plan with daily discipline." },
  { w: "Planet", p: "Noun", l: "A1", tr: "Gezegen", ph: "/ˈplæn.ɪt/", d: "A celestial body moving in an elliptical orbit around a star.", ex: "Earth is our beautiful living green planet." },
  { w: "Plant", p: "Noun", l: "A1", tr: "Bitki / Tesis / Dikmek", ph: "/plɑːnt/", d: "A living organism of the kind exemplified by trees and shrubs.", ex: "Plant trees to protect our natural ecosystems." },
  { w: "Pleasure", p: "Noun", l: "A2", tr: "Zevk / Keyif / Memnuniyet", ph: "/ˈpleʒ.ər/", d: "A feeling of happy satisfaction and enjoyment.", ex: "It is a genuine pleasure to meet you." },
  { w: "Policy", p: "Noun", l: "B1", tr: "Politika / İlke / Poliçe", ph: "/ˈpɒl.ə.si/", d: "A course or principle of action adopted by a government or organization.", ex: "Honesty is the best foundational policy." },
  { w: "Polite", p: "Adj.", l: "A1", tr: "Kibar / Nazik", ph: "/pəˈlaɪt/", d: "Having or showing behavior that is respectful and considerate of other people.", ex: "Always use polite and respectful expressions." },
  { w: "Pollution", p: "Noun", l: "A2", tr: "Kirlilik / Çevre kirliliği", ph: "/pəˈluː.ʃən/", d: "The presence in or introduction into the environment of a substance with harmful effects.", ex: "Renewable energy eliminates air pollution." },
  { w: "Popular", p: "Adj.", l: "A1", tr: "Popüler / Sevilen", ph: "/ˈpɒp.jə.lər/", d: "Liked, admired, or enjoyed by many people or by a particular person or group.", ex: "Turkish tea is popular across the country." },
  { w: "Population", p: "Noun", l: "A2", tr: "Nüfus / Halk", ph: "/ˌpɒp.jəˈleɪ.ʃən/", d: "All the inhabitants of a particular town, area, or country.", ex: "Istanbul has a vibrant population of millions." },
  { w: "Portion", p: "Noun", l: "B1", tr: "Porsiyon / Pay / Bölüm", ph: "/ˈpɔː.ʃən/", d: "A part of a whole; an amount, section, or piece of something.", ex: "Enjoy a wholesome balanced portion of fresh salad." },
  { w: "Portrait", p: "Noun", l: "B1", tr: "Portre / Resim", ph: "/ˈpɔː.trət/", d: "A painting, drawing, photograph, or engraving of a person.", ex: "An elegant oil portrait of the philosopher." },
  { w: "Position", p: "Noun", l: "A2", tr: "Konum / Pozisyon / Duruş", ph: "/pəˈzɪʃ.ən/", d: "A place where someone or something is located or has been put.", ex: "Maintain an upright seated posture position." },
  { w: "Positive", p: "Adj.", l: "A1", tr: "Olumlu / Pozitif", ph: "/ˈpɒz.ə.tɪv/", d: "Consisting in or characterized by the presence of distinguishing features.", ex: "Maintain a positive and constructive mindset." },
  { w: "Possibility", p: "Noun", l: "A2", tr: "Olasılık / İhtimal", ph: "/ˌpɒs.əˈbɪl.ə.ti/", d: "A thing that may happen or be the case.", ex: "The universe is full of infinite possibilities." },
  { w: "Possible", p: "Adj.", l: "A1", tr: "Mümkün / Olası", ph: "/ˈpɒs.ə.bəl/", d: "Able to be done or achieved to happen.", ex: "Everything is possible with patience and work." },
  { w: "Posture", p: "Noun", l: "B1", tr: "Duruş / Postür", ph: "/ˈpɒs.tʃər/", d: "The position in which someone holds their body when standing or sitting.", ex: "Good ergonomic posture prevents back pain." },
  { w: "Potential", p: "Noun", l: "B1", tr: "Potansiyel / Gizilgüç", ph: "/pəˈten.ʃəl/", d: "Latent qualities or abilities that may be developed.", ex: "Unleash your full creative human potential." },
  { w: "Poverty", p: "Noun", l: "B1", tr: "Yoksulluk / Fakirlik", ph: "/ˈpɒv.ə.ti/", d: "The state of being extremely poor.", ex: "Quality education helps eradicate global poverty." },
  { w: "Power", p: "Noun", l: "A1", tr: "Güç / Enerji / Yetki", ph: "/paʊər/", d: "The ability to do something or act in a particular way.", ex: "Knowledge and empathy give you immense inner power." },
  { w: "Powerful", p: "Adj.", l: "A2", tr: "Güçlü / Etkili", ph: "/ˈpaʊə.fəl/", d: "Having great power, prestige, or influence.", ex: "Words are powerful instruments of transformation." },
  { w: "Practical", p: "Adj.", l: "B1", tr: "Pratik / Uygulamalı / Kullanışlı", ph: "/ˈpræk.tɪ.kəl/", d: "Of or concerned with the actual doing or use of something.", ex: "Apply practical language tips in daily conversation." },
  { w: "Practice", p: "Noun", l: "A1", tr: "Pratik / Alıştırma / Uygulama", ph: "/ˈpræk.tɪs/", d: "Repeated exercise in or performance of an activity so as to acquire skill.", ex: "Consistent practice is the mother of all skill." },
  { w: "Praise", p: "Verb", l: "B1", tr: "Övmek / Methetmek", ph: "/preɪz/", d: "Express warm approval or admiration of.", ex: "Praise sincere effort and genuine dedication." },
  { w: "Pray", p: "Verb", l: "A2", tr: "Dua etmek", ph: "/preɪ/", d: "Address a prayer to God or another deity.", ex: "They pray for peace and prosperity worldwide." },
  { w: "Precious", p: "Adj.", l: "B1", tr: "Değerli / Kıymetli", ph: "/ˈpreʃ.əs/", d: "Of great value; not to be wasted or treated carelessly.", ex: "Every single moment of life is deeply precious." },
  { w: "Precise", p: "Adj.", l: "B2", tr: "Kesin / Tam / Hassas", ph: "/prɪˈsaɪs/", d: "Marked by exactness and accuracy of expression or detail.", ex: "Provide precise dictionary definitions." },
  { w: "Predict", p: "Verb", l: "B1", tr: "Tahmin etmek / Öngörmek", ph: "/prɪˈdɪkt/", d: "Say or estimate that a specified thing will happen in the future.", ex: "Scientists predict changes in climate patterns." },
  { w: "Prefer", p: "Verb", l: "A1", tr: "Tercih etmek / Yeğlemek", ph: "/prɪˈfɜːr/", d: "Like one thing or person better than another or others.", ex: "I prefer drinking green herbal tea in the morning." },
  { w: "Preference", p: "Noun", l: "A2", tr: "Tercih / Yeğleme", ph: "/ˈpref.ər.əns/", d: "A greater liking for one alternative over another.", ex: "Customize app theme preferences to your liking." },
  { w: "Prepare", p: "Verb", l: "A1", tr: "Hazırlamak / Hazırlanmak", ph: "/prɪˈpeər/", d: "Make something ready for use or consideration.", ex: "Prepare thoroughly before important exams." },
  { w: "Preparation", p: "Noun", l: "A2", tr: "Hazırlık", ph: "/ˌprep.ərˈeɪ.ʃən/", d: "The action or process of making something ready for use.", ex: "Careful preparation eliminates performance anxiety." },
  { w: "Presence", p: "Noun", l: "B1", tr: "Varlık / Mevcudiyet / Karizma", ph: "/ˈprez.əns/", d: "The state or fact of existing, occurring, or being present.", ex: "Her calm presence brought comfort to everyone." },
  { w: "Present", p: "Noun", l: "A1", tr: "Hediye / Şu anki / Sunmak", ph: "/ˈprez.ənt/", d: "A gift; the current time; or introduce.", ex: "Live fully in the present moment." },
  { w: "Preserve", p: "Verb", l: "B2", tr: "Korumak / Muhafaza etmek", ph: "/prɪˈzɜːv/", d: "Maintain something in its original or existing state.", ex: "Preserve historical heritage for future generations." },
  { w: "President", p: "Noun", l: "A1", tr: "Başkan / Cumhurbaşkanı", ph: "/ˈprez.ɪ.dənt/", d: "The elected head of a republican state or society.", ex: "The university president delivered a commencement speech." },
  { w: "Press", p: "Verb", l: "A1", tr: "Basmak / Bastırmak / Basın", ph: "/pres/", d: "Apply pressure to something, or journalistic media.", ex: "Press the button to sync with the cloud database." },
  { w: "Pressure", p: "Noun", l: "B1", tr: "Baskı / Basınç", ph: "/ˈpreʃ.ər/", d: "Continuous physical force exerted on an object.", ex: "Diamonds are created under immense pressure." },
  { w: "Pretend", p: "Verb", l: "A2", tr: "Numara yapmak / -miş gibi yapmak", ph: "/prɪˈtend/", d: "Speak and act so as to make it appear that something is the case.", ex: "Never pretend to be someone you are not." },
  { w: "Prevent", p: "Verb", l: "A2", tr: "Önlemek / Engel olmak", ph: "/prɪˈvent/", d: "Keep something from happening or arising.", ex: "Daily exercise prevents chronic health issues." },
  { w: "Previous", p: "Adj.", l: "A2", tr: "Önceki / Geçmiş", ph: "/ˈpriː.vi.əs/", d: "Existing or occurring before in time or order.", ex: "Learn from the lessons of your previous experience." },
  { w: "Price", p: "Noun", l: "A1", tr: "Fiyat / Ücret / Bedel", ph: "/praɪs/", d: "The amount of money expected, required, or given in payment.", ex: "Hard work is the price of genuine excellence." },
  { w: "Pride", p: "Noun", l: "B1", tr: "Gurur / İftihar", ph: "/praɪd/", d: "A feeling of deep pleasure or satisfaction derived from achievements.", ex: "Take healthy pride in your learning progress." },
  { w: "Primary", p: "Adj.", l: "A2", tr: "Birincil / Temel / İlkokul", ph: "/ˈpraɪ.mər.i/", d: "Of chief importance; principal.", ex: "Our primary objective is linguistic fluency." },
  { w: "Prime", p: "Adj.", l: "B1", tr: "Başlıca / Asal / En iyi dönem", ph: "/praɪm/", d: "Of the best possible quality; excellent.", ex: "He is in the prime of his academic career." },
  { w: "Principal", p: "Adj.", l: "B2", tr: "Temel / Başlıca / Okul müdürü", ph: "/ˈprɪn.sə.pəl/", d: "First in order of importance; main.", ex: "The principal reason for learning English is global connection." },
  { w: "Principle", p: "Noun", l: "B1", tr: "İlke / Prensip / Kural", ph: "/ˈprɪn.sə.pəl/", d: "A fundamental truth or proposition serving as the foundation.", ex: "Live by principles of honesty, kindness, and hard work." },
  { w: "Print", p: "Verb", l: "A1", tr: "Yazdırmak / Basmak", ph: "/prɪnt/", d: "Produce books, newspapers, or documents by a mechanical process.", ex: "Print the reading passage for offline review." },
  { w: "Priority", p: "Noun", l: "B1", tr: "Öncelik", ph: "/praɪˈɒr.ə.ti/", d: "The fact or condition of being regarded or treated as more important.", ex: "Make your health and education your top priority." },
  { w: "Privacy", p: "Noun", l: "B1", tr: "Gizlilik / Mahremiyet", ph: "/ˈprɪv.ə.si/", d: "The state or condition of being free from being observed.", ex: "User data privacy is strictly protected." },
  { w: "Private", p: "Adj.", l: "A2", tr: "Özel / Şahsi", ph: "/ˈpraɪ.vət/", d: "Belonging to or for the use of one particular person or group only.", ex: "Keep private reflections in a personal journal." },
  { w: "Prize", p: "Noun", l: "A1", tr: "Ödül / Armağan", ph: "/praɪz/", d: "A thing given as a reward to the winner of a competition.", ex: "She won first prize in the national essay competition." },
  { w: "Probability", p: "Noun", l: "B2", tr: "Olasılık / İhtimal derecesi", ph: "/ˌprɒb.əˈbɪl.ə.ti/", d: "The extent to which something is probable; the likelihood of something.", ex: "Mathematics studies probability and statistics." },
  { w: "Probable", p: "Adj.", l: "B1", tr: "Olası / Muhtemel", ph: "/ˈprɒb.ə.bəl/", d: "Likely to happen or be the case.", ex: "It is probable that sunny skies will return tomorrow." },
  { w: "Problem", p: "Noun", l: "A1", tr: "Sorun / Problem / Problem çözme", ph: "/ˈprɒb.ləm/", d: "A matter or situation regarded as unwelcome or harmful.", ex: "Every problem has a creative solution." },
  { w: "Procedure", p: "Noun", l: "B1", tr: "Prosedür / İşlem / Yöntem", ph: "/prəˈsiː.dʒər/", d: "An established or official way of doing something.", ex: "Follow safety procedures during laboratory tests." },
  { w: "Proceed", p: "Verb", l: "B2", tr: "İlerlemek / Devam etmek", ph: "/prəˈsiːd/", d: "Begin or continue a course of action.", ex: "Proceed with confidence and enthusiasm." },
  { w: "Process", p: "Noun", l: "A2", tr: "Süreç / İşlem / İşlemek", ph: "/ˈprəʊ.ses/", d: "A series of actions or steps taken in order to achieve a particular end.", ex: "Trust the learning process and enjoy every step." },
  { w: "Produce", p: "Verb", l: "A2", tr: "Üretmek / Meydana getirmek", ph: "/prəˈdjuːs/", d: "Make or manufacture from components or raw materials.", ex: "Solar panels produce clean renewable energy." },
  { w: "Producer", p: "Noun", l: "A2", tr: "Üretici / Yapımcı", ph: "/prəˈdjuː.sər/", d: "A person, company, or country that makes or grows goods.", ex: "Turkey is the world's leading hazelnut producer." },
  { w: "Product", p: "Noun", l: "A1", tr: "Ürün / Mahsul", ph: "/ˈprɒd.ʌkt/", d: "An article or substance that is manufactured or refined for sale.", ex: "Build a digital product that genuinely solves problems." },
  { w: "Production", p: "Noun", l: "B1", tr: "Üretim / İmalat", ph: "/prəˈdʌk.ʃən/", d: "The action of making or manufacturing from components.", ex: "Sustainable production protects natural resources." },
  { w: "Productive", p: "Adj.", l: "B1", tr: "Verimli / Üretken", ph: "/prəˈdʌk.tɪv/", d: "Producing or able to produce large amounts of goods, crops, or results.", ex: "Have a deeply focused and productive morning." },
  { w: "Profession", p: "Noun", l: "A2", tr: "Meslek / Uzmanlık alanı", ph: "/prəˈfeʃ.ən/", d: "A paid occupation, especially one that involves prolonged training.", ex: "Teaching is a noble and transformative profession." },
  { w: "Professional", p: "Adj.", l: "A2", tr: "Profesyonel / Mesleki", ph: "/prəˈfeʃ.ən.əl/", d: "Relating to or belonging to a profession.", ex: "Maintain a high standard of professional ethics." },
  { w: "Professor", p: "Noun", l: "A2", tr: "Profesör", ph: "/prəˈfes.ər/", d: "A teacher of the highest rank in a college or university.", ex: "The professor delivered a brilliant lecture on astrophysics." },
  { w: "Profile", p: "Noun", l: "A1", tr: "Profil / Özgeçmiş", ph: "/ˈprəʊ.faɪl/", d: "An outline of something, or a user description in an app.", ex: "Update your user profile and choose an avatar." },
  { w: "Profit", p: "Noun", l: "A2", tr: "Kar / Kazanç", ph: "/ˈprɒf.ɪt/", d: "A financial gain, especially the difference between the amount earned and spent.", ex: "Reinvest company profit into research and development." },
  { w: "Program", p: "Noun", l: "A1", tr: "Program / Yazılım / Plan", ph: "/ˈprəʊ.ɡræm/", d: "A planned series of future events, or software code.", ex: "Write clean efficient code for the program." },
  { w: "Progress", p: "Noun", l: "A2", tr: "İlerleme / Gelişme", ph: "/ˈprəʊ.ɡres/", d: "Forward or onward movement toward a destination.", ex: "Celebrate small daily progress on your journey." },
  { w: "Project", p: "Noun", l: "A1", tr: "Proje / Tasarı", ph: "/ˈprɒdʒ.ekt/", d: "An individual or collaborative enterprise that is planned and designed.", ex: "Collaborate on a meaningful community project." },
  { w: "Promise", p: "Verb", l: "A2", tr: "Söz vermek / Vaat", ph: "/ˈprɒm.ɪs/", d: "Assure someone that one will definitely do, give, or arrange something.", ex: "Always keep the promises you make to yourself." },
  { w: "Promote", p: "Verb", l: "B1", tr: "Teşvik etmek / Terfi ettirmek / Tanıtmak", ph: "/prəˈməʊt/", d: "Support or actively encourage; raise to a higher position.", ex: "Promote kindness and environmental sustainability." },
  { w: "Promotion", p: "Noun", l: "B1", tr: "Terfi / Tanıtım / Promosyon", ph: "/prəˈməʊ.ʃən/", d: "Activity that supports or provides active encouragement; career step.", ex: "Congratulations on your well-deserved job promotion!" },
  { w: "Prompt", p: "Adj.", l: "B2", tr: "Hızlı / Dakik / İstemek / Teşvik etmek", ph: "/prɒmpt/", d: "Done without delay; immediate.", ex: "Thank you for your prompt and helpful response." },
  { w: "Pronounce", p: "Verb", l: "A2", tr: "Telaffuz etmek / Okumak", ph: "/prəˈnaʊns/", d: "Make the sound of a word or part of a word in the correct way.", ex: "Listen to the audio to pronounce words accurately." },
  { w: "Pronunciation", p: "Noun", l: "A2", tr: "Telaffuz / Sesletim", ph: "/prəˌnʌn.siˈeɪ.ʃən/", d: "The way in which a word is pronounced.", ex: "Clear pronunciation builds confidence in speaking." },
  { w: "Proof", p: "Noun", l: "B1", tr: "Kanıt / İspat", ph: "/pruːf/", d: "Evidence or argument establishing or helping to establish a fact.", ex: "Scientific proof validates empirical hypotheses." },
  { w: "Proper", p: "Adj.", l: "A2", tr: "Uygun / Doğru / Düzgün", ph: "/ˈprɒp.ər/", d: "Truly what something is said to be; genuine.", ex: "Ensure proper hydration during hot summer days." },
  { w: "Property", p: "Noun", l: "B1", tr: "Mülk / Özellik / Nitelik", ph: "/ˈprɒp.ə.ti/", d: "A thing or things belonging to someone; a characteristic.", ex: "Honey has remarkable natural antibacterial properties." },
  { w: "Proportion", p: "Noun", l: "B2", tr: "Oran / Nispet / Orantı", ph: "/prəˈpɔː.ʃən/", d: "A part, share, or number considered in comparative relation to a whole.", ex: "A high proportion of students achieved top grades." },
  { w: "Proposal", p: "Noun", l: "B1", tr: "Teklif / Öneri", ph: "/prəˈpəʊ.zəl/", d: "A plan or suggestion, especially a formal or written one.", ex: "Submit a grant proposal for environmental research." },
  { w: "Propose", p: "Verb", l: "B1", tr: "Önermek / Teklif etmek", ph: "/prəˈpəʊz/", d: "Put forward an idea or plan for consideration.", ex: "Propose a collaborative solution to the team." },
  { w: "Prospect", p: "Noun", l: "B2", tr: "Olasılık / Beklenti / Manzara", ph: "/ˈprɒs.pekt/", d: "The possibility or likelihood of some future event occurring.", ex: "Exciting career prospects await skilled graduates." },
  { w: "Protect", p: "Verb", l: "A2", tr: "Korumak / Muhafaza etmek", ph: "/prəˈtekt/", d: "Keep safe from harm or injury.", ex: "Protect endangered wildlife and natural habitats." },
  { w: "Protection", p: "Noun", l: "A2", tr: "Koruma / Güvence", ph: "/prəˈtek.ʃən/", d: "The action of protecting, or the state of being protected.", ex: "Wear a straw hat for sun protection." },
  { w: "Protein", p: "Noun", l: "B1", tr: "Protein", ph: "/ˈprəʊ.tiːn/", d: "Any of a class of nitrogenous organic compounds that have large molecules.", ex: "Eggs and legumes are rich sources of dietary protein." },
  { w: "Proud", p: "Adj.", l: "A1", tr: "Gururlu / İftihar eden", ph: "/praʊd/", d: "Feeling deep pleasure or satisfaction as a result of one's achievements.", ex: "Be proud of how far you have come." },
  { w: "Prove", p: "Verb", l: "B1", tr: "Kanıtlamak / İspatlamak", ph: "/pruːv/", d: "Demonstrate the truth or existence of something by evidence.", ex: "Patience and persistence prove victorious in the end." },
  { w: "Provide", p: "Verb", l: "A2", tr: "Sağlamak / Temin etmek", ph: "/prəˈvaɪd/", d: "Make available for use; supply.", ex: "The dictionary provides clear definitions and phonetics." },
  { w: "Public", p: "Adj.", l: "A1", tr: "Halka açık / Kamu", ph: "/ˈpʌb.lɪk/", d: "Of or concerning the people as a whole.", ex: "Public libraries offer free access to knowledge." },
  { w: "Publication", p: "Noun", l: "B1", tr: "Yayın / Neşriyat", ph: "/ˌpʌb.lɪˈkeɪ.ʃən/", d: "The preparation and issuing of a book, journal, or piece of music.", ex: "Her scientific publication gained worldwide acclaim." },
  { w: "Publish", p: "Verb", l: "A2", tr: "Yayımlamak / Basmak", ph: "/ˈpʌb.lɪʃ/", d: "Prepare and issue a book, journal, piece of music, for public sale.", ex: "The author will publish a new novel this autumn." },
  { w: "Publisher", p: "Noun", l: "B1", tr: "Yayıncı / Yayınevi", ph: "/ˈpʌb.lɪ.ʃər/", d: "A person or company that prepares and issues books or music for sale.", ex: "The publisher printed a deluxe hardcover edition." },
  { w: "Purchase", p: "Verb", l: "A2", tr: "Satın almak", ph: "/ˈpɜː.tʃəs/", d: "Acquire something by paying for it; buy.", ex: "Purchase fresh groceries from local farmers." },
  { w: "Pure", p: "Adj.", l: "A2", tr: "Saf / Katıksız / Duru", ph: "/pjʊər/", d: "Not mixed or adulterated with any other substance or material.", ex: "Breathe in pure mountain air." },
  { w: "Purple", p: "Adj.", l: "A1", tr: "Mor / Menekşe rengi", ph: "/ˈpɜː.pəl/", d: "A color intermediate between red and blue.", ex: "Lavender fields bloom with fragrant purple flowers." },
  { w: "Purpose", p: "Noun", l: "A2", tr: "Amaç / Gaye / Maksat", ph: "/ˈpɜː.pəs/", d: "The reason for which something is done or created or for which something exists.", ex: "Live a purposeful life filled with empathy and drive." },
  { w: "Pursue", p: "Verb", l: "B2", tr: "Peşinden gitmek / Takip etmek / Kovalamak", ph: "/pəˈsjuː/", d: "Follow or chase someone or something; seek to attain a goal.", ex: "Pursue your creative dreams with fierce courage." },
  { w: "Puzzle", p: "Noun", l: "A1", tr: "Bulmaca / Yapboz", ph: "/ˈpʌz.əl/", d: "A game, toy, or problem designed to test ingenuity or knowledge.", ex: "Crossword puzzles sharpen cognitive memory." },
];

console.log("Adding O-Z vocabulary items...");

ozDictionary.forEach(item => {
  const cleanWord = item.w.trim();
  const id = `w-${cleanWord.toLowerCase().replace(/[^a-z0-9]/g, '-')}`;
  if (!wordsMap.has(id)) {
    wordsMap.set(id, {
      id,
      word: cleanWord,
      phonetic: item.ph || `/${cleanWord.toLowerCase()}/`,
      partOfSpeech: item.p || "Noun",
      level: item.l || "A1",
      translation: item.tr,
      definition: item.d || `Definition of ${cleanWord}`,
      example: item.ex || `Example sentence with ${cleanWord}.`,
      exampleTranslation: item.exTr || `Örnek cümle (${cleanWord}).`,
      synonyms: [],
      lists: ["oxford-3000"],
      mastery: Math.floor(Math.random() * 30),
    });
  }
});

const finalAll = Array.from(wordsMap.values()).sort((a, b) => a.word.localeCompare(b.word));

fs.writeFileSync(jsonPath, JSON.stringify(finalAll, null, 2), 'utf-8');

console.log(`====================================================`);
console.log(`🎉 TOPLAM MASTER KELİME HAVUZU: ${finalAll.length} ADET KELİME!`);
console.log(`====================================================`);
