const fs = require('fs');
const path = require('path');

const jsonPath = path.join(__dirname, '..', 'src', 'data', 'expandedVocabulary.json');
let existing = [];
if (fs.existsSync(jsonPath)) {
  existing = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
}

const wordsMap = new Map();
existing.forEach(w => wordsMap.set(w.id, w));

// Geniş İngilizce Kelime Listesi & Türkçe Çevirileri
const massiveData = [
  // D
  { w: "Daily", p: "Adj.", l: "A1", tr: "Günlük", ph: "/ˈdeɪ.li/", d: "Done, produced, or occurring every day.", ex: "Practice daily for fast progress." },
  { w: "Damage", p: "Noun", l: "B1", tr: "Hasar / Zarar", ph: "/ˈdæm.ɪdʒ/", d: "Physical harm impairing value or usefulness.", ex: "Prevent damage with careful handling." },
  { w: "Decade", p: "Noun", l: "B1", tr: "On yıl / Dekat", ph: "/ˈdek.eɪd/", d: "A period of ten years.", ex: "Technology advanced over the last decade." },
  { w: "Decline", p: "Verb", l: "B2", tr: "Azalmak / Reddetmek", ph: "/dɪˈklaɪn/", d: "Diminish in strength or politely refuse.", ex: "Costs declined by twenty percent." },
  { w: "Decorate", p: "Verb", l: "A2", tr: "Dekore etmek / Süslemek", ph: "/ˈdek.ə.reɪt/", d: "Make something look more attractive.", ex: "Decorate the room with fragrant flowers." },
  { w: "Deep", p: "Adj.", l: "A1", tr: "Derin", ph: "/diːp/", d: "Extending far down from the top or surface.", ex: "Take a deep breath and relax." },
  { w: "Defend", p: "Verb", l: "B1", tr: "Savunmak / Korumak", ph: "/dɪˈfend/", d: "Protect from harm or danger.", ex: "Defend your core principles with courage." },
  { w: "Definite", p: "Adj.", l: "B1", tr: "Belirli / Kesin", ph: "/ˈdef.ɪ.nət/", d: "Clearly stated or decided; not vague.", ex: "We need a definite deadline for the launch." },
  { w: "Definition", p: "Noun", l: "A2", tr: "Tanım / Açıklama", ph: "/ˌdef.ɪˈnɪʃ.ən/", d: "A statement of the exact meaning of a word.", ex: "Read the definition in the dictionary." },
  { w: "Delicate", p: "Adj.", l: "B2", tr: "Narin / Hassas", ph: "/ˈdel.ɪ.kət/", d: "Very fine in texture or structure; easily broken.", ex: "Handle delicate porcelain with care." },
  { w: "Deliver", p: "Verb", l: "A2", tr: "Teslim etmek / Ulaştırmak", ph: "/dɪˈlɪv.ər/", d: "Bring and hand over a parcel or goods.", ex: "Deliver the package to the client." },
  { w: "Demand", p: "Noun", l: "B1", tr: "Talep / İstek", ph: "/dɪˈmɑːnd/", d: "An insistent request or economic desire.", ex: "There is high demand for clean energy." },
  { w: "Demonstrate", p: "Verb", l: "B2", tr: "Göstermek / Kanıtlamak", ph: "/ˈdem.ən.streɪt/", d: "Clearly show the existence or truth of.", ex: "Demonstrate your skills through real projects." },
  { w: "Depart", p: "Verb", l: "A2", tr: "Kalkmak / Ayrılmak", ph: "/dɪˈpɑːt/", d: "Leave, typically in order to start a journey.", ex: "The train will depart from platform two." },
  { w: "Departure", p: "Noun", l: "A2", tr: "Kalkış / Ayrılış", ph: "/dɪˈpɑː.tʃər/", d: "The action of leaving, especially on a trip.", ex: "Check the departure board at the airport." },
  { w: "Depend", p: "Verb", l: "A2", tr: "Bağlı olmak / Güvenmek", ph: "/dɪˈpend/", d: "Be controlled or determined by.", ex: "Success depends on consistent daily effort." },
  { w: "Deposit", p: "Noun", l: "A2", tr: "Depozito / Yatırmak", ph: "/dɪˈpɒz.ɪt/", d: "A sum of money placed or kept in a bank.", ex: "Pay a small deposit to confirm booking." },
  { w: "Depress", p: "Verb", l: "B2", tr: "Moralini bozmak / Düşürmek", ph: "/dɪˈpres/", d: "Make someone feel utterly dispirited.", ex: "Gloomy weather can temporarily depress mood." },
  { w: "Describe", p: "Verb", l: "A1", tr: "Tanımlamak / Tarif etmek", ph: "/dɪˈskraɪb/", d: "Give a detailed account in words.", ex: "Describe your ideal holiday destination." },
  { w: "Design", p: "Noun", l: "A1", tr: "Tasarım / Tasarlamak", ph: "/dɪˈzaɪn/", d: "A plan or drawing produced to show the look.", ex: "Clean minimalist design inspires focus." },
  { w: "Desire", p: "Noun", l: "B1", tr: "Arzu / İstek", ph: "/dɪˈzaɪər/", d: "A strong feeling of wanting to have something.", ex: "A genuine desire to help others." },
  { w: "Despair", p: "Noun", l: "B2", tr: "Umutsuzluk / Çaresizlik", ph: "/dɪˈspeər/", d: "The complete loss or absence of hope.", ex: "Never give in to temporary despair." },
  { w: "Destroy", p: "Verb", l: "B1", tr: "Yok etmek / Yıkmak", ph: "/dɪˈstrɔɪ/", d: "End the existence of something by damaging it.", ex: "Wildfires can destroy natural forests." },
  { w: "Detail", p: "Noun", l: "A2", tr: "Ayrıntı / Detay", ph: "/ˈdiː.teɪl/", d: "An individual feature, fact, or item.", ex: "Pay close attention to every single detail." },
  { w: "Detect", p: "Verb", l: "B2", tr: "Tespit etmek / Algılamak", ph: "/dɪˈtekt/", d: "Discover or identify the presence of.", ex: "Sensors detect subtle temperature changes." },
  { w: "Develop", p: "Verb", l: "A2", tr: "Geliştirmek / Gelişmek", ph: "/dɪˈvel.əp/", d: "Grow or cause to grow and become more mature.", ex: "Develop your vocabulary step by step." },
  { w: "Device", p: "Noun", l: "A2", tr: "Cihaz / Alet", ph: "/dɪˈvaɪs/", d: "A thing made or adapted for a particular purpose.", ex: "A smartphone is a versatile mobile device." },
  { w: "Devote", p: "Verb", l: "B2", tr: "Aramak / Vakfetmek", ph: "/dɪˈvəʊt/", d: "Give all or a large part of one's time.", ex: "Devote thirty minutes daily to reading." },
  { w: "Dialogue", p: "Noun", l: "A2", tr: "Diyalog", ph: "/ˈdaɪ.ə.lɒɡ/", d: "Conversation between two or more people.", ex: "Open dialogue builds mutual understanding." },
  { w: "Diamond", p: "Noun", l: "B1", tr: "Elmas", ph: "/ˈdaɪə.mənd/", d: "A precious stone of clear, colorless crystalline carbon.", ex: "Diamonds are forged under intense pressure." },
  { w: "Diet", p: "Noun", l: "A1", tr: "Diyet / Beslenme", ph: "/ˈdaɪ.ət/", d: "The kinds of food that a person habitually eats.", ex: "A balanced diet provides essential vitamins." },
  { w: "Differ", p: "Verb", l: "B1", tr: "Farklı olmak / Ayrışmak", ph: "/ˈdɪf.ər/", d: "Be unlike or dissimilar.", ex: "Opinions differ on economic policies." },
  { w: "Difference", p: "Noun", l: "A1", tr: "Fark / Ayrım", ph: "/ˈdɪf.ər.əns/", d: "A point or way in which things are not the same.", ex: "Make a positive difference in someone's life." },
  { w: "Different", p: "Adj.", l: "A1", tr: "Farklı / Değişik", ph: "/ˈdɪf.ər.ənt/", d: "Not the same as another or each other.", ex: "Every human has a unique and different perspective." },
  { w: "Difficult", p: "Adj.", l: "A1", tr: "Zor / Güç", ph: "/ˈdɪf.ɪ.kəlt/", d: "Needing much effort or skill to accomplish.", ex: "Difficult roads often lead to beautiful destinations." },
  { w: "Difficulty", p: "Noun", l: "B1", tr: "Zorluk / Güçlük", ph: "/ˈdɪf.ɪ.kəl.ti/", d: "The state or condition of being difficult.", ex: "Overcoming difficulty builds inner resilience." },
  { w: "Digest", p: "Verb", l: "B2", tr: "Sindirmek / Özümsemek", ph: "/daɪˈdʒest/", d: "Break down food in the stomach or absorb ideas.", ex: "Take time to digest complex information." },
  { w: "Digital", p: "Adj.", l: "A1", tr: "Dijital / Sayısal", ph: "/ˈdɪdʒ.ɪ.təl/", d: "Relating to computer technology.", ex: "We live in an interconnected digital era." },
  { w: "Dignity", p: "Noun", l: "B2", tr: "Haysiyet / Onur / Vakar", ph: "/ˈdɪɡ.nə.ti/", d: "The state of being worthy of honor or respect.", ex: "Treat every individual with supreme dignity." },
  { w: "Dimension", p: "Noun", l: "B2", tr: "Boyut / Ebat", ph: "/ˌdaɪˈmen.ʃən/", d: "A measurable extent of a particular kind.", ex: "Art adds a rich new dimension to life." },
  { w: "Diminish", p: "Verb", l: "B2", tr: "Azalmak / Eksilmek", ph: "/dɪˈmɪn.ɪʃ/", d: "Make or become less.", ex: "Patience will not diminish with practice." },
  { w: "Direct", p: "Adj.", l: "A2", tr: "Doğrudan / Direkt", ph: "/daɪˈrekt/", d: "Extending along the shortest path without break.", ex: "Take a direct flight to save precious time." },
  { w: "Direction", p: "Noun", l: "A1", tr: "Yön / İstikamet", ph: "/daɪˈrek.ʃən/", d: "A course along which someone or something moves.", ex: "Choose your life direction with clarity." },
  { w: "Director", p: "Noun", l: "A2", tr: "Yönetmen / Müdür", ph: "/daɪˈrek.tər/", d: "A person who is in charge of an activity or film.", ex: "The film director won critical acclaim." },
  { w: "Disaster", p: "Noun", l: "B1", tr: "Felaket / Afet", ph: "/dɪˈzɑː.stər/", d: "A sudden event causing great damage or loss.", ex: "Early warning systems prevent natural disaster." },
  { w: "Discourage", p: "Verb", l: "B2", tr: "Cesaretini kırmak", ph: "/dɪˈskʌr.ɪdʒ/", d: "Cause someone to lose confidence or enthusiasm.", ex: "Never let initial failures discourage you." },
  { w: "Discuss", p: "Verb", l: "A2", tr: "Tartışmak / Görüşmek", ph: "/dɪˈskʌs/", d: "Talk about something with another person.", ex: "Discuss the project milestones openly." },
  { w: "Discussion", p: "Noun", l: "A2", tr: "Tartışma / Görüşme", ph: "/dɪˈskʌʃ.ən/", d: "The action of talking about something.", ex: "A fruitful and constructive group discussion." },
  { w: "Disease", p: "Noun", l: "B1", tr: "Hastalık", ph: "/dɪˈziːz/", d: "A disorder of structure or function in a human.", ex: "Clean water prevents infectious disease." },
  { w: "Dish", p: "Noun", l: "A1", tr: "Yemek / Tabak", ph: "/dɪʃ/", d: "A shallow container for food or a cooked meal.", ex: "Hummus is a delicious Middle Eastern dish." },
  { w: "Distance", p: "Noun", l: "A2", tr: "Mesafe / Uzaklık", ph: "/ˈdɪs.təns/", d: "An amount of space between two things.", ex: "Distance is no barrier to true friendship." },
  { w: "Distant", p: "Adj.", l: "B1", tr: "Uzak / Mesafeli", ph: "/ˈdɪs.tənt/", d: "Far away in space or time.", ex: "Distant mountain peaks were covered in snow." },
  { w: "Distinct", p: "Adj.", l: "B2", tr: "Belirgin / Farklı", ph: "/dɪˈstɪŋkt/", d: "Recognizably different in nature.", ex: "Each dialect has a distinct melodic tone." },
  { w: "Distinguish", p: "Verb", l: "B2", tr: "Ayırt etmek / Fark etmek", ph: "/dɪˈstɪŋ.ɡwɪʃ/", d: "Recognize or treat someone as different.", ex: "Learn to distinguish fact from speculation." },
  { w: "Distribute", p: "Verb", l: "B2", tr: "Dağıtmak / Paylaştırmak", ph: "/dɪˈstrɪb.juːt/", d: "Give shares of something to a number of recipients.", ex: "Distribute food and supplies to those in need." },
  { w: "Distribution", p: "Noun", l: "B2", tr: "Dağıtım / Dağılım", ph: "/ˌdɪs.trɪˈbjuː.ʃən/", d: "The way in which something is shared out.", ex: "Fair wealth distribution strengthens society." },
  { w: "District", p: "Noun", l: "A2", tr: "İlçe / Bölge / Semt", ph: "/ˈdɪs.trɪkt/", d: "An area of a country or city.", ex: "Kadikoy is a vibrant cultural district in Istanbul." },
  { w: "Diverse", p: "Adj.", l: "B2", tr: "Çeşitli / Farklı", ph: "/daɪˈvɜːs/", d: "Showing a great deal of variety.", ex: "A diverse team generates innovative ideas." },
  { w: "Diversity", p: "Noun", l: "B2", tr: "Çeşitlilik / Farklılık", ph: "/daɪˈvɜː.sə.ti/", d: "The state of being diverse; variety.", ex: "Cultural diversity enriches human society." },
  { w: "Divide", p: "Verb", l: "A2", tr: "Bölmek / Paylaştırmak", ph: "/dɪˈvaɪd/", d: "Separate or be separated into parts.", ex: "Divide the big goal into daily tasks." },
  { w: "Division", p: "Noun", l: "B1", tr: "Bölüm / Bölünme", ph: "/dɪˈvɪʒ.ən/", d: "The action of separating something into parts.", ex: "The software engineering division grew fast." },
  { w: "Document", p: "Noun", l: "A2", tr: "Belge / Doküman", ph: "/ˈdɒk.jə.mənt/", d: "A piece of written, printed, or electronic matter.", ex: "Save your document in the cloud safely." },
  { w: "Domestic", p: "Adj.", l: "B1", tr: "Yurtiçi / Evcil / Evle ilgili", ph: "/dəˈmes.tɪk/", d: "Relating to the running of a home or one's own country.", ex: "Domestic flights leave from Terminal 1." },
  { w: "Dominant", p: "Adj.", l: "B2", tr: "Baskın / Egemen", ph: "/ˈdɒm.ɪ.nənt/", d: "Most important, powerful, or influential.", ex: "English is the dominant language of tech." },
  { w: "Donate", p: "Verb", l: "B1", tr: "Bağışlamak", ph: "/dəʊˈneɪt/", d: "Give money or goods for a good cause.", ex: "Donate blood to save valuable human lives." },
  { w: "Draft", p: "Noun", l: "B1", tr: "Taslak / Müsvedde", ph: "/drɑːft/", d: "A preliminary version of a piece of writing.", ex: "Write a quick first draft without judgment." },
  { w: "Dramatic", p: "Adj.", l: "B2", tr: "Dramatik / Çarpıcı", ph: "/drəˈmæt.ɪk/", d: "Sudden and striking.", ex: "A dramatic improvement in test scores." },
  { w: "Duration", p: "Noun", l: "B2", tr: "Süre / Müddet", ph: "/djʊəˈreɪ.ʃən/", d: "The time during which something continues.", ex: "Flight duration is approximately three hours." },
  { w: "Dynamic", p: "Adj.", l: "B2", tr: "Dinamik / Hareketli", ph: "/daɪˈnæm.ɪk/", d: "Characterized by constant change, activity, or progress.", ex: "A dynamic environment fosters creativity." },

  // E
  { w: "Economy", p: "Noun", l: "B1", tr: "Ekonomi", ph: "/ɪˈkɒn.ə.mi/", d: "The state of a country in terms of goods and services.", ex: "A thriving sustainable green economy." },
  { w: "Economic", p: "Adj.", l: "B1", tr: "Ekonomik", ph: "/ˌiː.kəˈnɒm.ɪk/", d: "Relating to economics or the economy.", ex: "Economic stability benefits all citizens." },
  { w: "Edition", p: "Noun", l: "B1", tr: "Baskı / Edisyon", ph: "/ɪˈdɪʃ.ən/", d: "A particular form or version of a published text.", ex: "This is the third revised edition of the dictionary." },
  { w: "Educate", p: "Verb", l: "A2", tr: "Eğitmek", ph: "/ˈedʒ.u.keɪt/", d: "Give intellectual, moral, and social instruction.", ex: "Educate your mind through daily curiosity." },
  { w: "Education", p: "Noun", l: "A1", tr: "Eğitim", ph: "/ˌedʒ.uˈkeɪ.ʃən/", d: "The process of receiving or giving systematic instruction.", ex: "Education is the most powerful catalyst for change." },
  { w: "Effective", p: "Adj.", l: "B1", tr: "Etkili / Sonuç alıcı", ph: "/ɪˈfek.tɪv/", d: "Successful in producing a desired result.", ex: "Spaced repetition is an effective study method." },
  { w: "Efficiency", p: "Noun", l: "B2", tr: "Verimlilik / Etkinlik", ph: "/ɪˈfɪʃ.ən.si/", d: "The state of achieving maximum productivity.", ex: "Streamline code to improve server efficiency." },
  { w: "Elaborate", p: "Adj.", l: "B2", tr: "Ayrıntılı / Detaylı", ph: "/iˈlæb.ər.ət/", d: "Involving many carefully arranged parts.", ex: "They prepared an elaborate presentation." },
  { w: "Elderly", p: "Adj.", l: "B1", tr: "Yaşlı / İhtiyar", ph: "/ˈel.dəl.i/", d: "Old or aging person.", ex: "Always offer your seat to elderly travelers." },
  { w: "Election", p: "Noun", l: "B1", tr: "Seçim", ph: "/iˈlek.ʃən/", d: "A formal and organized choice by vote.", ex: "Citizens participate in democratic elections." },
  { w: "Electric", p: "Adj.", l: "A2", tr: "Elektrikli", ph: "/iˈlek.trɪk/", d: "Operating by means of electricity.", ex: "Electric vehicles reduce urban air pollution." },
  { w: "Electronic", p: "Adj.", l: "A2", tr: "Elektronik", ph: "/ˌel.ekˈtrɒn.ɪk/", d: "Having or operating with components such as microchips.", ex: "Store electronic receipts for bookkeeping." },
  { w: "Element", p: "Noun", l: "B1", tr: "Öğe / Unsur / Element", ph: "/ˈel.ɪ.mənt/", d: "An essential or characteristic part.", ex: "Trust is a fundamental element of any team." },
  { w: "Elevate", p: "Verb", l: "B2", tr: "Yükseltmek / Kaldırmak", ph: "/ˈel.ɪ.veɪt/", d: "Raise to a more important or higher position.", ex: "Good habits elevate your standard of living." },
  { w: "Eligible", p: "Adj.", l: "B2", tr: "Uygun / Hak sahibi", ph: "/ˈel.ɪ.dʒə.bəl/", d: "Having the right to do or obtain something.", ex: "All university graduates are eligible to apply." },
  { w: "Eliminate", p: "Verb", l: "B2", tr: "Ortadan kaldırmak / Elemek", ph: "/iˈlɪm.ɪ.neɪt/", d: "Completely remove or get rid of.", ex: "Automated testing eliminates human error." },
  { w: "Emotion", p: "Noun", l: "B1", tr: "Duygu / His", ph: "/iˈməʊ.ʃən/", d: "A strong feeling deriving from one's circumstances.", ex: "Express genuine emotion with honesty." },
  { w: "Emotional", p: "Adj.", l: "B1", tr: "Duygusal", ph: "/iˈməʊ.ʃən.əl/", d: "Relating to a person's emotions.", ex: "Music evokes deep emotional resonance." },
  { w: "Emperor", p: "Noun", l: "B1", tr: "İmparator", ph: "/ˈem.pər.ər/", d: "A sovereign ruler of an empire.", ex: "The ancient emperor commissioned grand monuments." },
  { w: "Emphasis", p: "Noun", l: "B2", tr: "Vurgu / Önem", ph: "/ˈem.fə.sɪs/", d: "Special importance, value, or prominence.", ex: "Place great emphasis on listening comprehension." },
  { w: "Employ", p: "Verb", l: "B1", tr: "İşe almak / İstihdam etmek", ph: "/ɪmˈplɔɪ/", d: "Give work to someone and pay them for it.", ex: "The tech company employs over two thousand engineers." },
  { w: "Employee", p: "Noun", l: "A2", tr: "Çalışan / Personel", ph: "/ɪmˈplɔɪ.iː/", d: "A person employed for wages or salary.", ex: "Happy employees build thriving enterprises." },
  { w: "Employer", p: "Noun", l: "A2", tr: "İşveren", ph: "/ɪmˈplɔɪ.ər/", d: "A person or organization that employs people.", ex: "A supportive employer encourages learning." },
  { w: "Employment", p: "Noun", l: "B1", tr: "İstihdam / İş", ph: "/ɪmˈplɔɪ.mənt/", d: "The state of having paid work.", ex: "Green technology creates high employment." },
  { w: "Enable", p: "Verb", l: "B1", tr: "Olanak sağlamak / Etkinleştirmek", ph: "/ɪˈneɪ.bəl/", d: "Give someone or something the authority or means to do.", ex: "Smartphones enable remote global collaboration." },
  { w: "Encounter", p: "Verb", l: "B2", tr: "Karşılaşmak / Rastlamak", ph: "/ɪŋˈkaʊn.tər/", d: "Unexpectedly be faced with or experience.", ex: "You will encounter inspiring people on your journey." },
  { w: "Encourage", p: "Verb", l: "B1", tr: "Cesaretlendirmek / Teşvik etmek", ph: "/ɪnˈkʌr.ɪdʒ/", d: "Give support, confidence, or hope to.", ex: "Teachers encourage students to think independently." },
  { w: "Energy", p: "Noun", l: "A2", tr: "Enerji / Güç", ph: "/ˈen.ə.dʒi/", d: "The strength and vitality required for physical or mental activity.", ex: "Start your day full of positive energy." },
  { w: "Engage", p: "Verb", l: "B2", tr: "İlgilenmek / Katılmak", ph: "/ɪnˈɡeɪdʒ/", d: "Participate or become involved in.", ex: "Engage in meaningful conversations." },
  { w: "Engine", p: "Noun", l: "A2", tr: "Motor / Makine", ph: "/ˈen.dʒɪn/", d: "A machine with moving parts that converts power into motion.", ex: "The electric engine runs quietly and smoothly." },
  { w: "Engineer", p: "Noun", l: "A2", tr: "Mühendis", ph: "/ˌen.dʒɪˈnɪər/", d: "A person who designs, builds, or maintains engines.", ex: "Software engineers build scalable digital tools." },
  { w: "Enormous", p: "Adj.", l: "B1", tr: "Devasa / Çok büyük", ph: "/ɪˈnɔː.məs/", d: "Very large in size, quantity, or extent.", ex: "The universe holds an enormous number of galaxies." },
  { w: "Ensure", p: "Verb", l: "B2", tr: "Sağlamak / Garantiye almak", ph: "/ɪnˈʃɔːr/", d: "Make certain that something will occur or be so.", ex: "Ensure that all data is backed up to the cloud." },
  { w: "Enterprise", p: "Noun", l: "B2", tr: "Girişim / Şirket", ph: "/ˈen.tə.praɪz/", d: "A project or business undertaking.", ex: "A bold entrepreneurial enterprise." },
  { w: "Entertain", p: "Verb", l: "A2", tr: "Eğlendirmek", ph: "/ˌen.təˈteɪn/", d: "Provide someone with amusement or enjoyment.", ex: "A good book can entertain and educate at once." },
  { w: "Entertainment", p: "Noun", l: "A2", tr: "Eğlence", ph: "/ˌen.təˈteɪn.mənt/", d: "The action of providing or being provided with amusement.", ex: "Live music offers wonderful evening entertainment." },
  { w: "Enthusiasm", p: "Noun", l: "B2", tr: "Coşku / Heyecan", ph: "/ɪnˈθjuː.zi.æz.əm/", d: "Intense and eager enjoyment, interest, or approval.", ex: "Approach every new challenge with enthusiasm." },
  { w: "Entire", p: "Adj.", l: "B1", tr: "Tüm / Bütün", ph: "/ɪnˈtaɪər/", d: "With no part left out; whole.", ex: "She spent the entire afternoon reading." },
  { w: "Entrance", p: "Noun", l: "A2", tr: "Giriş / Kapı", ph: "/ˈen.trəns/", d: "An opening, such as a door, that allows access.", ex: "The grand entrance to the historic palace." },
  { w: "Entry", p: "Noun", l: "B1", tr: "Giriş / Kayıt", ph: "/ˈen.tri/", d: "An act of going or coming in, or a single item in a list.", ex: "Each dictionary entry has a clear phonetic guide." },
  { w: "Envelope", p: "Noun", l: "A2", tr: "Zarf", ph: "/ˈen.və.ləʊp/", d: "A flat paper container for a letter.", ex: "Place the handwritten letter in this envelope." },
  { w: "Equip", p: "Verb", l: "B2", tr: "Donatmak / Teçhiz etmek", ph: "/ɪˈkwɪp/", d: "Supply with the necessary items for a purpose.", ex: "Equip yourself with strong linguistic skills." },
  { w: "Equipment", p: "Noun", l: "A2", tr: "Ekipman / Donanım", ph: "/ɪˈkwɪp.mənt/", d: "The necessary items for a particular purpose.", ex: "Carry proper hiking equipment in the mountains." },
  { w: "Equivalent", p: "Adj.", l: "B2", tr: "Eşdeğer / Denk", ph: "/ɪˈkwɪv.əl.ənt/", d: "Equal in value, amount, function, or meaning.", ex: "One hour of daily study is equivalent to great progress." },
  { w: "Era", p: "Noun", l: "B2", tr: "Çağ / Dönem / Devir", ph: "/ˈɪə.rə/", d: "A long and distinct period of history.", ex: "We are living in the revolutionary era of artificial intelligence." },
  { w: "Error", p: "Noun", l: "A2", tr: "Hata / Yanılgı", ph: "/ˈer.ər/", d: "A mistake.", ex: "Fix the syntax error in the code." },
  { w: "Escape", p: "Verb", l: "B1", tr: "Kaçmak / Kurtulmak", ph: "/ɪˈskeɪp/", d: "Break free from confinement or control.", ex: "Escape into a good book during the weekend." },
  { w: "Essay", p: "Noun", l: "A2", tr: "Deneme / Makale", ph: "/ˈes.eɪ/", d: "A short piece of writing on a particular subject.", ex: "She wrote an eloquent essay on philosophy." },
  { w: "Establish", p: "Verb", l: "B2", tr: "Kurmak / Tesis etmek", ph: "/ɪˈstæb.lɪʃ/", d: "Set up on a firm or permanent basis.", ex: "Establish a consistent daily learning habit." },
  { w: "Estimate", p: "Verb", l: "B2", tr: "Tahmin etmek / Değer biçmek", ph: "/ˈes.tɪ.meɪt/", d: "Roughly calculate or judge the value.", ex: "Experts estimate that the project will take two months." },
  { w: "Ethics", p: "Noun", l: "B2", tr: "Etik / Ahlak ilkeleri", ph: "/ˈeθ.ɪks/", d: "Moral principles that govern behavior.", ex: "Maintain high ethics in all research and business." },
  { w: "Evaluate", p: "Verb", l: "B2", tr: "Değerlendirmek", ph: "/ɪˈvæl.ju.eɪt/", d: "Form an idea of the amount, number, or value.", ex: "Evaluate your weekly progress to stay on track." },
  { w: "Event", p: "Noun", l: "A1", tr: "Etkinlik / Olay", ph: "/ɪˈvent/", d: "A thing that happens, especially one of importance.", ex: "The cultural event brought together international artists." },
  { w: "Evidence", p: "Noun", l: "B1", tr: "Kanıt / Delil", ph: "/ˈev.ɪ.dəns/", d: "The available body of facts indicating whether a belief is true.", ex: "Scientific evidence supports daily physical exercise." },
  { w: "Exact", p: "Adj.", l: "A2", tr: "Tam / Kesin", ph: "/ɪɡˈzækt/", d: "Not approximated in any way; precise.", ex: "Tell me the exact time of arrival." },
  { w: "Examine", p: "Verb", l: "B1", tr: "İncelemek / Muayene etmek", ph: "/ɪɡˈzæm.ɪn/", d: "Inspect someone or something thoroughly in detail.", ex: "Examine the sentence structure carefully." },
  { w: "Exceed", p: "Verb", l: "B2", tr: "Aşmak / Geçmek", ph: "/ɪkˈsiːd/", d: "Be greater in number or size than.", ex: "Her performance exceeded all expectations." },
  { w: "Excellent", p: "Adj.", l: "A1", tr: "Mükemmel / Harika", ph: "/ˈek.səl.ənt/", d: "Extremely good; outstanding.", ex: "You did an excellent job on this project!" },
  { w: "Exchange", p: "Verb", l: "A2", tr: "Değiş tokuş etmek / Bozdurmak", ph: "/ɪksˈtʃeɪndʒ/", d: "Give something and receive something of the same kind in return.", ex: "Exchange ideas openly during brainstorming." },
  { w: "Excite", p: "Verb", l: "A2", tr: "Heyecanlandırmak", ph: "/ɪkˈsaɪt/", d: "Cause strong feelings of enthusiasm and eagerness.", ex: "New travel adventures excite the soul." },
  { w: "Exclude", p: "Verb", l: "B2", tr: "Dışlamak / Hariç tutmak", ph: "/ɪkˈskluːd/", d: "Deny someone access to or bar someone from a place, group, or privilege.", ex: "Do not exclude any possibilities too early." },
  { w: "Excuse", p: "Noun", l: "A2", tr: "Bahane / Mazeret", ph: "/ɪkˈskjuːs/", d: "A reason put forward to defend or justify a fault.", ex: "Make progress, not excuses." },
  { w: "Executive", p: "Noun", l: "B2", tr: "Yönetici / İcracı", ph: "/ɪɡˈzek.jʊ.tɪv/", d: "A person with senior managerial responsibility in a business.", ex: "The chief executive announced new strategic goals." },
  { w: "Exercise", p: "Noun", l: "A1", tr: "Egzersiz / Alıştırma", ph: "/ˈek.sə.saɪz/", d: "Activity requiring physical effort.", ex: "Daily exercise improves mood and cardiovascular health." },
  { w: "Exhaust", p: "Verb", l: "B2", tr: "Tüketmek / Çok yormak", ph: "/ɪɡˈzɔːst/", d: "Drain of one's physical or mental resources completely.", ex: "A long day of travel can exhaust you physically." },
  { w: "Exhibit", p: "Verb", l: "B1", tr: "Sergilemek / Göstermek", ph: "/ɪɡˈzɪb.ɪt/", d: "Manifest or deliberately display.", ex: "Local artists exhibit their paintings in the gallery." },
  { w: "Exist", p: "Verb", l: "B1", tr: "Var olmak", ph: "/ɪɡˈzɪst/", d: "Have objective reality or being.", ex: "Countless species exist in the deep ocean." },
  { w: "Existence", p: "Noun", l: "B2", tr: "Varlık / Yaşam", ph: "/ɪɡˈzɪs.təns/", d: "The fact or state of living or having objective reality.", ex: "Philosophy ponders the meaning of human existence." },
  { w: "Expand", p: "Verb", l: "B2", tr: "Genişletmek / Büyütmek", ph: "/ɪkˈspænd/", d: "Become or make larger or more extensive.", ex: "Reading expands your active vocabulary and worldview." },
  { w: "Expansion", p: "Noun", l: "B2", tr: "Genişleme / Büyüme", ph: "/ɪkˈspæn.ʃən/", d: "The action of becoming larger or more extensive.", ex: "The international expansion of the company was a huge triumph." },
  { w: "Expect", p: "Verb", l: "A2", tr: "Beklemek / Ummak", ph: "/ɪkˈspekt/", d: "Regard something as likely to happen.", ex: "Expect success when you put in dedicated work." },
  { w: "Expectation", p: "Noun", l: "B1", tr: "Beklenti / Umut", ph: "/ˌek.spekˈteɪ.ʃən/", d: "A strong belief that something will happen.", ex: "Set realistic expectations for your daily goals." },
  { w: "Expense", p: "Noun", l: "A2", tr: "Masraf / Gider", ph: "/ɪkˈspens/", d: "The cost required for something.", ex: "Track your monthly expense sheet carefully." },
  { w: "Expensive", p: "Adj.", l: "A1", tr: "Pahalı", ph: "/ɪkˈspen.sɪv/", d: "Costing a lot of money.", ex: "Time is far more expensive than any material good." },
  { w: "Expert", p: "Noun", l: "A2", tr: "Uzman / Usta", ph: "/ˈek.spɜːt/", d: "A person who has a comprehensive and authoritative knowledge.", ex: "Consult a language learning expert for guidance." },
  { w: "Expertise", p: "Noun", l: "B2", tr: "Uzmanlık / İhtisas", ph: "/ˌek.spɜːˈtiːz/", d: "Expert skill or knowledge in a particular field.", ex: "She shared her deep technical expertise willingly." },
  { w: "Exploration", p: "Noun", l: "B1", tr: "Keşif / Araştırma", ph: "/ˌek.spləˈreɪ.ʃən/", d: "The action of traveling in or through an unfamiliar area in order to learn.", ex: "Space exploration reveals the wonders of the cosmos." },
  { w: "Explore", p: "Verb", l: "A2", tr: "Keşfetmek / Araştırmak", ph: "/ɪkˈsplɔːr/", d: "Travel in or through an unfamiliar area.", ex: "Explore historic neighborhoods on weekend mornings." },
  { w: "Export", p: "Verb", l: "B1", tr: "İhraç etmek", ph: "/ɪkˈspɔːt/", d: "Send goods or services to another country for sale.", ex: "Turkey exports textiles, hazelnuts, and cars globally." },
  { w: "Expose", p: "Verb", l: "B2", tr: "Maruz bırakmak / Açığa çıkarmak", ph: "/ɪkˈspəʊz/", d: "Make something visible by uncovering it, or leave unprotected.", ex: "Expose your mind to natural spoken English daily." },
  { w: "Exposure", p: "Noun", l: "B2", tr: "Maruz kalma / Tanıtım", ph: "/ɪkˈspəʊ.ʒər/", d: "The state of being exposed to contact with something.", ex: "Daily exposure to English podcasts accelerates fluency." },
  { w: "Express", p: "Verb", l: "A2", tr: "İfade etmek / Açıklamak", ph: "/ɪkˈspres/", d: "Convey a thought or feeling in words or by gestures.", ex: "Express your gratitude to those who help you." },
  { w: "Expression", p: "Noun", l: "A2", tr: "İfade / Deyim", ph: "/ɪkˈspreʃ.ən/", d: "The look on someone's face, or a word/phrase.", ex: "Learn useful colloquial idioms and expressions." },
  { w: "Extend", p: "Verb", l: "B1", tr: "Uzatmak / Genişletmek", ph: "/ɪkˈstend/", d: "Cause to cover a larger area or longer time.", ex: "Extend your vocabulary study session by ten minutes." },
  { w: "Extension", p: "Noun", l: "B1", tr: "Uzantı / Uzatma", ph: "/ɪkˈsten.ʃən/", d: "A part that is added to something to enlarge or prolong it.", ex: "Install a dictionary extension on your browser." },
  { w: "Extensive", p: "Adj.", l: "B2", tr: "Kapsamlı / Geniş çaplı", ph: "/ɪkˈsten.sɪv/", d: "Covering or affecting a large area.", ex: "She did extensive research on Turkish history." },
  { w: "Extraordinary", p: "Adj.", l: "B2", tr: "Olağanüstü / Sıradışı", ph: "/ɪkˈstrɔː.dən.ri/", d: "Very unusual or remarkable.", ex: "The ancient architecture of Hagia Sophia is extraordinary." },
  { w: "Extreme", p: "Adj.", l: "B1", tr: "Aşırı / Uç", ph: "/ɪkˈstriːm/", d: "Reaching a high or the highest degree; very severe.", ex: "Avoid extreme workout routines without proper rest." },
];

console.log("Compiling massive 1000+ vocabulary corpus...");

massiveData.forEach(item => {
  const cleanWord = item.w.trim();
  const id = `w-${cleanWord.toLowerCase().replace(/[^a-z0-9]/g, '-')}`;
  if (!wordsMap.has(id)) {
    wordsMap.set(id, {
      id,
      word: cleanWord,
      phonetic: item.ph || `/${cleanWord.toLowerCase()}/`,
      partOfSpeech: item.p || "Noun",
      level: item.l || "A1",
      translation: item.tr,
      definition: item.d || `Definition of ${cleanWord}`,
      example: item.ex || `Example sentence with ${cleanWord}.`,
      exampleTranslation: item.exTr || `Örnek cümle (${cleanWord}).`,
      synonyms: [],
      lists: ["oxford-3000"],
      mastery: Math.floor(Math.random() * 30),
    });
  }
});

const finalAll = Array.from(wordsMap.values()).sort((a, b) => a.word.localeCompare(b.word));

fs.writeFileSync(jsonPath, JSON.stringify(finalAll, null, 2), 'utf-8');

console.log(`====================================================`);
console.log(`🚀 BAŞARILI: Toplam ${finalAll.length} kelimelik devasa sözlük verisi hazırlandı!`);
console.log(`====================================================`);
